# -*- coding: utf-8 -*-
"""Datos Claudio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvZ9kDjxOSMoyYs3bxAiQNVjO5crOjRD
"""

# Dependencias instaladas via workflow (requirements)

# ============================================
# CONFIGURACIÓN — EDITÁ SOLO ESTA SECCIÓN
# ============================================

# Tu Google Sheet ID
SHEET_ID = "1Tuy0X7VMylI0-4PA1dSWPUK4_-iqPmczPqfjTUtDldY"

# Benchmark para fuerza relativa
BENCHMARK = "SPY"

# Tickers organizados por categoría
TICKERS = {
    "ADRs Argentina": [
        "YPF", "GGAL", "BMA", "LOMA", "MELI", "GLOB", "SUPV", "BBAR",
        "CEPU", "PAM", "TGS", "IRS", "BIOX", "VIST", "CAAP", "ADGO"
    ],
    "CEDEARs Tecnología": [
        "AAPL", "MSFT", "GOOGL", "META", "AMZN", "NVDA", "TSLA", "NFLX",
        "AMD", "INTC", "QCOM", "AVGO", "MU", "AMAT", "LRCX", "MRVL",
        "TXN", "TSM", "ARM", "ASML", "ADBE", "CRM", "NOW", "TEAM",
        "SNOW", "DOCU", "TWLO", "SHOP", "UBER", "ABNB", "BKNG",
        "PYPL", "XYZ", "COIN", "MSTR", "PLTR", "PANW", "CSCO", "IBM",
        "ORCL", "SAP", "INFY", "ACN", "ADP", "MSI", "GRMN",
        "EBAY", "ETSY", "PINS", "SNAP", "SPOT", "ZM", "RBLX",
        "ROKU", "SONY", "NTCO", "SE", "JD", "BIDU", "BABA",
        "NTES", "PDD", "TCOM", "AI", "PATH", "UPST", "HOOD",
        "RKLB", "ASTS", "ALAB", "RGTI", "OKLO", "IREN",
        "IBIT", "ETHA", "ARKK", "CRWV", "TEM", "SATL",
        "ANET", "SNDK", "NBIS", "ONDS"
    ],
    "CEDEARs Finanzas": [
        "JPM", "BAC", "GS", "C", "WFC", "USB", "BK", "AXP",
        "V", "MA", "PYPL", "SCHW", "BX", "MS", "AIG",
        "BBD", "ITUB", "BSBR", "SAN", "BBV", "ING",
        "HSBC", "HDB", "IBN", "KB", "MFG", "MUFG", "NMR",
        "XP", "PAGS", "STNE", "NU", "HOOD", "FISV", "O"
    ],
    "CEDEARs Salud": [
        "JNJ", "PFE", "ABBV", "MRK", "AMGN", "GILD", "BIIB",
        "MRNA", "BMY", "AZN", "NVS", "GSK", "LLY", "MDT",
        "ISRG", "DHR", "TMO", "UNH", "CVS", "VRTX", "MDLZ", "HIMS"
    ],
    "CEDEARs Consumo & Retail": [
        "KO", "PEP", "MCD", "WMT", "COST", "TGT", "HD", "NKE",
        "SBUX", "DIS", "MO", "PM", "PG", "CL", "KMB", "UL",
        "DEO", "HSY", "MDLZ", "SYY", "TJX", "ROST", "URBN",
        "ANF", "WBA", "DECK", "HMC", "TM", "CAJ", "TTM"
    ],
    "CEDEARs Energía & Materiales": [
        "XOM", "CVX", "BP", "SHEL", "TTE", "OXY", "HAL", "SLB",
        "BKR", "PSX", "CEG", "FCX", "RIO", "BHP", "VALE",
        "GOLD", "NEM", "AEM", "GFI", "HMY", "KGC", "PAAS",
        "MUX", "HL", "CDE", "NG", "AUY", "GGB", "SID",
        "NUE", "SCCO", "MOS", "DOW", "LND", "BNG",
        "SUZ", "BAK", "UGP", "PBR", "PTR", "SNP",
        "COP", "GLNG", "MP", "CCJ", "NEE"
    ],
    "CEDEARs Industria & Aero": [
        "BA", "CAT", "MMM", "GE", "HON", "RTX", "LMT", "HWM",
        "DE", "PCAR", "UNP", "FDX", "DAL", "AAL", "UAL",
        "GM", "F", "STLA", "HOG", "ERJ", "TSLA",
        "RACE", "HPQ", "IP", "AVY", "IFF", "GLW",
        "ECL", "EMR", "JCI", "PKS", "CX", "ARCO"
    ],
    "CEDEARs ETFs Renta Variable": [
        "SPY", "QQQ", "DIA", "IWM", "VIG", "VEA",
        "EWZ", "EEM", "IEMG", "EFA", "EWJ", "FXI",
        "ILF", "ACWI", "IEUR", "IJH",
        "XLK", "XLF", "XLE", "XLV", "XLI", "XLB",
        "XLC", "XLY", "XLP", "XLRE", "XLU",
        "SMH", "IBB", "ITA", "COPX", "URA",
        "ARKK", "TQQQ", "SH", "PSQ",
        "ESGU", "IVE", "SPGI",
        "CIBR", "CLOU", "BOTZ", "KRE", "XOP", "ICLN"
    ],
    "CEDEARs ETFs Commodities & Bonos": [
        "GLD", "SLV", "IAU", "GDX", "USO",
        "TLT", "HYG", "VXX"
    ],
    "CEDEARs Brasil": [
        "VALE", "PBR", "ITUB", "BBD", "BSBR", "SUZ", "GGB",
        "BAK", "BRFS", "EBR", "ELP", "SBS", "UGP",
        "ABEV", "PAGS", "STNE", "XP", "CAAP"
    ],
    "CEDEARs Europa & Asia": [
        "ASML", "SAP", "ADBE", "AZN", "NVS", "GSK", "BAYER",
        "BAYN", "BAS", "EOAN", "NEC1", "MBG", "BSN",
        "VOD", "T", "TMUS", "VZ", "NGG", "ORAN",
        "PHG", "ING", "BBV", "SAN",
        "TTE", "ENI", "SHEL", "BP",
        "RIO", "BHP", "LFC", "SNP", "PTR",
        "HMC", "TM", "SONY", "MUFG", "MFG", "NMR",
        "TSM", "SMSN", "INFY", "HDB", "IBN",
        "BABA", "JD", "BIDU", "NTES", "PDD", "SE"
    ]
}

# ETF de sector por ticker (para comparar vs su sector)
ETF_SECTOR = {
    # Tecnologia
    "AAPL": "XLK", "ACN": "XLK", "ADBE": "XLK", "AI": "XLK",
    "ALAB": "XLK", "AMAT": "XLK", "AMD": "XLK", "ANET": "XLK",
    "ARM": "XLK", "AVGO": "XLK", "CRM": "XLK", "CRWV": "XLK",
    "CSCO": "XLK", "DOCU": "XLK", "GLOB": "XLK", "GLW": "XLK",
    "GRMN": "XLK", "HPQ": "XLK", "IBM": "XLK", "INTC": "XLK",
    "IREN": "XLK", "LRCX": "XLK", "MRVL": "XLK", "MSFT": "XLK",
    "MSI": "XLK", "MSTR": "XLK", "MU": "XLK", "NBIS": "XLK",
    "NOW": "XLK", "NVDA": "XLK", "ORCL": "XLK", "PANW": "XLK",
    "PATH": "XLK", "PLTR": "XLK", "QCOM": "XLK", "RGTI": "XLK",
    "SHOP": "XLK", "SNDK": "XLK", "SNOW": "XLK", "TEAM": "XLK",
    "TWLO": "XLK", "TXN": "XLK", "ZM": "XLK",

    # Financiero
    "AIG": "XLF", "AXP": "XLF", "BAC": "XLF", "BBAR": "XLF",
    "BK": "XLF", "BMA": "XLF", "BX": "XLF", "C": "XLF",
    "COIN": "XLF", "FISV": "XLF", "GGAL": "XLF", "GS": "XLF",
    "HOOD": "XLF", "JPM": "XLF", "MA": "XLF", "MS": "XLF",
    "PYPL": "XLF", "SCHW": "XLF", "SPGI": "XLF", "SUPV": "XLF",
    "UPST": "XLF", "USB": "XLF", "V": "XLF", "WFC": "XLF",
    "XYZ": "XLF",

    # Salud
    "ABBV": "XLV", "AMGN": "XLV", "BIIB": "XLV", "BMY": "XLV",
    "CVS": "XLV", "DHR": "XLV", "GILD": "XLV", "HIMS": "XLV",
    "ISRG": "XLV", "JNJ": "XLV", "LLY": "XLV", "MDT": "XLV",
    "MRK": "XLV", "MRNA": "XLV", "PFE": "XLV", "TEM": "XLV",
    "TMO": "XLV", "UNH": "XLV", "VRTX": "XLV",

    # Energia
    "BKR": "XLE", "COP": "XLE", "CVX": "XLE", "HAL": "XLE",
    "OXY": "XLE", "PSX": "XLE", "SLB": "XLE", "VIST": "XLE",
    "XOM": "XLE", "YPF": "XLE",

    # Consumo discrecional
    "ABNB": "XLY", "AMZN": "XLY", "ANF": "XLY", "ARCO": "XLY",
    "BKNG": "XLY", "DECK": "XLY", "EBAY": "XLY", "ETSY": "XLY",
    "F": "XLY", "GM": "XLY", "HD": "XLY", "HOG": "XLY",
    "MCD": "XLY", "MELI": "XLY", "NKE": "XLY", "ROST": "XLY",
    "SBUX": "XLY", "TJX": "XLY", "TSLA": "XLY", "URBN": "XLY",

    # Consumo basico
    "CL": "XLP", "COST": "XLP", "HSY": "XLP", "KMB": "XLP",
    "KO": "XLP", "MDLZ": "XLP", "MO": "XLP", "PEP": "XLP",
    "PG": "XLP", "PM": "XLP", "SYY": "XLP", "TGT": "XLP",
    "WBA": "XLP", "WMT": "XLP",

    # Industriales
    "AAL": "XLI", "ADP": "XLI", "BA": "XLI", "CAAP": "XLI",
    "CAT": "XLI", "DAL": "XLI", "DE": "XLI", "EMR": "XLI",
    "FDX": "XLI", "GE": "XLI", "HON": "XLI", "HWM": "XLI",
    "JCI": "XLI", "LMT": "XLI", "MMM": "XLI", "PCAR": "XLI",
    "RTX": "XLI", "UAL": "XLI", "UBER": "XLI", "UNP": "XLI",

    # Materiales
    "AVY": "XLB", "BIOX": "XLB", "DOW": "XLB", "ECL": "XLB",
    "FCX": "XLB", "IFF": "XLB", "IP": "XLB", "LOMA": "XLB",
    "MOS": "XLB", "MP": "XLB", "NEM": "XLB", "NUE": "XLB",
    "SCCO": "XLB",

    # Comunicaciones
    "DIS": "XLC", "GOOGL": "XLC", "META": "XLC", "NFLX": "XLC",
    "PINS": "XLC", "RBLX": "XLC", "ROKU": "XLC", "SNAP": "XLC",
    "SPOT": "XLC", "T": "XLC", "TMUS": "XLC", "VZ": "XLC",

    # Utilities
    "CEG": "XLU", "CEPU": "XLU", "NEE": "XLU", "PAM": "XLU",
    "TGS": "XLU",

    # Real Estate
    "IRS": "XLRE", "O": "XLRE",

    # Brasil / Latam
    "ABEV": "EWZ", "BAK": "EWZ", "BBD": "EWZ", "BSBR": "EWZ",
    "GGB": "EWZ", "ITUB": "EWZ", "LND": "EWZ", "PAGS": "EWZ",
    "PBR": "EWZ", "SBS": "EWZ", "SID": "EWZ", "STNE": "EWZ",
    "SUZ": "EWZ", "UGP": "EWZ", "VALE": "EWZ", "XP": "EWZ",

    # China
    "BABA": "FXI", "BIDU": "FXI", "JD": "FXI", "NTES": "FXI",
    "PDD": "FXI", "TCOM": "FXI",

    # Japon
    "HMC": "EWJ", "MFG": "EWJ", "MUFG": "EWJ", "NMR": "EWJ",
    "SONY": "EWJ", "TM": "EWJ",

    # Desarrollados ex-US (Europa/UK/otros)
    "ASML": "EFA", "AZN": "EFA", "BHP": "EFA", "BP": "EFA",
    "DEO": "EFA", "GLNG": "EFA", "GSK": "EFA", "HSBC": "EFA",
    "ING": "EFA", "MBG": "EFA", "NGG": "EFA", "NVS": "EFA",
    "PHG": "EFA", "RACE": "EFA", "RIO": "EFA", "SAN": "EFA",
    "SAP": "EFA", "SHEL": "EFA", "STLA": "EFA", "TTE": "EFA",
    "UL": "EFA", "VOD": "EFA",

    # Emergentes ex-China/Brasil/Japon (India, Taiwan, Corea, Singapur)
    "HDB": "EEM", "IBN": "EEM", "INFY": "EEM", "KB": "EEM",
    "NU": "EEM", "SE": "EEM", "TSM": "EEM",

    # Mexico / Latam amplio
    "CX": "ILF",

    # Mineras de oro y plata (sin sectorial propio en la spec)
    "AEM": "GDX", "AUY": "GDX", "CDE": "GDX", "GFI": "GDX",
    "GOLD": "GDX", "HL": "GDX", "HMY": "GDX", "KGC": "GDX",
    "MUX": "GDX", "NG": "GDX", "PAAS": "GDX",

    # Uranio / nuclear (sin sectorial propio en la spec)
    "CCJ": "URA", "OKLO": "URA",

    # Aeroespacial / space (sin sectorial propio en la spec, incluye small caps de nicho)
    "ASTS": "ITA", "RKLB": "ITA", "SATL": "ITA"
}

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime

def calcular_rsi(close, periodo=14):
    # Wilder's Smoothing (RMA) — igual a TradingView
    delta = close.diff()
    ganancia = delta.clip(lower=0)
    perdida = (-delta.clip(upper=0))
    alpha = 1 / periodo
    avg_gan = ganancia.ewm(alpha=alpha, min_periods=periodo, adjust=False).mean()
    avg_per = perdida.ewm(alpha=alpha, min_periods=periodo, adjust=False).mean()
    rs = avg_gan / avg_per
    return round((100 - (100 / (1 + rs))).iloc[-1], 2)

def calcular_volatilidad_relativa(close, high, low, ruedas_corto=5, ruedas_largo=252):
    """
    Promedio del rango diario H-L/Close de los últimos 5 días vs histórico 1 año.
    Captura velas amplias individuales (ej: +20% en un día) y semanas extendidas.
    < 1 = velas más estrechas que de costumbre (comprimido)
    > 1 = velas más anchas que de costumbre (extendido/volátil)
    """
    if len(close) < ruedas_largo + ruedas_corto:
        return None
    rango_pct = ((high - low) / close).dropna()
    if len(rango_pct) < ruedas_largo:
        return None
    avg_5d   = rango_pct.tail(ruedas_corto).mean()
    avg_hist = rango_pct.tail(ruedas_largo).mean()
    if avg_hist == 0:
        return None
    return round(avg_5d / avg_hist, 2)

def calcular_volumen_inusual(volume, ruedas=20):
    if len(volume) < ruedas + 1:
        return None
    vol_hoy      = volume.iloc[-1]
    vol_promedio = volume.iloc[-ruedas-1:-1].mean()
    if vol_promedio == 0:
        return None
    return round((vol_hoy / vol_promedio - 1) * 100, 2)

RS_LOOKBACK_MIN = 60  # ~3 meses -- por debajo de esto el percentrank no es confiable

def calcular_rs_score(close_ticker, close_spy, periodo_sma=50, lookback=252):
    df = pd.DataFrame({"ticker": close_ticker, "spy": close_spy}).dropna()
    # Historial corto (spin-offs/IPOs recientes, ej. SNDK desde 2/2025): en vez
    # de devolver todo None y dejar el pilar de Fuerza Relativa ciego durante
    # el primer año de cotizacion, usar como lookback todo lo disponible.
    # Se reserva margen de 22 ruedas para que "ayer/semana/mes" tambien caigan
    # dentro de la ventana valida del percentrank (si no, quedan en NaN aunque
    # el valor de hoy si se calcule). Piso de RS_LOOKBACK_MIN ruedas para que
    # el percentrank siga siendo estadisticamente razonable.
    lb = min(lookback, len(df) - 22)
    if lb < RS_LOOKBACK_MIN:
        return None, None, None, None, None, None, None, None, None

    df["fr"]     = df["ticker"] / df["spy"]
    df["sma_fr"] = df["fr"].rolling(window=periodo_sma).mean()

    def percentrank_tv(series, length):
        """
        Replica exacta de ta.percentrank de TradingView:
        cuenta cuántos de los últimos 'length' valores anteriores
        son MENORES al valor actual (excluye el valor actual)
        """
        scores = []
        arr = series.values
        for i in range(len(arr)):
            if i < length:
                scores.append(np.nan)
            else:
                ventana = arr[i-length:i]
                actual  = arr[i]
                rank    = (ventana < actual).sum() / length * 100
                scores.append(round(rank, 2))
        return pd.Series(scores, index=series.index)

    df["rs_score"] = percentrank_tv(df["fr"], lb)

    ultimo = df.iloc[-1]
    ayer   = df.iloc[-2]
    semana = df.iloc[-6]  if len(df) >= 6  else df.iloc[0]
    mes    = df.iloc[-22] if len(df) >= 22 else df.iloc[0]

    sobre_sma = "✅ Sí" if ultimo["fr"] > ultimo["sma_fr"] else "❌ No"

    return (
        round(ultimo["rs_score"], 1),
        round(ayer["rs_score"],   1),
        round(semana["rs_score"], 1),
        round(mes["rs_score"],    1),
        sobre_sma,
        round(float(ultimo["fr"]), 6),
        round(float(ayer["fr"]),   6),
        round(float(semana["fr"]), 6),
        round(float(mes["fr"]),    6),
    )

def rs_score_series(close_ticker, close_spy, lookback=252):
    """Serie completa de RS Score (percentrank de ticker/spy), dia por dia.
    Standalone (no comparte tupla con calcular_rs_score) para no tocar esa
    funcion ya probada en produccion. Usada para leer el RS Score en una
    rueda especifica del pasado (ej. el dia de contacto con la EMA200).
    Mismo lookback dinamico que calcular_rs_score() para tickers con poco
    historial (ver RS_LOOKBACK_MIN)."""
    df = pd.DataFrame({"ticker": close_ticker, "spy": close_spy}).dropna()
    lb = min(lookback, len(df) - 1)
    if lb < RS_LOOKBACK_MIN:
        return None
    fr = df["ticker"] / df["spy"]
    arr = fr.values
    scores = []
    for i in range(len(arr)):
        if i < lb:
            scores.append(np.nan)
        else:
            ventana = arr[i-lb:i]
            rank = (ventana < arr[i]).sum() / lb * 100
            scores.append(round(rank, 2))
    return pd.Series(scores, index=fr.index)

def atr14_pct(df):
    """ATR de 14 ruedas expresado como % del precio actual."""
    if df is None or len(df) < 15:
        return None
    try:
        high  = df['High']
        low   = df['Low']
        close = df['Close']
        prev  = close.shift(1)
        tr = pd.concat([
            high - low,
            (high - prev).abs(),
            (low  - prev).abs()
        ], axis=1).max(axis=1)
        atr14  = tr.tail(14).mean()
        precio = close.iloc[-1]
        if precio <= 0:
            return None
        return round(float(atr14 / precio * 100), 4)
    except:
        return None

def vol_anual_pct(df):
    """Volatilidad histórica anualizada (252 ruedas) expresada como %."""
    if df is None or len(df) < 20:
        return None
    try:
        rets = df['Close'].pct_change().dropna()
        if len(rets) < 20:
            return None
        return round(float(rets.std() * (252 ** 0.5) * 100), 4)
    except:
        return None


def _atr14_series(df):
    """Serie completa de ATR14 (True Range promedio de 14 ruedas), no solo el ultimo valor."""
    try:
        high, low, close = df['High'], df['Low'], df['Close']
        prev = close.shift(1)
        tr = pd.concat([
            high - low,
            (high - prev).abs(),
            (low  - prev).abs()
        ], axis=1).max(axis=1)
        return tr.rolling(14).mean()
    except Exception:
        return None


def avance_pico_15r(df):
    """Avance Pico 15r % — estiramiento reciente medido contra el PICO de la
    ventana, no contra el cierre de hoy. Motivo (caso CVX): si el papel subió
    y corrigió parte en las últimas ruedas, medir cierre-a-cierre esconde el
    estiramiento real; contra el pico queda capturado. cierre_base usa el menor
    entre el cierre de hace 15 ruedas y el mínimo de cierre de la ventana, para
    anclar bien la base de recuperaciones en V. Reemplaza a la vieja
    'Var 10 Ruedas %' (Warren Score v2.3)."""
    if df is None or len(df) < 16:
        return None
    try:
        close, high = df['Close'], df['High']
        pico_15r          = high.tail(15).max()
        cierre_hace_15    = close.iloc[-16]
        min_close_ventana = close.tail(15).min()
        cierre_base       = min(cierre_hace_15, min_close_ventana)
        if cierre_base <= 0:
            return None
        return round(float((pico_15r / cierre_base - 1) * 100), 2)
    except Exception:
        return None


def choppiness_eficiencia(df):
    """Choppiness (ATR14% actual vs hace 20 ruedas) y Eficiencia (Kaufman ER, 10 ruedas).
    Detecta 'volatilidad sin dirección' — velas grandes sin avance neto, firma de
    posible distribución (Warren Score v2.3, caso VOD)."""
    if df is None or len(df) < 35:
        return {'Choppiness': None, 'Eficiencia 10d': None}
    try:
        close = df['Close']
        atr14_abs = _atr14_series(df)
        if atr14_abs is None:
            return {'Choppiness': None, 'Eficiencia 10d': None}
        atr14_pct_ser = atr14_abs / close * 100
        atr_hoy = atr14_pct_ser.iloc[-1]
        atr_20r = atr14_pct_ser.iloc[-21]
        choppiness = (round(float(atr_hoy / atr_20r), 4)
                      if pd.notna(atr_hoy) and pd.notna(atr_20r) and atr_20r > 0 else None)

        cambio_neto = abs(close.iloc[-1] - close.iloc[-11])
        recorrido   = close.tail(11).diff().abs().sum()
        eficiencia  = round(float(cambio_neto / recorrido), 4) if recorrido > 0 else None

        return {'Choppiness': choppiness, 'Eficiencia 10d': eficiencia}
    except Exception:
        return {'Choppiness': None, 'Eficiencia 10d': None}


# ── Panel "Regreso a la EMA200" — visitas raras a la media de largo plazo ──
EMA200_CERCA_ATR = 2.0   # "cerca de la EMA200" = |precio - EMA200| <= CERCA_ATR x ATR14
EMA200_RACHA_MIN = 80    # ruedas minimas de alejamiento previo para que la visita sea "rara" (~4 meses)
EMA200_VENTANA   = 15    # la visita es "actual" si ocurrio dentro de las ultimas 15 ruedas

def visita_ema200(close, ema200, atr14, cerca_atr=EMA200_CERCA_ATR, racha_min=EMA200_RACHA_MIN, ventana=EMA200_VENTANA):
    """
    Detecta visitas raras a la EMA200: un acercamiento actual precedido por
    una racha larga de alejamiento (no la frecuencia anual, que solo informa).
    close/ema200/atr14: arrays o series alineados, mismo largo (>= 260 ruedas).
    """
    try:
        c = np.asarray(close, dtype=float)
        e = np.asarray(ema200, dtype=float)
        a = np.asarray(atr14, dtype=float)
        n = len(c)
        if n < 260:
            return None
        if np.isnan(a[-1]) or a[-1] <= 0:
            return None  # ATR no computable -> el umbral "cerca" tampoco lo es

        valid = ~np.isnan(a) & (a > 0)
        cerca = np.zeros(n, dtype=bool)
        cerca[valid] = np.abs(c[valid] - e[valid]) <= cerca_atr * a[valid]

        freq = round(float(cerca[-252:].mean() * 100), 1) if n >= 252 else round(float(cerca.mean() * 100), 1)
        dist_atrs = round(float((c[-1] - e[-1]) / a[-1]), 2)

        idx_visitas = [i for i in range(max(0, n - ventana), n) if cerca[i]]
        if not idx_visitas:
            return {'visita': False, 'racha': None, 'freq': freq, 'dist_atrs': dist_atrs}

        # inicio del acercamiento actual: retroceder mientras siga "cerca"
        inicio = idx_visitas[0]
        while inicio - 1 >= 0 and cerca[inicio - 1]:
            inicio -= 1

        # racha de alejamiento previa al acercamiento actual
        racha = 0
        j = inicio - 1
        while j >= 0 and not cerca[j]:
            racha += 1
            j -= 1
        # si la racha llega hasta el principio de la serie disponible, se toma tal cual (no None)

        return {'visita': racha >= racha_min, 'racha': racha, 'freq': freq, 'dist_atrs': dist_atrs}
    except Exception:
        return None

# ── EMA200 Reversal Score — clímax de volumen + repunte de RS en el contacto ──
EMA200R_CONTACTO_PCT  = 1.0   # "en contacto" = distancia a la EMA200 <= 1% del precio
EMA200R_VENTANA       = 10    # el contacto cuenta si ocurrió en las últimas 10 ruedas
EMA200R_CLIMAX_MARGEN = 3     # la vela de clímax se busca en contacto ± 3 ruedas

def ema200_reversal_features(hist, ema200_series, rs_series):
    """
    Features para el EMA200 Reversal Score (calculado en el frontend):
    - contacto_ruedas: ruedas atrás (0=hoy) del contacto más reciente con la
      EMA200 (distancia <= 1% del precio) dentro de las últimas 10 ruedas.
    - racha_previa: ruedas que estuvo lejos de la EMA200 (> 1%) antes de que
      empezara este acercamiento (cuanto más rara la visita, más vale).
    - dist_hace20: Dist EMA200 % de hace 20 ruedas (para ver si "venía de arriba").
    - climax_vol_ratio / climax_pos_cierre: la vela de mayor volumen dentro de
      contacto ± 3 ruedas (vela de clímax/absorción) y su cierre relativo a su rango.
    - rs_en_contacto: RS Score en la rueda del contacto.
    - precio_sobre_climax: si el precio actual ya superó el máximo de la vela de clímax.
    Devuelve None si no hay suficiente historia o no hubo contacto en ventana.
    """
    try:
        close  = hist['Close'].values
        high   = hist['High'].values
        low    = hist['Low'].values
        volume = hist['Volume'].values
        ema200 = ema200_series.values
        n = len(close)
        if n < 260 or rs_series is None:
            return None

        valid = ~np.isnan(ema200) & (ema200 != 0)
        cerca = np.zeros(n, dtype=bool)
        cerca[valid] = np.abs(close[valid] - ema200[valid]) / np.abs(ema200[valid]) * 100 <= EMA200R_CONTACTO_PCT

        contacto_ruedas = None
        for ago in range(EMA200R_VENTANA):
            idx = n - 1 - ago
            if idx >= 0 and cerca[idx]:
                contacto_ruedas = ago
                break
        if contacto_ruedas is None:
            return None

        contacto_idx = n - 1 - contacto_ruedas

        # racha de alejamiento previa al acercamiento actual (mismo criterio
        # que visita_ema200, pero con "cerca" definido en % en vez de ATRs)
        inicio = contacto_idx
        while inicio - 1 >= 0 and cerca[inicio - 1]:
            inicio -= 1
        racha_previa = 0
        j = inicio - 1
        while j >= 0 and not cerca[j]:
            racha_previa += 1
            j -= 1

        idx20 = n - 21
        dist_hace20 = None
        if idx20 >= 0 and not np.isnan(ema200[idx20]) and ema200[idx20] != 0:
            dist_hace20 = round(float((close[idx20] - ema200[idx20]) / ema200[idx20] * 100), 2)

        lo = max(0, contacto_idx - EMA200R_CLIMAX_MARGEN)
        hi = min(n - 1, contacto_idx + EMA200R_CLIMAX_MARGEN)
        climax_idx = max(range(lo, hi + 1), key=lambda i: volume[i])

        climax_vol_ratio = None
        if climax_idx >= 20:
            vol_prom20 = float(np.mean(volume[climax_idx-20:climax_idx]))
            if vol_prom20 > 0:
                climax_vol_ratio = round(float(volume[climax_idx]) / vol_prom20, 2)

        rango = high[climax_idx] - low[climax_idx]
        climax_pos_cierre = 0.5 if rango <= 0 else round(float((close[climax_idx] - low[climax_idx]) / rango), 3)

        rs_en_contacto = None
        pos_rs = len(rs_series) - 1 - contacto_ruedas
        if pos_rs >= 0:
            val = rs_series.iloc[pos_rs]
            if not pd.isna(val):
                rs_en_contacto = round(float(val), 1)

        precio_sobre_climax = bool(close[-1] > high[climax_idx])

        return {
            'contacto_ruedas':     contacto_ruedas,
            'racha_previa':        racha_previa,
            'dist_hace20':         dist_hace20,
            'climax_vol_ratio':    climax_vol_ratio,
            'climax_pos_cierre':   climax_pos_cierre,
            'rs_en_contacto':      rs_en_contacto,
            'precio_sobre_climax': precio_sobre_climax,
        }
    except Exception:
        return None

def detectar_base(df):
    """
    Detecta la base estructural de un papel (para Warren Score v2 Pilar D).
    Retorna dict con semanas, prof, pos, voltrend — o None en cada campo si no computable.

    'minimo' y 'tramo_inicio' (agregados para el modificador de sacudon,
    Warren Score v3.1) exponen valores YA calculados internamente para
    profundidad/voltrend -- no cambian nada de lo que Pilar D usa ni de
    como se calculan semanas/prof/pos/voltrend.
    """
    NULL = {'semanas': None, 'prof': None, 'pos': None, 'voltrend': None,
            'minimo': None, 'tramo_inicio': None}
    try:
        if df is None or len(df) < 30:
            return NULL
        # Renombrar columnas a minúsculas para uniformidad
        df = df.copy()
        df.columns = [c.lower() for c in df.columns]
        if 'close' not in df.columns or 'high' not in df.columns:
            return NULL

        VENTANA = 130  # ~26 semanas
        reciente = df.tail(VENTANA)
        pivote_alto = reciente['high'].max()
        fecha_pivote = reciente['high'].idxmax()

        # Si el máximo está en las últimas 5 ruedas, retroceder al máximo previo
        if fecha_pivote >= df.index[-5]:
            reciente2 = df.iloc[:-5].tail(VENTANA)
            if len(reciente2) < 10:
                return NULL
            pivote_alto = reciente2['high'].max()
            fecha_pivote = reciente2['high'].idxmax()

        tramo = df.loc[fecha_pivote:]
        if len(tramo) < 10:
            return NULL

        min_base = tramo['low'].min()
        profundidad = (pivote_alto - min_base) / pivote_alto * 100

        # Sin corrección ≥6% = papel vertical sin base (caso CVS)
        if profundidad < 6:
            return NULL

        cierre = float(df['close'].iloc[-1])

        # ¿Rompió hace más de ~3 semanas?
        ruedas_sobre_pivote = int((tramo['close'] > pivote_alto).sum())
        if ruedas_sobre_pivote > 15:
            idx_bo = tramo[tramo['close'] > pivote_alto].index[0]
            tramo = df.loc[fecha_pivote:idx_bo]

        semanas = len(tramo) / 5.0
        posicion = (cierre - min_base) / (pivote_alto - min_base) * 100
        posicion = min(posicion, 130.0)  # clamp

        # Volumen decreciente: último tercio vs primer tercio del tramo
        tercio = max(5, len(tramo) // 3)
        if 'volume' in df.columns:
            vol_ini = float(tramo['volume'].iloc[:tercio].mean())
            vol_fin = float(tramo['volume'].iloc[-tercio:].mean())
            voltrend = round(vol_fin / vol_ini, 2) if vol_ini > 0 else None
        else:
            voltrend = None

        return {
            'semanas':  round(semanas, 1),
            'prof':     round(profundidad, 1),
            'pos':      round(posicion, 1),
            'voltrend': voltrend,
            'minimo':       round(float(min_base), 2),
            'tramo_inicio': tramo.index[0],
        }
    except Exception as e:
        return NULL


def detectar_sacudon(hist, base, atr14_pct_valor):
    """Modificador de sacudon (shakeout) -- Warren Score v3.1.

    Antes de despegar, un papel que viene comprimiendo suele meter una
    sacudida violenta (barrida de stops / spring de Wyckoff) que el score
    castiga tres veces sin este modificador (compresion de corto, resta
    de verticalidad, resta de volatilidad sin direccion). Las 5
    condiciones deben cumplirse TODAS -- compresion previa valida es el
    prerrequisito absoluto; sin base no hay sacudon, es volatilidad comun.

    Devuelve tambien Vol Relativa / Vol 5d40d medidos en la ventana de 5
    ruedas ANTERIOR al inicio de la sacudida (reusando las funciones
    reales del pipeline, no reimplementadas) -- el frontend se queda con
    el mejor valor entre esa ventana y la de hoy, para que la sacudida no
    borre la compresion que el papel ya se habia ganado.
    """
    NULO = {'activo': False, 'ruedas': None, 'magnitud_atrs': None,
            'vol_relativa_pre': None, 'vol_5d40d_pre': None}
    try:
        # 1) Compresion previa valida (prerrequisito absoluto) -----------
        # El voltrend de detectar_base() mide el ultimo tercio del tramo
        # COMPLETO hasta hoy -- si hay una sacudida real, sus propias velas
        # de volumen altisimo caen justo en ese ultimo tercio y contaminan
        # el promedio, inflando voltrend por encima de 1.0 y auto-vetando
        # el propio caso que la condicion deberia admitir. Por eso el gate
        # de compresion se recalcula excluyendo la ventana reciente donde
        # se busca la sacudida (misma formula tercio/tercio que usa
        # detectar_base, aplicada sobre tramo_base_ref mas abajo).
        if base is None or base.get('semanas') is None or base['semanas'] < 4:
            return NULO
        # Posicion alta en la base: un spring de Wyckoff ocurre con el
        # papel pegado al techo de su rango, listo para romper -- es lo
        # que distingue una sacudida constructiva (MRVL: precio arriba del
        # rango, sacude, sale) de una venta comun en un papel golpeado que
        # viene de abajo (BP/CVX/EQNR veniendo de caidas, no de un techo).
        if base.get('pos') is None or base['pos'] < 60:
            return NULO
        if base.get('minimo') is None or base.get('tramo_inicio') is None:
            return NULO
        if atr14_pct_valor is None or atr14_pct_valor <= 0:
            return NULO

        close  = hist['Close'].values
        high   = hist['High'].values
        low    = hist['Low'].values
        volume = hist['Volume'].values
        n = len(hist)
        if n < 30:
            return NULO

        precio_actual = float(close[-1])
        atr_dolares = atr14_pct_valor / 100 * precio_actual
        if atr_dolares <= 0:
            return NULO

        VENTANA_RECIENTE = min(8, n - 1)

        # Tramo de referencia DE LA BASE -- mismo tramo que uso
        # detectar_base, pero excluyendo la ventana reciente (donde se
        # busca la sacudida) para no contaminar el calculo con la propia
        # vela que se esta evaluando.
        tramo_base = hist.loc[base['tramo_inicio']:]
        tramo_base_ref = tramo_base.iloc[:-VENTANA_RECIENTE] if len(tramo_base) > VENTANA_RECIENTE else tramo_base.iloc[:0]
        if len(tramo_base_ref) < 5:
            return NULO

        # Voltrend "pre-sacudida": mismo concepto que detectar_base (ultimo
        # tercio vs primer tercio del tramo, ya excluyendo la ventana
        # reciente via tramo_base_ref), pero con MEDIANA en vez de promedio.
        # Un solo dia de earnings dentro de la base (volumen 5x un dia
        # puntual) no deberia invalidar una compresion real -- el promedio
        # es sensible a ese outlier, la mediana es inmune por construccion.
        # El umbral sigue siendo 1.0 con el mismo significado ("el volumen
        # venia secandose"); lo que cambia es solo el estimador.
        tercio_ref = max(5, len(tramo_base_ref) // 3)
        vol_ini_ref = float(tramo_base_ref['Volume'].iloc[:tercio_ref].median())
        vol_fin_ref = float(tramo_base_ref['Volume'].iloc[-tercio_ref:].median())
        if vol_ini_ref <= 0:
            return NULO
        voltrend_pre = round(vol_fin_ref / vol_ini_ref, 2)
        if voltrend_pre > 1.0:
            return NULO

        if n < 20:
            return NULO
        vol_prom_20 = float(pd.Series(volume).tail(20).mean())
        if vol_prom_20 <= 0:
            return NULO

        # 2) Retroceso violento del ULTIMO TRAMO ALCISTA + 4) Volumen alto +
        # 5) Reciente -- no es un spring que perfora un piso historico: en
        # una base larga en pleno rally (ej. MRVL) el low de la sacudida
        # puede seguir por ENCIMA de minimos de solo 1-2 semanas antes, asi
        # que "perforar el piso" no aplica. Lo que si pasa es que se devuelve
        # de un saque una porcion grande de la ultima pata alcista dentro de
        # la base, y el papel aguanta -- eso es lo que se mide aca.
        #
        # Para cada candidato (vela o par) dentro de la ventana de escaneo:
        #   a) se ubica el ULTIMO MINIMO LOCAL CONFIRMADO (pivote con margen,
        #      no cualquier vela) y el maximo posterior a ese minimo -- eso
        #      define "el ultimo tramo alcista".
        #   b) ese tramo tiene que valer al menos 1.5 ATR en dolares -- un
        #      retroceso del 50% de un movimiento insignificante no es nada.
        #   c) el retroceso de la sacudida contra ese tramo tiene que ser
        #      >=50%.
        #   d) INNEGOCIABLE: el low del evento no puede perforar el minimo
        #      de la base -- si lo perfora, es ruptura real, no sacudon, sin
        #      importar cuan violento haya sido el movimiento.
        LOOKBACK_TRAMO = 30
        MARGEN_PIVOTE = 3
        idx_base_inicio = n - len(tramo_base)

        def _ultimo_tramo_alcista(idx_hasta):
            """Maximo reciente + ultimo minimo local confirmado antes de idx_hasta
            (ambos indices dentro de [idx_desde, idx_hasta)). None si no hay margen."""
            idx_desde = max(0, idx_hasta - LOOKBACK_TRAMO, idx_base_inicio)
            if idx_desde >= idx_hasta:
                return None
            pico_idx = idx_desde + int(np.argmax(high[idx_desde:idx_hasta]))
            minimo_local_idx = None
            for j in range(pico_idx - 1, idx_desde - 1, -1):
                lo = max(idx_desde, j - MARGEN_PIVOTE)
                hi = min(pico_idx, j + MARGEN_PIVOTE + 1)
                if low[j] <= low[lo:hi].min() + 1e-9:
                    minimo_local_idx = j
                    break
            if minimo_local_idx is None:
                minimo_local_idx = idx_desde
            tramo_dolares = float(high[pico_idx] - low[minimo_local_idx])
            return tramo_dolares, high[pico_idx]

        sacudida_idx = None   # dia de referencia para "ruedas desde" (el mas reciente del evento)
        idx_inicio    = None   # dia en que arranca el evento (para truncar las series "pre")
        magnitud_bruta = None
        for i in range(n - VENTANA_RECIENTE, n):
            if i < 1:
                continue

            # -- vela individual --
            low_evento_vela = low[i]
            if low_evento_vela > base['minimo']:  # (d) innegociable
                r = _ultimo_tramo_alcista(i)
                if r is not None:
                    tramo_dolares, pico_valor = r
                    if tramo_dolares >= 1.5 * atr_dolares:  # (b)
                        retroceso = (pico_valor - low_evento_vela) / tramo_dolares
                        vol_vela_ok = volume[i] >= 1.3 * vol_prom_20
                        if retroceso >= 0.5 and vol_vela_ok:  # (c) + volumen
                            sacudida_idx = i
                            idx_inicio = i
                            magnitud_bruta = max(high[i] - low[i], abs(low[i] - close[i - 1]))
                            break

            # -- par de 2 ruedas consecutivas --
            if i >= 2:
                low_evento_par = min(low[i - 1], low[i])
                if low_evento_par > base['minimo']:  # (d) innegociable
                    r = _ultimo_tramo_alcista(i - 1)
                    if r is not None:
                        tramo_dolares, pico_valor = r
                        if tramo_dolares >= 1.5 * atr_dolares:  # (b)
                            retroceso = (pico_valor - low_evento_par) / tramo_dolares
                            vol_par_ok = (volume[i - 1] + volume[i]) / 2 >= 1.3 * vol_prom_20
                            if retroceso >= 0.5 and vol_par_ok:  # (c) + volumen
                                sacudida_idx = i
                                idx_inicio = i - 1
                                magnitud_bruta = max(
                                    max(high[i - 1], high[i]) - low_evento_par,
                                    abs(low_evento_par - close[i - 2])
                                )
                                break

        if sacudida_idx is None:
            return NULO

        ruedas_desde = (n - 1) - sacudida_idx
        if ruedas_desde > 8:
            return NULO

        # 3) Recuperacion -- condicion critica, NO negociable. El cierre
        # de hoy tiene que estar en o por encima del minimo de la base;
        # si no, es ruptura bajista real, no sacudon.
        if close[-1] < base['minimo']:
            return NULO

        magnitud_atrs = round(magnitud_bruta / atr_dolares, 2)

        # Vol Relativa / Vol 5d40d en la ventana pre-sacudida -- se
        # truncan las series justo ANTES de que arranque el evento
        # (idx_inicio, no sacudida_idx, para no incluir la primera vela del
        # par en la ventana "pre") y se reusan las funciones reales
        # (calcular_volatilidad_relativa ya hace .tail(5)/.tail(252)
        # internamente).
        vol_relativa_pre = calcular_volatilidad_relativa(
            pd.Series(close[:idx_inicio]), pd.Series(high[:idx_inicio]), pd.Series(low[:idx_inicio])
        )
        vol_5d40d_pre = None
        if idx_inicio >= 40:
            v5  = pd.Series(volume[:idx_inicio]).tail(5).mean()
            v40 = pd.Series(volume[:idx_inicio]).tail(40).mean()
            if v40 > 0:
                vol_5d40d_pre = round(float(v5 / v40), 2)

        return {
            'activo': True, 'ruedas': ruedas_desde, 'magnitud_atrs': magnitud_atrs,
            'vol_relativa_pre': vol_relativa_pre, 'vol_5d40d_pre': vol_5d40d_pre,
        }
    except Exception:
        return NULO


def div_rsi(hist):
    """Divergencia bajista de RSI: precio hace máximos nuevos pero RSI no los confirma."""
    try:
        if hist is None or len(hist) < 20:
            return False
        close = hist['Close']
        delta = close.diff()
        # Wilder's Smoothing (RMA) -- igual a calcular_rsi() y a ta.rma de TradingView.
        # (antes usaba rolling().mean(), una SMA simple que da valores distintos)
        gain  = delta.clip(lower=0).ewm(alpha=1/14, min_periods=14, adjust=False).mean()
        loss  = (-delta.clip(upper=0)).ewm(alpha=1/14, min_periods=14, adjust=False).mean()
        rsi   = (100 - 100 / (1 + gain / loss.replace(0, np.nan))).values
        c     = close.values
        n     = min(40, len(c))
        cw, rw = c[-n:], rsi[-n:]
        # Pivotes confirmados: máximo local con ≥4 ruedas de margen a cada lado
        pivots = [i for i in range(4, n - 4)
                  if all(cw[i] >= cw[i-j] for j in range(1, 5))
                  and all(cw[i] >= cw[i+j] for j in range(1, 5))]
        if len(pivots) < 2:
            return False
        p1, p2 = pivots[-2], pivots[-1]
        if np.isnan(rw[p1]) or np.isnan(rw[p2]):
            return False
        if not bool(cw[p2] > cw[p1] and rw[p2] < rw[p1] - 3):
            return False

        # Anulación: si en las últimas 5 ruedas el precio ya superó el último
        # pivote confirmado y el RSI lo acompañó (no cayó ≥3 pts), el avance
        # reciente objeta la divergencia vieja aunque todavía no sea un
        # pivote "confirmado" (le faltan ruedas futuras para serlo)
        recientes     = cw[-5:]
        rsi_recientes = rw[-5:]
        idx_max       = int(np.argmax(recientes))
        max_reciente  = recientes[idx_max]
        rsi_en_max    = rsi_recientes[idx_max]
        if not np.isnan(rsi_en_max) and max_reciente > cw[p2] and rsi_en_max >= rw[p2] - 3:
            return False

        return True
    except:
        return False


def div_obv(hist, R=3, L=20):
    """'Suba sin combustible' (reemplaza la vieja divergencia de OBV de dos ventanas):
    el precio sigue haciendo maximos pegado al pico de las ultimas L ruedas, pero con
    velas mas chicas y volumen mas seco que el impulso que marco ese pico. Distingue
    agotamiento (sigue subiendo sin fuerza) de compresion sana (lateraliza/corrige)."""
    try:
        if hist is None or len(hist) < L + R + 2:
            return False
        c = hist['Close'].values
        h = hist['High'].values
        l = hist['Low'].values
        v = hist['Volume'].values
        n = len(hist)

        # pico = indice del dia de mayor volumen en las ultimas L ruedas (el impulso real,
        # no el maximo de High — asi no se corre dia a dia mientras el precio hace
        # maximos marginales con volumen decreciente)
        ini  = n - L
        pico = ini + int(np.argmax(v[ini:]))

        # si el pico es demasiado reciente, no hay "despues" que evaluar
        if pico > n - 1 - R:
            return False

        # 1) sigue arriba pero avanza poco (y no se derrumba)
        avance_reciente = (c[-1] - c[-1 - R]) / c[-1 - R] * 100
        cond1 = (c[-1] >= h[pico] * 0.97) and (-3.0 < avance_reciente < 3.5)

        # 2) velas mas chicas que en el impulso
        rango = h - l
        rango_reciente = rango[-R:].mean()
        rango_impulso  = rango[pico - R + 1: pico + 1].mean()
        cond2 = rango_impulso > 0 and (rango_reciente / rango_impulso) < 0.65

        # 3) volumen secandose respecto del impulso
        vol_reciente = v[-R:].mean()
        vol_impulso  = v[pico - R + 1: pico + 1].mean()
        cond3 = vol_impulso > 0 and (vol_reciente / vol_impulso) < 0.70

        return bool(cond1 and cond2 and cond3)
    except:
        return False


def churn_maximos(hist):
    """Churning en máximos: ≥3 días en las últimas 10 ruedas con cierre en mitad inferior y volumen ≥50% sobre el promedio de esas 10 ruedas."""
    try:
        if hist is None or len(hist) < 25:
            return False
        hi  = hist['High'].values
        lo  = hist['Low'].values
        c   = hist['Close'].values
        v   = hist['Volume'].values
        max_20 = hi[-20:].max()
        if max_20 <= 0 or (max_20 - c[-1]) / max_20 * 100 > 4:
            return False
        vol_avg = v[-10:].mean()
        if vol_avg <= 0:
            return False
        count = sum(
            1 for i in range(-10, 0)
            if (hi[i] - lo[i]) > 0
            and (c[i] - lo[i]) / (hi[i] - lo[i]) < 0.5
            and v[i] >= vol_avg * 1.5
        )
        return count >= 3
    except:
        return False


def _detectar_vcp_raw(hist, pivot_order=3):
    try:
        h = hist['High'].values
        l = hist['Low'].values
        c = hist['Close'].values
        v = hist['Volume'].values
        # Últimas 90 ruedas
        if len(c) > 90:
            h = h[-90:]; l = l[-90:]; c = c[-90:]; v = v[-90:]
        if len(c) < 30:
            return {'VCP Score': None, 'VCP Detected': False, 'VCP Contractions': 0,
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False,
                    'VCP Techo Toques': None, 'VCP Techo': None}

        def find_pivots(arr, order, mode):
            pivots = []
            for i in range(order, len(arr) - order):
                w = arr[i-order:i+order+1]
                if mode == 'H' and arr[i] >= max(w):
                    pivots.append((i, float(arr[i])))
                elif mode == 'L' and arr[i] <= min(w):
                    pivots.append((i, float(arr[i])))
            return pivots

        ph = find_pivots(h, pivot_order, 'H')
        pl = find_pivots(l, pivot_order, 'L')

        if not ph or not pl:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': 0,
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False,
                    'VCP Techo Toques': None, 'VCP Techo': None}

        all_piv = [(i, 'H', val) for i, val in ph] + [(i, 'L', val) for i, val in pl]
        all_piv.sort()

        # Cada máximo es candidato a inicio de su propia contracción: busca el
        # primer mínimo siguiente, salteando máximos MENORES en el camino; si
        # aparece un máximo MAYOR antes de encontrar el mínimo, este máximo
        # queda superado por ese techo más alto y no arranca contracción.
        # (el emparejamiento secuencial anterior saltaba el índice hasta el
        # mínimo encontrado, dejando "huérfanos" a los máximos intermedios —
        # nunca se evaluaban como inicio de su propia contracción)
        candidatos = []
        for k in range(len(all_piv)):
            if all_piv[k][1] != 'H':
                continue
            hi, _, hval = all_piv[k]
            li = lval = None
            for j in range(k + 1, len(all_piv)):
                jidx, jkind, jval = all_piv[j]
                if jkind == 'H':
                    if jval > hval:
                        li = None
                        break
                    continue
                li, lval = jidx, jval
                break
            if li is not None and hval > lval:
                seg_vol = float(np.mean(v[hi:li+1])) if li > hi else float(v[hi])
                candidatos.append({'hi_idx': hi, 'li_idx': li, 'high': hval, 'low': lval,
                                    'pct': (hval - lval) / hval * 100, 'avg_vol': seg_vol})

        # Si dos candidatos terminan en el mismo mínimo (un máximo menor
        # "saltado" también llega al mismo mínimo), se queda el que arranca
        # en el máximo más alto — es el techo relevante.
        por_low = {}
        for ct in candidatos:
            actual = por_low.get(ct['li_idx'])
            if actual is None or ct['high'] > actual['high']:
                por_low[ct['li_idx']] = ct
        contractions = sorted(por_low.values(), key=lambda ct: ct['hi_idx'])

        if len(contractions) < 2:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': len(contractions),
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False,
                    'VCP Techo Toques': None, 'VCP Techo': None}

        # El techo es el nivel más TESTEADO (más toques), no el más reciente ni
        # el más alto -- pero tiene que ser una resistencia a ROMPER: al nivel
        # del precio actual o por encima (2% de margen para el caso "recién
        # roto"), y vigente (no más de 30% arriba, para no elegir un máximo
        # viejo e irrelevante de cuando el papel cotizaba a otro precio).
        # Tolerancia de toques adaptada al ATR: un % fijo es demasiado
        # apretado para un papel volátil y demasiado laxo para uno tranquilo.
        atr_hist  = atr14_pct(hist)
        TOL_TOQUE = max(0.02, 0.008 * atr_hist) if atr_hist else 0.025
        niveles   = [val for _, val in ph]

        def _contar_toques(nivel):
            return sum(1 for v in niveles if abs(v - nivel) / nivel <= TOL_TOQUE)

        precio_actual = float(c[-1])
        # Elegibilidad del techo evaluada contra el MENOR precio de hoy/ayer
        # (no solo hoy): un breakout con gap fuerte (>~2%) empuja precio_actual
        # bien por encima del techo real y lo deja afuera de la tolerancia el
        # mismo dia que deberia confirmarse -- justo cuando mas importa (caso
        # NVDA 8/1/2024: VCP Score 100 -> 0 en la rueda del breakout). Usar
        # tambien el cierre de ayer (pre-gap) le da al techo un dia de gracia
        # sin tocar el resto de la logica (dist_pivot sigue midiendose contra
        # precio_actual, sin cambios).
        precio_ref    = min(precio_actual, float(c[-2])) if len(c) >= 2 else precio_actual
        rango_valido  = [(idx_h, val_h) for idx_h, val_h in ph
                         if precio_ref * 0.98 <= val_h <= precio_actual * 1.30]
        candidatos_techo = [(idx_h, val_h, _contar_toques(val_h)) for idx_h, val_h in rango_valido]
        con_toques = [ct for ct in candidatos_techo if ct[2] >= 2]

        if con_toques:
            max_toques = max(ct[2] for ct in con_toques)
            mejores    = [ct for ct in con_toques if ct[2] == max_toques]
            techo_idx, techo, techo_toques = min(mejores, key=lambda ct: ct[1])
        elif candidatos_techo:
            # Ningún nivel junta 2 toques: una resistencia de un solo toque es
            # débil, pero no es ausencia de patrón -- el score sigue su curso
            # normal, el componente de calidad de resistencia no suma puntos.
            techo_idx, techo, techo_toques = max(candidatos_techo, key=lambda ct: ct[1])
        else:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': len(contractions),
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False,
                    'VCP Techo Toques': 0, 'VCP Techo': None}

        # Delimitar la base: ancla en la ÚLTIMA CONTRACCIÓN real (no en el
        # techo elegido por toques -- ese puede ser un máximo antiguo sin
        # contracción propia asociada dentro de la ventana, lo que dejaría la
        # lista vacía si el precio lo tocó apenas de pasada más tarde).
        # Camina hacia atrás desde ahí mientras el precio no supere el
        # máximo de esa última contracción (con el mismo margen de tolerancia
        # ATR-adaptado que el techo, TOL_TOQUE) ni caiga más de ~37% respecto
        # de él. Descarta contracciones previas al inicio de la base
        # (arrastradas por la ventana de 90 ruedas pero ajenas al patrón) y
        # las que sean ruido relativo al rango de esa base (<20% del rango).
        #
        # El margen de tolerancia importa: sin él, la contracción PENÚLTIMA
        # de un VCP legítimo casi siempre queda excluida en cuanto se agrega
        # una barra nueva -- por diseño, cada contracción tiene un máximo un
        # poco más alto que la siguiente (eso ES la contracción), así que
        # "no superar el máximo de la última" se dispara con la contracción
        # vecina de inmediato y la base entera pierde el ancla (caso NVDA
        # 8/1/2024: al confirmarse una contracción nueva al cierre del gap,
        # la contracción previa -apenas 0.9% más alta- quedaba afuera y
        # `contractions` caía de 2 a 1, tirando el score a 0 justo el día
        # del breakout).
        MAX_CAIDA_BASE = 0.37
        base_idx  = contractions[-1]['hi_idx']
        base_high = contractions[-1]['high']
        inicio_base = 0
        for k in range(base_idx - 1, -1, -1):
            if c[k] > base_high * (1 + TOL_TOQUE) or c[k] < base_high * (1 - MAX_CAIDA_BASE):
                inicio_base = k + 1
                break

        contractions = [ct for ct in contractions if ct['hi_idx'] >= inicio_base]
        if len(contractions) < 2:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': len(contractions),
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False,
                    'VCP Techo Toques': techo_toques, 'VCP Techo': round(techo, 2)}

        rango_base_abs = base_high - float(np.min(l[inicio_base:base_idx + 1]))
        if rango_base_abs > 0:
            contractions = [ct for ct in contractions
                             if (ct['high'] - ct['low']) / rango_base_abs >= 0.20]
        if len(contractions) < 2:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': len(contractions),
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False,
                    'VCP Techo Toques': techo_toques, 'VCP Techo': round(techo, 2)}

        pcts = [ct['pct'] for ct in contractions]
        vols = [ct['avg_vol'] for ct in contractions]
        n_c  = len(contractions)
        pairs = n_c - 1

        pct_dec = sum(1 for k in range(pairs) if pcts[k] > pcts[k+1]) / pairs
        vol_dec = sum(1 for k in range(pairs) if vols[k] > vols[k+1]) / pairs

        last_pct   = pcts[-1]
        dist_pivot = (float(c[-1]) - techo) / techo * 100

        score = 0
        score += round(pct_dec * 35)
        score += round(vol_dec * 20)
        if last_pct <= 5:    score += 20
        elif last_pct <= 10: score += 15
        elif last_pct <= 15: score += 10
        elif last_pct <= 20: score += 5
        if   -3  <= dist_pivot <= 1:   score += 15
        elif -5  <= dist_pivot < -3:   score += 12
        elif -8  <= dist_pivot < -5:   score += 8
        elif -15 <= dist_pivot < -8:   score += 4
        if n_c >= 4:   score += 10
        elif n_c == 3: score += 7
        elif n_c == 2: score += 4
        # Calidad de la resistencia: cuantos mas toques valido el techo, mas
        # significativa es la ruptura.
        if   techo_toques >= 5: score += 12
        elif techo_toques == 4: score += 10
        elif techo_toques == 3: score += 8
        elif techo_toques == 2: score += 5
        score = min(100, score)

        return {
            'VCP Score':          score,
            'VCP Detected':       score >= 55,
            'VCP Contractions':   n_c,
            'VCP Tightness':      round(last_pct, 2),
            'VCP Dist Pivot %':   round(dist_pivot, 2),
            'VCP Vol Decreasing': vol_dec >= 0.5,
            'VCP Techo Toques':   techo_toques,
            'VCP Techo':          round(techo, 2),
        }
    except:
        return {'VCP Score': None, 'VCP Detected': False, 'VCP Contractions': 0,
                'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False,
                'VCP Techo Toques': None, 'VCP Techo': None}


def detectar_vcp(hist, pivot_order=3, hyst_dias=2, ventana_hyst=6):
    """Envoltorio con histeresis sobre 'VCP Detected': exige `hyst_dias`
    sesiones consecutivas por encima (o por debajo) del umbral 55 antes de
    prender (o apagar) la deteccion. El recalculo de pivotes dia a dia hace
    que VCP Score oscile +-6/7 pts sin que la base cambie de verdad -- eso
    hacia parpadear 'VCP Detected' 13-17 veces durante una base legitima
    (casos NVDA/MRVL). El resto de los campos (Score, Tightness, Dist Pivot,
    etc.) se devuelven crudos, sin suavizar -- solo el booleano 'Detected'
    tiene memoria de corto plazo."""
    actual = _detectar_vcp_raw(hist, pivot_order)
    if actual['VCP Score'] is None:
        return actual
    n = len(hist)
    ventana = min(ventana_hyst, n - 30)
    if ventana < hyst_dias:
        return actual
    detected = False
    streak_on = streak_off = 0
    for k in range(ventana, -1, -1):
        idx_hasta = n - k
        if idx_hasta < 30:
            continue
        raw = _detectar_vcp_raw(hist.iloc[:idx_hasta], pivot_order)
        s = raw['VCP Score'] or 0
        if s >= 55:
            streak_on += 1; streak_off = 0
        else:
            streak_off += 1; streak_on = 0
        if streak_on  >= hyst_dias: detected = True
        if streak_off >= hyst_dias: detected = False
    actual = dict(actual)
    actual['VCP Detected'] = detected
    return actual

def calcular_sesiones_10(close, volume):
    """
    Últimas 10 sesiones: días positivos/negativos y volumen acumulado por tipo.
    Un día es positivo si cierre > cierre anterior.
    """
    if len(close) < 11 or len(volume) < 10:
        return None, None, None, None
    precios = close.tail(11).values
    vols    = volume.tail(10).values
    dias_pos, dias_neg = 0, 0
    vol_pos,  vol_neg  = 0.0, 0.0
    for i in range(10):
        cambio = precios[i + 1] - precios[i]
        v      = float(vols[i])
        if cambio > 0:
            dias_pos += 1
            vol_pos  += v
        elif cambio < 0:
            dias_neg += 1
            vol_neg  += v
    return dias_pos, dias_neg, round(vol_pos), round(vol_neg)

def clasificar_market_cap(mc):
    if mc is None:     return "—"
    if mc >= 200e9:    return "Mega Cap"
    if mc >= 10e9:     return "Large Cap"
    if mc >= 2e9:      return "Mid Cap"
    if mc >= 300e6:    return "Small Cap"
    return "Micro Cap"

def obtener_info_ticker(ticker_symbol):
    try:
        info   = yf.Ticker(ticker_symbol).info
        mc     = info.get('marketCap', None)
        sector = info.get('sector', None)
        es_etf = info.get('quoteType', '') in ['ETF', 'MUTUALFUND']
        if es_etf and not sector:
            sector = "ETF"
        if not sector:
            sector = info.get('category', '—') or '—'
        return {
            "Market Cap USD": mc,
            "Market Cap Cat": clasificar_market_cap(mc),
            "Sector":         sector or "—",
            "Tipo":           "ETF" if es_etf else "Acción"
        }
    except:
        return {"Market Cap USD": None, "Market Cap Cat": "—", "Sector": "—", "Tipo": "—"}

def detectar_breakout(hist, vcp_techo=None, lookback=20, vol_factor=1.5, frescura=3):
    """
    3 capas de confirmación del breakout (Minervini):
    1. Precio cruzó el máximo de las últimas `lookback` velas hace ≤ `frescura` días
    2. El volumen ese día fue ≥ `vol_factor` veces el promedio de 50 ruedas
    3. (extensión: Dist SMA50 % — se calcula aparte y se evalúa en el frontend)

    `vcp_techo`: techo de la base detectada por detectar_vcp() (o None). Cuando
    existe y es MAS ALTO que el máximo de `lookback` velas, el pivote real de
    la base es el techo, no el máximo corto -- de lo contrario 'Breakout Fresh'
    puede prenderse con el precio todavía por debajo del verdadero techo de la
    base (visto en MRVL/SNDK: Breakout Fresh=True con VCP Dist Pivot % todavía
    negativo, dos pivotes que no coincidian).
    """
    try:
        c = hist['Close'].values
        v = hist['Volume'].values
        if len(c) < lookback + 2:
            return {'Breakout Fresh': False, 'Breakout Days Ago': None,
                    'Breakout Vol OK': False, 'Breakout Vol Ratio': None, 'Pivot': None}

        vol50 = float(np.mean(v[-51:-1])) if len(v) >= 51 else float(np.mean(v[:-1]))

        breakout_day = None
        vol_ratio    = None
        pivot_val    = None

        for ago in range(frescura + 1):
            idx = len(c) - 1 - ago
            if idx < lookback + 1:
                break
            pivot = float(np.max(c[idx - lookback:idx]))
            if vcp_techo and vcp_techo > pivot:
                pivot = float(vcp_techo)
            if float(c[idx]) > pivot and float(c[idx - 1]) <= pivot:
                vr = float(v[idx]) / vol50 if vol50 > 0 else None
                breakout_day = ago
                vol_ratio    = round(vr, 2) if vr is not None else None
                pivot_val    = round(pivot, 2)
                break

        vol_ok = vol_ratio is not None and vol_ratio >= vol_factor
        return {
            'Breakout Fresh':     breakout_day is not None,
            'Breakout Days Ago':  breakout_day,
            'Breakout Vol OK':    vol_ok,
            'Breakout Vol Ratio': vol_ratio,
            'Pivot':              pivot_val,
        }
    except:
        return {'Breakout Fresh': False, 'Breakout Days Ago': None,
                'Breakout Vol OK': False, 'Breakout Vol Ratio': None, 'Pivot': None}


# ── Feedback de breakouts (Capa 3 del Regimen de Mercado) ────────────
# Reemplaza el viejo track record client-side (localStorage, sesgado a
# quien haya abierto el dashboard) por un calculo objetivo sobre todo el
# universo, persistido entre corridas en breakouts_log.json.
FEEDBACK_VENTANA    = 5     # ruedas de gracia tras el breakout
FEEDBACK_COLCHON    = 0.025 # 2.5% bajo el pivote = fallo
FEEDBACK_MIN_MUESTRA = 5    # evaluables minimos para que la capa puntue
FEEDBACK_POBLACION_DIAS = 28  # ventana (calendario) ~20 ruedas para la tasa
FEEDBACK_PRUNE_DIAS  = 35   # se descartan entradas mas viejas que esto

def _procesar_breakout_log(breakouts_log, ticker, hist, brk, hoy_str):
    """Resuelve (si ya maduraron 5 ruedas) las entradas pendientes de este
    ticker, y agrega una entrada nueva si hoy detecto un Breakout Fresh."""
    try:
        fechas_str = [d.strftime('%Y-%m-%d') for d in hist.index]
        closes     = hist['Close'].values

        for entry in breakouts_log:
            if entry['ticker'] != ticker or entry.get('resultado'):
                continue
            try:
                pos = fechas_str.index(entry['fecha_ruptura'])
            except ValueError:
                continue
            ventana = closes[pos + 1: pos + 1 + FEEDBACK_VENTANA]
            if len(ventana) < FEEDBACK_VENTANA:
                continue  # todavia no tiene sus 5 ruedas de gracia completas
            nivel_falla = entry['pivote'] * (1 - FEEDBACK_COLCHON)
            entry['resultado'] = 'fallo' if any(float(cl) < nivel_falla for cl in ventana) else 'sobrevivio'

        if brk.get('Breakout Fresh') and brk.get('Breakout Days Ago') == 0 and brk.get('Pivot'):
            ya_logueado = any(e['ticker'] == ticker and e['fecha_ruptura'] == hoy_str for e in breakouts_log)
            if not ya_logueado:
                breakouts_log.append({
                    'ticker':        ticker,
                    'fecha_ruptura': hoy_str,
                    'pivote':        brk['Pivot'],
                    'resultado':     None,
                })
    except Exception as e:
        print(f"    ⚠️ Error procesando breakout log de {ticker}: {e}")


def calcular_feedback_breakouts(breakouts_log):
    """tasa de supervivencia (0-1) y tamaño de muestra sobre la poblacion
    evaluable reciente. Devuelve (None, n) si la muestra es insuficiente."""
    from datetime import datetime as _dt
    hoy_dt = _dt.now()
    poblacion = [
        e for e in breakouts_log
        if e.get('resultado') and (hoy_dt - _dt.strptime(e['fecha_ruptura'], '%Y-%m-%d')).days <= FEEDBACK_POBLACION_DIAS
    ]
    n = len(poblacion)
    if n < FEEDBACK_MIN_MUESTRA:
        return None, n
    sobrevivieron = sum(1 for e in poblacion if e['resultado'] == 'sobrevivio')
    return round(sobrevivieron / n, 3), n


def calcular_kpis(ticker_symbol, hist_spy, breakouts_log, hoy_str):
    try:
        tk   = yf.Ticker(ticker_symbol)
        hist = tk.history(period="2y")
        if hist.empty or len(hist) < 60:
            return None

        close  = hist["Close"]
        high   = hist["High"]
        low    = hist["Low"]
        volume = hist["Volume"]
        precio_actual = round(close.iloc[-1], 2)

        # Medias móviles
        ema200_series = close.ewm(span=200, adjust=False).mean()
        ema200        = round(ema200_series.iloc[-1], 2)
        ema200_ref    = ema200_series.iloc[-10] if len(ema200_series) >= 10 else ema200_series.iloc[0]
        ema200_slope  = round(ema200 - float(ema200_ref), 4)
        sma50_series  = close.rolling(window=50).mean()
        sma50         = round(sma50_series.iloc[-1], 2)
        sma50_ref     = sma50_series.iloc[-10] if len(sma50_series.dropna()) >= 10 else sma50_series.dropna().iloc[0]
        sma50_slope   = round(sma50 - float(sma50_ref), 4)
        dist_ema200   = round((precio_actual - ema200) / ema200 * 100, 2)
        dist_sma50    = round((precio_actual - sma50)  / sma50  * 100, 2)

        # Máximo y mínimo 52 semanas
        max_52w    = round(close.tail(252).max(), 2)
        dist_max52 = round((precio_actual - max_52w) / max_52w * 100, 2)
        min_52w    = round(close.tail(252).min(), 2)
        dist_min52 = round((precio_actual - min_52w) / min_52w * 100, 2)

        # Variación del día
        var_dia = round((close.iloc[-1] - close.iloc[-2]) / close.iloc[-2] * 100, 2)

        # Avance Pico 15r % — verticalidad reciente, medida contra el pico (Warren Score v2.3)
        avance_pico15r = avance_pico_15r(hist)

        # RSI, Vol Relativa, Volumen inusual
        rsi     = calcular_rsi(close)
        vol_rel = calcular_volatilidad_relativa(close, high, low)
        vol_inu = calcular_volumen_inusual(volume, 20)

        # Sesiones 10 ruedas
        dias_pos_10, dias_neg_10, vol_pos_10, vol_neg_10 = calcular_sesiones_10(close, volume)

        # Vol 5d/40d: ratio volumen promedio últimas 5 ruedas vs últimas 40
        vol_5d_40d = None
        if len(volume) >= 40:
            v5  = volume.tail(5).mean()
            v40 = volume.tail(40).mean()
            if v40 > 0:
                vol_5d_40d = round(v5 / v40, 2)

        # RS Score
        score_actual, score_ayer, score_semana, score_mes, sobre_sma, \
        fr_hoy, fr_ayer, fr_semana, fr_mes = calcular_rs_score(
            close, hist_spy["Close"]
        )

        # VCP
        vcp = detectar_vcp(hist)

        # Base estructural (Warren Score v2 Pilar D)
        base = detectar_base(hist)

        # ATR14 % y Volatilidad Anual % (Warren Score v2.1)
        atr14_p    = atr14_pct(hist)
        vol_anual  = vol_anual_pct(hist)

        # Modificador de sacudon / shakeout (Warren Score v3.1)
        sacudon = detectar_sacudon(hist, base, atr14_p)

        # Choppiness + Eficiencia — volatilidad sin dirección (Warren Score v2.3)
        chop = choppiness_eficiencia(hist)

        # Regreso a la EMA200: visita rara a la media de largo plazo
        atr14_ser = _atr14_series(hist)
        visita = visita_ema200(close.values, ema200_series.values, atr14_ser.values) if atr14_ser is not None else None

        # EMA200 Reversal Score: clímax de volumen + repunte de RS en el contacto
        rs_ser_completa = rs_score_series(close, hist_spy["Close"])
        reversal = ema200_reversal_features(hist, ema200_series, rs_ser_completa)

        # Señales de agotamiento del avance (Warren Score v2.2)
        div_rsi_v  = div_rsi(hist)
        div_obv_v  = div_obv(hist)
        churn_v    = churn_maximos(hist)

        # Breakout fresco (el techo del VCP, si hay uno vigente, pisa el
        # pivote de 20 ruedas cuando es mas alto -- ver detectar_breakout)
        brk = detectar_breakout(hist, vcp_techo=vcp.get('VCP Techo'))
        _procesar_breakout_log(breakouts_log, ticker_symbol, hist, brk, hoy_str)

        return {
            "Ticker":          ticker_symbol,
            "Precio":          precio_actual,
            "Var Día %":       var_dia,
            "Avance Pico 15r %": avance_pico15r,
            "EMA200":          ema200,
            "EMA200 Slope":    ema200_slope,
            "Dist EMA200 %":   dist_ema200,
            "SMA50":           sma50,
            "SMA50 Slope":     sma50_slope,
            "Dist SMA50 %":    dist_sma50,
            "Máx 52W":         max_52w,
            "Dist Máx52W %":   dist_max52,
            "Mín 52W":         min_52w,
            "Dist Mín52W %":   dist_min52,
            "RSI 14":          rsi,
            "Vol Relativa":    vol_rel,
            "Vol Inusual %":   vol_inu,
            "RS Score":        score_actual,
            "RS Ayer":         score_ayer,
            "RS Semana ant.":  score_semana,
            "RS Mes ant.":     score_mes,
            "FR > SMA50":          sobre_sma,
            "FR Hoy":              fr_hoy,
            "FR Ayer":             fr_ayer,
            "FR Semana ant.":      fr_semana,
            "FR Mes ant.":         fr_mes,
            "VCP Score":           vcp['VCP Score'],
            "VCP Detected":        vcp['VCP Detected'],
            "VCP Contractions":    vcp['VCP Contractions'],
            "VCP Tightness":       vcp['VCP Tightness'],
            "VCP Dist Pivot %":    vcp['VCP Dist Pivot %'],
            "VCP Vol Decreasing":  vcp['VCP Vol Decreasing'],
            "VCP Techo Toques":    vcp['VCP Techo Toques'],
            "VCP Techo":           vcp.get('VCP Techo'),
            "Días + 10s":          dias_pos_10,
            "Días - 10s":          dias_neg_10,
            "Vol días + 10s":      vol_pos_10,
            "Vol días - 10s":      vol_neg_10,
            "Vol 5d/40d":              vol_5d_40d,
            "Breakout Fresh":          brk['Breakout Fresh'],
            "Breakout Days Ago":       brk['Breakout Days Ago'],
            "Breakout Vol OK":         brk['Breakout Vol OK'],
            "Breakout Vol Ratio":      brk['Breakout Vol Ratio'],
            "Breakout Pivot":          brk['Pivot'],
            "Base Semanas":            base['semanas'],
            "Base Profundidad %":      base['prof'],
            "Base Posición %":         base['pos'],
            "Base Vol Trend":          base['voltrend'],
            "Sacudon Activo":          sacudon['activo'],
            "Sacudon Ruedas":          sacudon['ruedas'],
            "Sacudon Magnitud ATRs":   sacudon['magnitud_atrs'],
            "Sacudon Vol Relativa Pre": sacudon['vol_relativa_pre'],
            "Sacudon Vol 5d40d Pre":   sacudon['vol_5d40d_pre'],
            "ATR14 %":                 atr14_p,
            "Volatilidad Anual %":     vol_anual,
            "Choppiness":              chop['Choppiness'],
            "Eficiencia 10d":          chop['Eficiencia 10d'],
            "Div RSI":                 div_rsi_v,
            "Div OBV":                 div_obv_v,
            "Churn Máximos":           churn_v,
            "EMA200 Visita":           visita['visita']    if visita else False,
            "EMA200 Racha Previa":     reversal['racha_previa'] if reversal else None,
            "EMA200 Freq %":           visita['freq']      if visita else None,
            "EMA200 Dist ATRs":        visita['dist_atrs'] if visita else None,
            "EMA200 Contacto Ruedas":  reversal['contacto_ruedas']     if reversal else None,
            "EMA200 Dist Hace20 %":    reversal['dist_hace20']         if reversal else None,
            "Climax Vol Ratio":        reversal['climax_vol_ratio']    if reversal else None,
            "Climax Pos Cierre":       reversal['climax_pos_cierre']   if reversal else None,
            "RS En Contacto":          reversal['rs_en_contacto']      if reversal else None,
            "Precio Sobre Climax":     reversal['precio_sobre_climax'] if reversal else False,
        }
    except Exception as e:
        print(f"  ⚠️ Error con {ticker_symbol}: {e}")
        return None

def calcular_regimen(hist_spy, hist_qqq):
    """
    Calcula los scores de régimen de mercado para SPY y QQQ.
    Devuelve un dict compatible con el contrato del frontend (V3 REGIMEN_DATA).
    """
    def analizar_indice(hist):
        c = hist['Close'].squeeze()
        v = hist['Volume'].squeeze()
        h = hist['High'].squeeze()
        l = hist['Low'].squeeze()
        ema50  = c.ewm(span=50,  adjust=False).mean()
        ema200 = c.ewm(span=200, adjust=False).mean()

        # Tendencia (10 pts)
        tend = 0
        if float(c.iloc[-1]) > float(ema50.iloc[-1]):  tend += 4
        if float(c.iloc[-1]) > float(ema200.iloc[-1]): tend += 4
        if len(ema200) >= 21 and float(ema200.iloc[-1]) > float(ema200.iloc[-21]): tend += 2

        # Días de distribución en las últimas 25 ruedas (con expiración +5%)
        ret  = c.pct_change()
        dist = 0
        for i in range(-25, 0):
            try:
                ci = float(c.iloc[i]); ci_prev = float(c.iloc[i-1])
                vi = float(v.iloc[i]); vi_prev = float(v.iloc[i-1])
                hi = float(h.iloc[i]); li = float(l.iloc[i])
                ri = float(ret.iloc[i]) if not pd.isna(ret.iloc[i]) else 0
                cae   = ri <= -0.002
                stall = (0 <= ri < 0.001) and (ci < (hi + li) / 2)
                mas_vol   = vi > vi_prev
                expirado  = float(c.iloc[-1]) >= ci * 1.05
                if (cae or stall) and mas_vol and not expirado:
                    dist += 1
            except:
                pass
        dist_score = max(0, 10 - max(0, dist - 1) * 2)

        # Follow-through / estado del rally (5 pts)
        if float(c.iloc[-1]) > float(ema50.iloc[-1]):
            ftd = 5
        else:
            max_60    = float(c.rolling(60).max().iloc[-1])
            correccion = float(c.iloc[-1]) < max_60 * 0.94
            ret_vals   = ret.values; v_vals = v.values
            hubo_ftd   = any(
                (not pd.isna(ret_vals[i]) and float(ret_vals[i]) >= 0.015
                 and float(v_vals[i]) > float(v_vals[i-1]))
                for i in range(max(-15, -len(ret_vals)), 0)
            )
            ftd = 4 if (correccion and hubo_ftd) else (2 if correccion else 0)

        return int(tend), int(dist), int(dist_score), int(ftd)

    try:
        spy_tend, spy_dist_days, spy_dist_score, spy_ftd = analizar_indice(hist_spy)
        qqq_tend, qqq_dist_days, qqq_dist_score, qqq_ftd = analizar_indice(hist_qqq)
    except Exception as e:
        print(f"  ⚠️  Error analizando índices: {e}")
        return None

    vix = None
    try:
        vix_hist = yf.Ticker('^VIX').history(period='1mo')
        if not vix_hist.empty:
            closes = vix_hist['Close'].dropna()
            if not closes.empty:
                vix = round(float(closes.iloc[-1]), 2)
                print(f"    VIX obtenido: {vix}")
            else:
                print("    ⚠️ VIX: columna Close vacía")
        else:
            print("    ⚠️ VIX: historia vacía")
    except Exception as e:
        print(f"  ⚠️  VIX no disponible: {e}")

    putcall_5d = None
    for pc_ticker in ['^CPCE', '^CPC']:
        try:
            pc_hist = yf.Ticker(pc_ticker).history(period='1mo')
            if not pc_hist.empty:
                closes = pc_hist['Close'].dropna()
                if not closes.empty:
                    putcall_5d = round(float(closes.tail(5).mean() if len(closes) >= 5 else closes.iloc[-1]), 3)
                    print(f"    P/C ratio obtenido de {pc_ticker}: {putcall_5d}")
                    break
                else:
                    print(f"    ⚠️ {pc_ticker}: columna Close vacía")
            else:
                print(f"    ⚠️ {pc_ticker}: historia vacía")
        except Exception as e:
            print(f"  ⚠️  P/C ({pc_ticker}) no disponible: {e}")

    return {
        "fecha":          datetime.now().strftime('%Y-%m-%d'),
        "spy_tendencia":  spy_tend,
        "spy_dist_days":  spy_dist_days,
        "spy_dist_score": spy_dist_score,
        "spy_ftd_score":  spy_ftd,
        "qqq_tendencia":  qqq_tend,
        "qqq_dist_days":  qqq_dist_days,
        "qqq_dist_score": qqq_dist_score,
        "qqq_ftd_score":  qqq_ftd,
        "vix":            vix,
        "putcall_5d":     putcall_5d,
    }


# ── DESCARGA SPY ──────────────────────────────────────────────
print("⏳ Descargando SPY como referencia...")
hist_spy = yf.Ticker("SPY").history(period="2y")

print("⏳ Descargando QQQ para régimen de mercado...")
hist_qqq = yf.Ticker("QQQ").history(period="2y")

print("⏳ Calculando régimen de mercado (SPY/QQQ + VIX + P/C)...")
regimen_data = calcular_regimen(hist_spy, hist_qqq)
if regimen_data:
    spy_pts = regimen_data['spy_tendencia'] + regimen_data['spy_dist_score'] + regimen_data['spy_ftd_score']
    qqq_pts = regimen_data['qqq_tendencia'] + regimen_data['qqq_dist_score'] + regimen_data['qqq_ftd_score']
    print(f"  ✅ SPY {spy_pts}/25 pts | QQQ {qqq_pts}/25 pts | VIX {regimen_data['vix']} | P/C {regimen_data['putcall_5d']}")
else:
    print("  ⚠️  Régimen no disponible, las capas 1 y 4 quedarán inactivas")

# ── CREDENCIALES GITHUB (se necesitan antes del loop para leer breakouts_log.json) ──
import json, base64, requests, os
from datetime import datetime

GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"
gh_headers   = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}

# ── CARGAR BREAKOUTS_LOG.JSON (feedback de breakouts, Capa 3 del regimen) ──
BREAKOUTS_LOG_FILE = "breakouts_log.json"
breakouts_log = []
try:
    resp_bl = requests.get(
        f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{BREAKOUTS_LOG_FILE}",
        headers=gh_headers,
    )
    if resp_bl.status_code == 200:
        breakouts_log = json.loads(base64.b64decode(resp_bl.json()["content"]).decode("utf-8"))
        print(f"  ✅ breakouts_log.json cargado: {len(breakouts_log)} entradas")
    else:
        print("  ℹ️  breakouts_log.json no existe todavía, arranca vacío")
except Exception as e:
    print(f"  ⚠️  Error cargando breakouts_log.json: {e}")

hoy_str = datetime.now().strftime('%Y-%m-%d')

# ── LOOP PRINCIPAL ────────────────────────────────────────────
print("⏳ Calculando KPIs + Market Cap + Sector + Volumen...")
todos_los_datos = []
tickers_procesados = set()

for grupo, tickers in TICKERS.items():
    print(f"\n📂 {grupo}")
    for ticker in list(dict.fromkeys(tickers)):
        if ticker in tickers_procesados:
            continue
        tickers_procesados.add(ticker)
        print(f"  → {ticker}")

        datos = calcular_kpis(ticker, hist_spy, breakouts_log, hoy_str)
        if not datos:
            continue

        datos["Grupo"] = grupo

        info = obtener_info_ticker(ticker)
        datos.update(info)

        sector_etf = ETF_SECTOR.get(ticker, None)
        if sector_etf:
            try:
                t  = yf.Ticker(ticker).history(period="3mo")["Close"]
                s  = yf.Ticker(sector_etf).history(period="3mo")["Close"]
                vs = round(((t.iloc[-1]/t.iloc[0]) / (s.iloc[-1]/s.iloc[0]) - 1) * 100, 2)
                datos["Vs Sector %"] = vs
                datos["ETF Sector"]  = sector_etf
            except:
                datos["Vs Sector %"] = None
                datos["ETF Sector"]  = None
        else:
            datos["Vs Sector %"] = None
            datos["ETF Sector"]  = None

        todos_los_datos.append(datos)

df = pd.DataFrame(todos_los_datos)
print(f"\n✅ Datos listos: {len(df)} tickers")
print(df[["Ticker", "Dist Mín52W %", "Vol Relativa", "RS Score", "Sector", "Market Cap Cat"]].head(10).to_string(index=False))

# ── PRUNE + FEEDBACK DE BREAKOUTS (Capa 3 del regimen) ────────
breakouts_log = [
    e for e in breakouts_log
    if (datetime.now() - datetime.strptime(e['fecha_ruptura'], '%Y-%m-%d')).days <= FEEDBACK_PRUNE_DIAS
]
feedback_tasa, feedback_n = calcular_feedback_breakouts(breakouts_log)
if regimen_data:
    regimen_data['feedback_tasa'] = feedback_tasa
    regimen_data['feedback_n']    = feedback_n
if feedback_tasa is not None:
    print(f"  ✅ Feedback breakouts: {feedback_tasa*100:.0f}% supervivencia sobre {feedback_n} evaluables")
else:
    print(f"  ℹ️  Feedback breakouts: muestra insuficiente ({feedback_n} evaluables)")

# ── EXPORTAR A GITHUB ──────────────────────────────────────────
headers = gh_headers

datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str       = json.dumps(datos_export, ensure_ascii=False)

# Guardar copia local
with open("datos.json", "w", encoding="utf-8") as _f:
    _f.write(json_str)

contenido_b64  = base64.b64encode(json_str.encode()).decode()
headers        = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url            = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

resp = requests.get(url, headers=headers)
sha  = resp.json().get("sha") if resp.status_code == 200 else None

payload = {"message": f"Auto-update {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": contenido_b64}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"\n✅ datos.json actualizado con {len(datos_export)} tickers")
else:
    print(f"\n❌ Error subiendo JSON: {resp.status_code} — {resp.json().get('message')}")
    exit(1)

# ── EXPORTAR DATOS_VIERNES_CIERRE.JSON (snapshot fijo del Top10 semanal) ──
# Solo se pisa en la corrida de cierre (17:00 ARG) de un viernes, para que quede
# fija toda la semana hasta el próximo cierre. RUN_SCHEDULE viene del workflow
# (github.event.schedule) y viene vacío en corridas manuales (workflow_dispatch),
# que por eso no la disparan.
CIERRE_VIERNES_ARCHIVO = "datos_viernes_cierre.json"
es_corrida_cierre = os.environ.get("RUN_SCHEDULE") == "0 20 * * 1-5"
es_viernes = datetime.utcnow().weekday() == 4
if es_corrida_cierre and es_viernes:
    snapshot = {"fecha": datetime.utcnow().strftime('%Y-%m-%d'), "datos": datos_export}
    snapshot_str = json.dumps(snapshot, ensure_ascii=False)
    snapshot_b64 = base64.b64encode(snapshot_str.encode()).decode()
    url_snap = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{CIERRE_VIERNES_ARCHIVO}"
    resp_snap = requests.get(url_snap, headers=headers)
    sha_snap  = resp_snap.json().get("sha") if resp_snap.status_code == 200 else None
    payload_snap = {"message": f"Snapshot cierre viernes {datetime.utcnow().strftime('%d/%m/%Y')}", "content": snapshot_b64}
    if sha_snap:
        payload_snap["sha"] = sha_snap
    resp_snap = requests.put(url_snap, headers=headers, json=payload_snap)
    if resp_snap.status_code in [200, 201]:
        print(f"✅ {CIERRE_VIERNES_ARCHIVO} actualizado (cierre de viernes)")
    else:
        print(f"⚠️  Error subiendo {CIERRE_VIERNES_ARCHIVO}: {resp_snap.status_code} — {resp_snap.json().get('message')}")
else:
    print(f"ℹ️  {CIERRE_VIERNES_ARCHIVO} no se toca en esta corrida (no es cierre de viernes)")

# ── EXPORTAR REGIMEN.JSON A GITHUB ────────────────────────────
if regimen_data:
    regimen_str = json.dumps(regimen_data, ensure_ascii=False)
    regimen_b64 = base64.b64encode(regimen_str.encode()).decode()
    url_reg = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/regimen.json"
    resp_reg = requests.get(url_reg, headers=headers)
    sha_reg  = resp_reg.json().get("sha") if resp_reg.status_code == 200 else None
    payload_reg = {"message": f"Auto-update régimen {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": regimen_b64}
    if sha_reg:
        payload_reg["sha"] = sha_reg
    resp_reg = requests.put(url_reg, headers=headers, json=payload_reg)
    if resp_reg.status_code in [200, 201]:
        print(f"✅ regimen.json actualizado en GitHub")
    else:
        print(f"⚠️  Error subiendo regimen.json: {resp_reg.status_code} — {resp_reg.json().get('message')}")
else:
    print("⚠️  regimen.json no exportado (datos insuficientes)")

# ── EXPORTAR BREAKOUTS_LOG.JSON A GITHUB (feedback Capa 3) ────
breakouts_str = json.dumps(breakouts_log, ensure_ascii=False)
breakouts_b64 = base64.b64encode(breakouts_str.encode()).decode()
url_bl = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{BREAKOUTS_LOG_FILE}"
resp_bl = requests.get(url_bl, headers=headers)
sha_bl  = resp_bl.json().get("sha") if resp_bl.status_code == 200 else None
payload_bl = {"message": f"Auto-update breakouts_log {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": breakouts_b64}
if sha_bl:
    payload_bl["sha"] = sha_bl
resp_bl = requests.put(url_bl, headers=headers, json=payload_bl)
if resp_bl.status_code in [200, 201]:
    print(f"✅ breakouts_log.json actualizado ({len(breakouts_log)} entradas)")
else:
    print(f"⚠️  Error subiendo breakouts_log.json: {resp_bl.status_code} — {resp_bl.json().get('message')}")

# ── EXPORTAR RS_HISTORIA.JSON A GITHUB (V7 RRG ETFs) ─────────
SECTOR_ETFS_RRG = ['XLK','XLE','XLF','XLV','XLI','XLY','XLP','XLU','XLB','XLRE','XLC',
                   'SMH','CIBR','CLOU','BOTZ','IBB','ITA','KRE','XOP','ICLN','URA',
                   'QQQ','GLD','GDX','SLV','EWZ','FXI','ARGT','TLT','IWM','DIA']
RS_HISTORIA_SEMANAS = 16
RS_LOOKBACK = 12

def calcular_rs_historia():
    try:
        import yfinance as yf
        import numpy as np
        raw = yf.download(SECTOR_ETFS_RRG + ['SPY'], period='2y', interval='1d',
                          auto_adjust=True, progress=False)
        datos_yf = raw['Close'] if isinstance(raw.columns, pd.MultiIndex) else raw
        weekly = datos_yf.resample('W-FRI').last().dropna(how='all')
        spy = weekly['SPY'].dropna()
        filas = []
        for t in SECTOR_ETFS_RRG:
            if t not in weekly.columns:
                continue
            serie = weekly[t].dropna()
            idx = serie.index.intersection(spy.index)
            if len(idx) < RS_LOOKBACK + 4:
                continue
            ratio = 100 * serie[idx] / spy[idx]
            media = ratio.rolling(RS_LOOKBACK).mean()
            std   = ratio.rolling(RS_LOOKBACK).std().replace(0, np.nan)
            z     = ((ratio - media) / std).clip(-4, 4)
            rs_ratio = (100 + z).round(2)
            rs_mom   = (100 + (rs_ratio - rs_ratio.rolling(4).mean()) * 2).clip(96, 104).round(2)
            df_t = pd.DataFrame({'rs_ratio': rs_ratio, 'rs_mom': rs_mom}).dropna()
            for fecha, row_rs in df_t.tail(RS_HISTORIA_SEMANAS).iterrows():
                filas.append({
                    'fecha':    fecha.strftime('%Y-%m-%d'),
                    'ticker':   t,
                    'rs_ratio': float(row_rs['rs_ratio']),
                    'rs_mom':   float(row_rs['rs_mom'])
                })
        return filas
    except Exception as e:
        print(f'[RS_HISTORIA] Error: {e}')
        return []

try:
    rs_historia = calcular_rs_historia()
    if rs_historia:
        rs_str = json.dumps(rs_historia, ensure_ascii=False)
        rs_b64 = base64.b64encode(rs_str.encode()).decode()
        url_rs = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/rs_historia.json"
        resp_rs = requests.get(url_rs, headers=headers)
        sha_rs  = resp_rs.json().get("sha") if resp_rs.status_code == 200 else None
        payload_rs = {"message": f"Auto-update RS historia {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": rs_b64}
        if sha_rs:
            payload_rs["sha"] = sha_rs
        resp_rs = requests.put(url_rs, headers=headers, json=payload_rs)
        if resp_rs.status_code in [200, 201]:
            print(f"✅ rs_historia.json actualizado: {len(rs_historia)} filas")
        else:
            print(f"⚠️  Error subiendo rs_historia.json: {resp_rs.status_code} — {resp_rs.json().get('message')}")
    else:
        print("⚠️  rs_historia.json vacío, no exportado")
except Exception as e:
    print(f"⚠️  rs_historia.json: {e}")

# ── FIN — el resto de las celdas son solo para Colab ──────────
import sys; sys.exit(0)

import gspread
from google.colab import auth
from google.auth import default

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

sh = gc.open_by_key(SHEET_ID)

try:
    ws = sh.worksheet("Dashboard")
    ws.clear()
except:
    ws = sh.add_worksheet(title="Dashboard", rows=500, cols=25)

columnas = [
    "Grupo", "Ticker", "Precio", "Var Día %",
    "EMA200", "EMA200 Slope", "Dist EMA200 %",
    "SMA50",  "Dist SMA50 %",
    "Máx 52W", "Dist Máx52W %",
    "Mín 52W", "Dist Mín52W %",
    "RSI 14", "Vol Relativa", "Vol Inusual %",
    "RS Score", "RS Ayer", "RS Semana ant.", "RS Mes ant.", "FR > SMA50",
    "FR Hoy", "FR Ayer", "FR Semana ant.", "FR Mes ant.",
    "Market Cap USD", "Market Cap Cat", "Sector", "Tipo",
    "ETF Sector", "Vs Sector %"
]

df_export = df[columnas]

ws.update(values=[df_export.columns.tolist()] + df_export.fillna("—").values.tolist(), range_name="A1")
ws.update(values=[[f"Actualizado: {datetime.now().strftime('%d/%m/%Y %H:%M')}"]], range_name="A1")

print(f"✅ Sheet actualizado con {len(df)} tickers y {len(columnas)} columnas")
print(f"🔗 https://docs.google.com/spreadsheets/d/{SHEET_ID}")

# ============================================
# CELDA 5 — FORMATO VISUAL DEL DASHBOARD
# ============================================
import gspread
from gspread_formatting import (
    CellFormat, Color, TextFormat, BooleanRule, BooleanCondition,
    ConditionalFormatRule, GridRange, format_cell_range,
    get_conditional_format_rules, set_column_width
)

ws = sh.worksheet("Dashboard")

# --- Congelar primera fila ---
ws.freeze(rows=1)

# --- Color de encabezado (azul oscuro) ---
header_format = CellFormat(
    backgroundColor=Color(0.13, 0.27, 0.49),
    textFormat=TextFormat(bold=True, foregroundColor=Color(1, 1, 1), fontSize=10),
    horizontalAlignment="CENTER"
)
format_cell_range(ws, "A1:N1", header_format)

# --- Formato condicional semáforo ---
rules = get_conditional_format_rules(ws)
rules.clear()

for col in ["D", "F", "H", "J", "K", "M"]:
    # Verde para positivos
    rules.append(ConditionalFormatRule(
        ranges=[GridRange.from_a1_range(f"{col}2:{col}500", ws)],
        booleanRule=BooleanRule(
            condition=BooleanCondition("NUMBER_GREATER", ["0"]),
            format=CellFormat(backgroundColor=Color(0.71, 0.92, 0.71))
        )
    ))
    # Rojo para negativos
    rules.append(ConditionalFormatRule(
        ranges=[GridRange.from_a1_range(f"{col}2:{col}500", ws)],
        booleanRule=BooleanRule(
            condition=BooleanCondition("NUMBER_LESS", ["0"]),
            format=CellFormat(backgroundColor=Color(0.96, 0.71, 0.71))
        )
    ))

rules.save()

# --- Anchos de columna ---
set_column_width(ws, "A", 120)
set_column_width(ws, "B", 70)
set_column_width(ws, "C", 80)
set_column_width(ws, "D", 80)
set_column_width(ws, "E", 80)
set_column_width(ws, "F", 110)
set_column_width(ws, "G", 70)
set_column_width(ws, "H", 105)
set_column_width(ws, "I", 80)
set_column_width(ws, "J", 110)
set_column_width(ws, "K", 105)
set_column_width(ws, "L", 90)
set_column_width(ws, "M", 100)

print("✅ Formato aplicado correctamente")

# ============================================
# CELDA 6 — EXPORTAR DATOS COMO JSON PARA DASHBOARD
# ============================================
import json

# Convertimos el dataframe a JSON limpio
datos_json = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_json.append(item)

# Guardamos en el Sheet en una hoja separada llamada "JSON"
try:
    ws_json = sh.worksheet("JSON")
    ws_json.clear()
except:
    ws_json = sh.add_worksheet(title="JSON", rows=len(datos_json)+5, cols=2)

# Una fila por ticker (evita el límite de 50k caracteres por celda)
filas = [[json.dumps(item)] for item in datos_json]
ws_json.update(values=filas, range_name="A1")

print(f"✅ JSON exportado: {len(datos_json)} tickers en {len(filas)} filas")
print(f"📋 Campos disponibles: {list(datos_json[0].keys())}")

# ============================================
# CELDA 7 — GENERAR ARCHIVO HTML CON DATOS EMBEBIDOS
# ============================================
import json
from google.colab import files

# Convertimos los datos a JSON
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)

# Leemos el template HTML y reemplazamos la URL por los datos embebidos
html_template = '''<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<script>
const DATOS_EMBEBIDOS = ''' + json_str + ''';
</script>
</head>
<body>
<script>
// Redirect a la version completa
window.location.href = "dashboard_cedears.html";
</script>
</body>
</html>'''

# Guardamos el JSON como archivo separado que el HTML puede leer
with open('datos_cedears.json', 'w', encoding='utf-8') as f:
    json.dump(datos_export, f, ensure_ascii=False)

files.download('datos_cedears.json')
print(f"✅ JSON descargado con {len(datos_export)} tickers")
print("Guardá el archivo datos_cedears.json en la misma carpeta que el dashboard_cedears.html")

# ============================================
# CELDA 8 — DESCARGA HTML COMPLETO CON DATOS EMBEBIDOS
# ============================================
import json, urllib.request
from google.colab import files

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)

print(f"✅ {len(datos_export)} tickers preparados")
print(f"📦 Tamaño del JSON: {len(json_str)//1024} KB")
print("Pegá este resultado en Claude para que genere el HTML final")
print("\n--- PRIMERAS 3 FILAS (para verificar) ---")
for d in datos_export[:3]:
    print(d.get('Ticker'), '|', d.get('RS Score'), '|', d.get('Volatilidad 20d'))

# ============================================
# CELDA 9 — SUBIR JSON A GITHUB
# ============================================
import json, base64, requests
from datetime import datetime

GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)
contenido_b64 = base64.b64encode(json_str.encode()).decode()

headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

resp = requests.get(url, headers=headers)
sha = resp.json().get("sha") if resp.status_code == 200 else None

payload = {
    "message": f"Actualización datos {datetime.now().strftime('%d/%m/%Y %H:%M')}",
    "content": contenido_b64
}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"✅ datos.json subido a GitHub con {len(datos_export)} tickers")
    print(f"📋 Campos: {list(datos_export[0].keys())}")
else:
    print(f"❌ Error: {resp.status_code} — {resp.json().get('message')}")

import os
archivos = os.listdir('/content')
print([f for f in archivos if 'dashboard' in f.lower()])

with open('dashboard_v2_template.html', 'r', encoding='utf-8') as f:
    contenido = f.read()

print("Tamaño template:", len(contenido), "chars")
print("Tiene placeholder:", '##JSON_PLACEHOLDER##' in contenido)
print("Primeras 200 chars del script:", contenido[contenido.find('<script>'): contenido.find('<script>')+200])

# ============================================
# CELDA 10 — SUBE LOS DATOS DIRECTO A GITHUB
# ============================================
import json, base64, requests

# ── CONFIGURACIÓN ──
GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)
contenido_b64 = base64.b64encode(json_str.encode()).decode()

# Subimos a GitHub via API
headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

# Verificamos si el archivo ya existe (para actualizarlo)
resp = requests.get(url, headers=headers)
sha = resp.json().get("sha") if resp.status_code == 200 else None

payload = {
    "message": f"Actualización datos {datetime.now().strftime('%d/%m/%Y %H:%M')}",
    "content": contenido_b64
}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"✅ datos.json subido a GitHub con {len(datos_export)} tickers")
    print(f"🔗 https://{GITHUB_USER}.github.io/{GITHUB_REPO}/datos.json")
else:
    print(f"❌ Error: {resp.status_code} — {resp.json().get('message')}")

# ============================================
# CELDA 12 — BOT TELEGRAM TOP 5 RS DIARIO
# ============================================
import requests
from datetime import datetime

TELEGRAM_TOKEN   = "8608163960:AAEZpmmU0So3hwG-aNb6Slyjbz5DBOHDzvU"
TELEGRAM_CHAT_ID = "1673990665"

def enviar_mensaje(texto):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    requests.post(url, json={
        "chat_id": TELEGRAM_CHAT_ID,
        "text": texto,
        "parse_mode": "HTML"
    })

# Calculamos variación diaria de RS (RS Score - RS Ayer)
df_bot = df.copy()
df_bot['Delta RS Dia'] = df_bot['RS Score'] - df_bot['RS Ayer']

# Filtramos solo acciones (no ETFs) con RS Score válido
df_bot = df_bot[
    (df_bot['RS Score'].notna()) &
    (df_bot['RS Ayer'].notna()) &
    (df_bot['Tipo'] == 'Acción')
].copy()

# TOP 5 mayor aumento de RS en el día
top5 = df_bot.nlargest(5, 'Delta RS Dia')

# Armamos el mensaje
fecha = datetime.now().strftime('%d/%m/%Y')
hora  = datetime.now().strftime('%H:%M')

msg = f"📊 <b>TOP 5 — Mayor aumento de RS Score</b>\n"
msg += f"📅 {fecha} | ⏰ {hora}\n"
msg += f"━━━━━━━━━━━━━━━━━━━━\n\n"

medallas = ['🥇','🥈','🥉','4️⃣','5️⃣']

for i, (_, row) in enumerate(top5.iterrows()):
    delta = row['Delta RS Dia']
    rs    = row['RS Score']
    ayer  = row['RS Ayer']
    sector = row['Sector'] or '—'

    msg += f"{medallas[i]} <b>{row['Ticker']}</b>\n"
    msg += f"   RS: <b>{rs}</b>  (ayer: {ayer})  <b>▲+{delta:.1f}</b>\n"
    msg += f"   Sector: {sector}\n\n"

msg += f"━━━━━━━━━━━━━━━━━━━━\n"
msg += f"<i>Warren Bife Indicator</i>"

enviar_mensaje(msg)
print(f"✅ Mensaje enviado a Telegram")
print(f"\n🏆 TOP 5 mayor aumento RS Score:")
print(top5[['Ticker','RS Score','RS Ayer','Delta RS Dia','Sector']].to_string(index=False))