# -*- coding: utf-8 -*-
"""Datos Claudio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvZ9kDjxOSMoyYs3bxAiQNVjO5crOjRD
"""

# Dependencias instaladas via workflow (requirements)

# ============================================
# CONFIGURACIÓN — EDITÁ SOLO ESTA SECCIÓN
# ============================================

# Tu Google Sheet ID
SHEET_ID = "1Tuy0X7VMylI0-4PA1dSWPUK4_-iqPmczPqfjTUtDldY"

# Benchmark para fuerza relativa
BENCHMARK = "SPY"

# Tickers organizados por categoría
TICKERS = {
    "ADRs Argentina": [
        "YPF", "GGAL", "BMA", "LOMA", "MELI", "GLOB", "SUPV", "BBAR",
        "CEPU", "PAM", "TGS", "IRS", "BIOX", "VIST", "CAAP", "ADGO"
    ],
    "CEDEARs Tecnología": [
        "AAPL", "MSFT", "GOOGL", "META", "AMZN", "NVDA", "TSLA", "NFLX",
        "AMD", "INTC", "QCOM", "AVGO", "MU", "AMAT", "LRCX", "MRVL",
        "TXN", "TSM", "ARM", "ASML", "ADBE", "CRM", "NOW", "TEAM",
        "SNOW", "DOCU", "TWLO", "SHOP", "UBER", "ABNB", "BKNG",
        "PYPL", "SQ", "COIN", "MSTR", "PLTR", "PANW", "CSCO", "IBM",
        "ORCL", "SAP", "INFY", "ACN", "ADP", "MSI", "GRMN",
        "EBAY", "ETSY", "PINS", "SNAP", "SPOT", "ZM", "RBLX",
        "ROKU", "SONY", "NTCO", "SE", "JD", "BIDU", "BABA",
        "NTES", "PDD", "TCOM", "AI", "PATH", "UPST", "HOOD",
        "RKLB", "ASTS", "ALAB", "RGTI", "OKLO", "IREN",
        "IBIT", "ETHA", "ARKK", "CRWV", "TEM", "SATL",
        "ANET", "SNDK", "NBIS", "ONDS"
    ],
    "CEDEARs Finanzas": [
        "JPM", "BAC", "GS", "C", "WFC", "USB", "BK", "AXP",
        "V", "MA", "PYPL", "SCHW", "BX", "MS", "AIG",
        "BBD", "ITUB", "BSBR", "SAN", "BBV", "ING",
        "HSBC", "HDB", "IBN", "KB", "MFG", "MUFG", "NMR",
        "XP", "PAGS", "STNE", "NU", "HOOD", "FISV", "O"
    ],
    "CEDEARs Salud": [
        "JNJ", "PFE", "ABBV", "MRK", "AMGN", "GILD", "BIIB",
        "MRNA", "BMY", "AZN", "NVS", "GSK", "LLY", "MDT",
        "ISRG", "DHR", "TMO", "UNH", "CVS", "VRTX", "MDLZ"
    ],
    "CEDEARs Consumo & Retail": [
        "KO", "PEP", "MCD", "WMT", "COST", "TGT", "HD", "NKE",
        "SBUX", "DIS", "MO", "PM", "PG", "CL", "KMB", "UL",
        "DEO", "HSY", "MDLZ", "SYY", "TJX", "ROST", "URBN",
        "ANF", "WBA", "DECK", "HMC", "TM", "CAJ", "TTM"
    ],
    "CEDEARs Energía & Materiales": [
        "XOM", "CVX", "BP", "SHEL", "TTE", "OXY", "HAL", "SLB",
        "BKR", "PSX", "EQNR", "FCX", "RIO", "BHP", "VALE",
        "GOLD", "NEM", "AEM", "GFI", "HMY", "KGC", "PAAS",
        "MUX", "HL", "CDE", "NG", "AUY", "GGB", "SID",
        "NUE", "SCCO", "MOS", "DOW", "LND", "BNG",
        "SUZ", "BAK", "UGP", "PBR", "PTR", "SNP",
        "COP", "GLNG", "MP", "CCJ", "NEE"
    ],
    "CEDEARs Industria & Aero": [
        "BA", "CAT", "MMM", "GE", "HON", "RTX", "LMT", "HWM",
        "DE", "PCAR", "UNP", "FDX", "DAL", "AAL", "UAL",
        "GM", "F", "STLA", "HOG", "ERJ", "TSLA",
        "RACE", "HPQ", "IP", "AVY", "IFF", "GLW",
        "ECL", "EMR", "JCI", "PKS", "CX", "ARCO"
    ],
    "CEDEARs ETFs Renta Variable": [
        "SPY", "QQQ", "DIA", "IVV", "IWM", "VIG", "VEA",
        "EWZ", "EEM", "IEMG", "EFA", "EWJ", "FXI",
        "ILF", "ACWI", "IEUR", "IJH",
        "XLK", "XLF", "XLE", "XLV", "XLI", "XLB",
        "XLC", "XLY", "XLP", "XLRE", "XLU",
        "SMH", "IBB", "ITA", "COPX", "URA",
        "ARKK", "SPXL", "TQQQ", "SH", "PSQ",
        "ESGU", "IVW", "IVE", "SPGI"
    ],
    "CEDEARs ETFs Commodities & Bonos": [
        "GLD", "SLV", "IAU", "GDX", "USO",
        "TLT", "HYG", "VXX"
    ],
    "CEDEARs Brasil": [
        "VALE", "PBR", "ITUB", "BBD", "BSBR", "SUZ", "GGB",
        "BAK", "BRFS", "EBR", "ELP", "SBS", "UGP",
        "ABEV", "PAGS", "STNE", "XP", "CAAP"
    ],
    "CEDEARs Europa & Asia": [
        "ASML", "SAP", "ADBE", "AZN", "NVS", "GSK", "BAYER",
        "BAYN", "BAS", "EOAN", "NEC1", "MBG", "BSN",
        "VOD", "T", "TMUS", "VZ", "NGG", "ORAN",
        "SIEGY", "PHG", "ING", "BBV", "SAN",
        "TTE", "ENI", "SHEL", "BP", "EQNR",
        "RIO", "BHP", "LFC", "SNP", "PTR",
        "HMC", "TM", "SONY", "MUFG", "MFG", "NMR",
        "TSM", "SMSN", "INFY", "HDB", "IBN",
        "BABA", "JD", "BIDU", "NTES", "PDD", "SE"
    ]
}

# ETF de sector por ticker (para comparar vs su sector)
ETF_SECTOR = {
    # Tecnología
    "AAPL": "XLK", "MSFT": "XLK", "GOOGL": "XLK", "META": "XLK",
    "UBER": "XLK", "SNAP": "XLK", "SHOP": "XLK", "SQ": "XLK",
    "ADBE": "XLK", "CRM": "XLK", "NOW": "XLK", "TEAM": "XLK",
    "SNOW": "XLK", "DOCU": "XLK", "TWLO": "XLK", "IBM": "XLK",
    "ORCL": "XLK", "SAP": "XLK", "ACN": "XLK", "ADP": "XLK",
    "CSCO": "XLK", "MSI": "XLK", "INFY": "XLK", "PLTR": "XLK",
    "PANW": "XLK", "PATH": "XLK", "AI": "XLK", "TEM": "XLK",
    "COIN": "XLK", "MSTR": "XLK", "HOOD": "XLK",
    "ANET": "XLK", "SNDK": "SMH", "NBIS": "XLK", "ONDS": "XLK",
    # Semis
    "NVDA": "SMH", "AMD": "SMH", "INTC": "SMH", "QCOM": "SMH",
    "AVGO": "SMH", "MU": "SMH", "AMAT": "SMH", "LRCX": "SMH",
    "MRVL": "SMH", "TXN": "SMH", "TSM": "SMH", "ARM": "SMH",
    "ASML": "SMH", "SWKS": "SMH", "ADI": "SMH",
    # Finanzas
    "JPM": "XLF", "BAC": "XLF", "GS": "XLF", "C": "XLF",
    "WFC": "XLF", "AXP": "XLF", "V": "XLF", "MA": "XLF",
    "SCHW": "XLF", "BX": "XLF", "BK": "XLF", "USB": "XLF",
    "PYPL": "XLF", "FISV": "XLF", "O": "XLRE",
    # Salud
    "JNJ": "XLV", "PFE": "XLV", "ABBV": "XLV", "MRK": "XLV",
    "AMGN": "XLV", "GILD": "XLV", "BIIB": "XLV", "MRNA": "XLV",
    "BMY": "XLV", "LLY": "XLV", "MDT": "XLV", "ISRG": "XLV",
    "DHR": "XLV", "TMO": "XLV", "UNH": "XLV", "CVS": "XLV",
    "VRTX": "XLV", "AZN": "XLV", "NVS": "XLV", "GSK": "XLV",
    # Energía
    "XOM": "XLE", "CVX": "XLE", "BP": "XLE", "SHEL": "XLE",
    "TTE": "XLE", "OXY": "XLE", "HAL": "XLE", "SLB": "XLE",
    "BKR": "XLE", "PSX": "XLE", "EQNR": "XLE", "COP": "XLE", "GLNG": "XLE",
    # Materiales / Minería
    "GOLD": "GDX", "NEM": "GDX", "AEM": "GDX", "KGC": "GDX",
    "GFI": "GDX", "HMY": "GDX", "PAAS": "GDX", "MUX": "GDX",
    "HL": "GDX", "CDE": "GDX", "NG": "GDX", "AUY": "GDX",
    "FCX": "COPX", "SCCO": "COPX", "MP": "XLB", "CCJ": "URA", "NEE": "XLU",
    "RIO": "XLB", "BHP": "XLB", "VALE": "XLB", "GGB": "XLB",
    # Industria
    "BA": "XLI", "CAT": "XLI", "MMM": "XLI", "GE": "XLI",
    "HON": "XLI", "RTX": "XLI", "LMT": "XLI", "DE": "XLI",
    "UNP": "XLI", "FDX": "XLI", "HWM": "XLI",
    # Consumo discrecional
    "AMZN": "XLY", "TSLA": "XLY", "MCD": "XLY", "NKE": "XLY",
    "SBUX": "XLY", "HD": "XLY", "TGT": "XLY", "BKNG": "XLY",
    "ABNB": "XLY", "GM": "XLY", "F": "XLY", "HOG": "XLY",
    "RACE": "XLY", "TJX": "XLY", "ROST": "XLY",
    # Consumo básico
    "KO": "XLP", "PEP": "XLP", "WMT": "XLP", "COST": "XLP",
    "PG": "XLP", "CL": "XLP", "KMB": "XLP", "UL": "XLP",
    "PM": "XLP", "MO": "XLP", "HSY": "XLP", "MDLZ": "XLP",
    # Comunicaciones
    "GOOGL": "XLC", "META": "XLC", "NFLX": "XLC", "DIS": "XLC",
    "T": "XLC", "TMUS": "XLC", "VZ": "XLC", "SPOT": "XLC",
    # Latam
    "MELI": "EWZ", "GLOB": "EWZ", "VALE": "EWZ", "PBR": "EWZ",
    "ITUB": "EWZ", "BBD": "EWZ", "ABEV": "EWZ", "XP": "EWZ",
    "PAGS": "EWZ", "STNE": "EWZ",
}

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime

def calcular_rsi(close, periodo=14):
    # Wilder's Smoothing (RMA) — igual a TradingView
    delta = close.diff()
    ganancia = delta.clip(lower=0)
    perdida = (-delta.clip(upper=0))
    alpha = 1 / periodo
    avg_gan = ganancia.ewm(alpha=alpha, min_periods=periodo, adjust=False).mean()
    avg_per = perdida.ewm(alpha=alpha, min_periods=periodo, adjust=False).mean()
    rs = avg_gan / avg_per
    return round((100 - (100 / (1 + rs))).iloc[-1], 2)

def calcular_volatilidad_relativa(close, ruedas_corto=5, ruedas_largo=252):
    """
    Volatilidad relativa: vol últimas 5 ruedas / vol histórica 1 año.
    < 1 = más tranquilo que de costumbre
    > 1 = más volátil que de costumbre
    """
    retornos = close.pct_change().dropna()
    if len(retornos) < ruedas_largo:
        return None
    vol_corto     = retornos.tail(ruedas_corto).std() * np.sqrt(252) * 100
    vol_historica = retornos.tail(ruedas_largo).std() * np.sqrt(252) * 100
    if vol_historica == 0:
        return None
    return round(vol_corto / vol_historica, 2)

def calcular_volumen_inusual(volume, ruedas=20):
    if len(volume) < ruedas + 1:
        return None
    vol_hoy      = volume.iloc[-1]
    vol_promedio = volume.iloc[-ruedas-1:-1].mean()
    if vol_promedio == 0:
        return None
    return round((vol_hoy / vol_promedio - 1) * 100, 2)

def calcular_rs_score(close_ticker, close_spy, periodo_sma=50, lookback=252):
    df = pd.DataFrame({"ticker": close_ticker, "spy": close_spy}).dropna()
    if len(df) < lookback + 1:
        return None, None, None, None, None

    df["fr"]     = df["ticker"] / df["spy"]
    df["sma_fr"] = df["fr"].rolling(window=periodo_sma).mean()

    def percentrank_tv(series, length):
        """
        Replica exacta de ta.percentrank de TradingView:
        cuenta cuántos de los últimos 'length' valores anteriores
        son MENORES al valor actual (excluye el valor actual)
        """
        scores = []
        arr = series.values
        for i in range(len(arr)):
            if i < length:
                scores.append(np.nan)
            else:
                ventana = arr[i-length:i]
                actual  = arr[i]
                rank    = (ventana < actual).sum() / length * 100
                scores.append(round(rank, 2))
        return pd.Series(scores, index=series.index)

    df["rs_score"] = percentrank_tv(df["fr"], lookback)

    ultimo = df.iloc[-1]
    ayer   = df.iloc[-2]
    semana = df.iloc[-6]  if len(df) >= 6  else df.iloc[0]
    mes    = df.iloc[-22] if len(df) >= 22 else df.iloc[0]

    sobre_sma = "✅ Sí" if ultimo["fr"] > ultimo["sma_fr"] else "❌ No"

    return (
        round(ultimo["rs_score"], 1),
        round(ayer["rs_score"],   1),
        round(semana["rs_score"], 1),
        round(mes["rs_score"],    1),
        sobre_sma,
        round(float(ultimo["fr"]), 6),
        round(float(ayer["fr"]),   6),
        round(float(semana["fr"]), 6),
        round(float(mes["fr"]),    6),
    )

def detectar_vcp(hist, pivot_order=3):
    try:
        h = hist['High'].values
        l = hist['Low'].values
        c = hist['Close'].values
        v = hist['Volume'].values
        # Últimas 90 ruedas
        if len(c) > 90:
            h = h[-90:]; l = l[-90:]; c = c[-90:]; v = v[-90:]
        if len(c) < 30:
            return {'VCP Score': None, 'VCP Detected': False, 'VCP Contractions': 0,
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False}

        def find_pivots(arr, order, mode):
            pivots = []
            for i in range(order, len(arr) - order):
                w = arr[i-order:i+order+1]
                if mode == 'H' and arr[i] >= max(w):
                    pivots.append((i, float(arr[i])))
                elif mode == 'L' and arr[i] <= min(w):
                    pivots.append((i, float(arr[i])))
            return pivots

        ph = find_pivots(h, pivot_order, 'H')
        pl = find_pivots(l, pivot_order, 'L')

        if not ph or not pl:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': 0,
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False}

        all_piv = [(i, 'H', val) for i, val in ph] + [(i, 'L', val) for i, val in pl]
        all_piv.sort()

        contractions = []
        i = 0
        while i < len(all_piv):
            if all_piv[i][1] == 'H':
                hi, _, hval = all_piv[i]
                for j in range(i + 1, len(all_piv)):
                    if all_piv[j][1] == 'L' and all_piv[j][0] > hi:
                        li, _, lval = all_piv[j]
                        if hval > lval:
                            pct     = (hval - lval) / hval * 100
                            seg_vol = float(np.mean(v[hi:li+1])) if li > hi else float(v[hi])
                            contractions.append({'high': hval, 'low': lval, 'pct': pct, 'avg_vol': seg_vol})
                        i = j
                        break
                else:
                    i += 1
            else:
                i += 1

        if len(contractions) < 2:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': len(contractions),
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False}

        pcts = [ct['pct'] for ct in contractions]
        vols = [ct['avg_vol'] for ct in contractions]
        n_c  = len(contractions)
        pairs = n_c - 1

        pct_dec = sum(1 for k in range(pairs) if pcts[k] > pcts[k+1]) / pairs
        vol_dec = sum(1 for k in range(pairs) if vols[k] > vols[k+1]) / pairs

        last_pct       = pcts[-1]
        last_piv_high  = contractions[-1]['high']
        dist_pivot     = (float(c[-1]) - last_piv_high) / last_piv_high * 100

        score = 0
        score += round(pct_dec * 35)
        score += round(vol_dec * 20)
        if last_pct <= 5:    score += 20
        elif last_pct <= 10: score += 15
        elif last_pct <= 15: score += 10
        elif last_pct <= 20: score += 5
        if   -3  <= dist_pivot <= 1:   score += 15
        elif -5  <= dist_pivot < -3:   score += 12
        elif -8  <= dist_pivot < -5:   score += 8
        elif -15 <= dist_pivot < -8:   score += 4
        if n_c >= 4:   score += 10
        elif n_c == 3: score += 7
        elif n_c == 2: score += 4
        score = min(100, score)

        return {
            'VCP Score':          score,
            'VCP Detected':       score >= 60,
            'VCP Contractions':   n_c,
            'VCP Tightness':      round(last_pct, 2),
            'VCP Dist Pivot %':   round(dist_pivot, 2),
            'VCP Vol Decreasing': vol_dec >= 0.5,
        }
    except:
        return {'VCP Score': None, 'VCP Detected': False, 'VCP Contractions': 0,
                'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False}

def calcular_sesiones_10(close, volume):
    """
    Últimas 10 sesiones: días positivos/negativos y volumen acumulado por tipo.
    Un día es positivo si cierre > cierre anterior.
    """
    if len(close) < 11 or len(volume) < 10:
        return None, None, None, None
    precios = close.tail(11).values
    vols    = volume.tail(10).values
    dias_pos, dias_neg = 0, 0
    vol_pos,  vol_neg  = 0.0, 0.0
    for i in range(10):
        cambio = precios[i + 1] - precios[i]
        v      = float(vols[i])
        if cambio > 0:
            dias_pos += 1
            vol_pos  += v
        elif cambio < 0:
            dias_neg += 1
            vol_neg  += v
    return dias_pos, dias_neg, round(vol_pos), round(vol_neg)

def clasificar_market_cap(mc):
    if mc is None:     return "—"
    if mc >= 200e9:    return "Mega Cap"
    if mc >= 10e9:     return "Large Cap"
    if mc >= 2e9:      return "Mid Cap"
    if mc >= 300e6:    return "Small Cap"
    return "Micro Cap"

def obtener_info_ticker(ticker_symbol):
    try:
        info   = yf.Ticker(ticker_symbol).info
        mc     = info.get('marketCap', None)
        sector = info.get('sector', None)
        es_etf = info.get('quoteType', '') in ['ETF', 'MUTUALFUND']
        if es_etf and not sector:
            sector = "ETF"
        if not sector:
            sector = info.get('category', '—') or '—'
        return {
            "Market Cap USD": mc,
            "Market Cap Cat": clasificar_market_cap(mc),
            "Sector":         sector or "—",
            "Tipo":           "ETF" if es_etf else "Acción"
        }
    except:
        return {"Market Cap USD": None, "Market Cap Cat": "—", "Sector": "—", "Tipo": "—"}

def calcular_kpis(ticker_symbol, hist_spy):
    try:
        tk   = yf.Ticker(ticker_symbol)
        hist = tk.history(period="2y")
        if hist.empty or len(hist) < 60:
            return None

        close  = hist["Close"]
        volume = hist["Volume"]
        precio_actual = round(close.iloc[-1], 2)

        # Medias móviles
        ema200_series = close.ewm(span=200, adjust=False).mean()
        ema200        = round(ema200_series.iloc[-1], 2)
        ema200_ref    = ema200_series.iloc[-10] if len(ema200_series) >= 10 else ema200_series.iloc[0]
        ema200_slope  = round(ema200 - float(ema200_ref), 4)
        sma50         = round(close.rolling(window=50).mean().iloc[-1], 2)
        dist_ema200   = round((precio_actual - ema200) / ema200 * 100, 2)
        dist_sma50    = round((precio_actual - sma50)  / sma50  * 100, 2)

        # Máximo y mínimo 52 semanas
        max_52w    = round(close.tail(252).max(), 2)
        dist_max52 = round((precio_actual - max_52w) / max_52w * 100, 2)
        min_52w    = round(close.tail(252).min(), 2)
        dist_min52 = round((precio_actual - min_52w) / min_52w * 100, 2)

        # Variación del día
        var_dia = round((close.iloc[-1] - close.iloc[-2]) / close.iloc[-2] * 100, 2)

        # RSI, Vol Relativa, Volumen inusual
        rsi     = calcular_rsi(close)
        vol_rel = calcular_volatilidad_relativa(close)
        vol_inu = calcular_volumen_inusual(volume, 20)

        # Sesiones 10 ruedas
        dias_pos_10, dias_neg_10, vol_pos_10, vol_neg_10 = calcular_sesiones_10(close, volume)

        # Vol 5d/40d: ratio volumen promedio últimas 5 ruedas vs últimas 40
        vol_5d_40d = None
        if len(volume) >= 40:
            v5  = volume.tail(5).mean()
            v40 = volume.tail(40).mean()
            if v40 > 0:
                vol_5d_40d = round(v5 / v40, 2)

        # RS Score
        score_actual, score_ayer, score_semana, score_mes, sobre_sma, \
        fr_hoy, fr_ayer, fr_semana, fr_mes = calcular_rs_score(
            close, hist_spy["Close"]
        )

        # VCP
        vcp = detectar_vcp(hist)

        return {
            "Ticker":          ticker_symbol,
            "Precio":          precio_actual,
            "Var Día %":       var_dia,
            "EMA200":          ema200,
            "EMA200 Slope":    ema200_slope,
            "Dist EMA200 %":   dist_ema200,
            "SMA50":           sma50,
            "Dist SMA50 %":    dist_sma50,
            "Máx 52W":         max_52w,
            "Dist Máx52W %":   dist_max52,
            "Mín 52W":         min_52w,
            "Dist Mín52W %":   dist_min52,
            "RSI 14":          rsi,
            "Vol Relativa":    vol_rel,
            "Vol Inusual %":   vol_inu,
            "RS Score":        score_actual,
            "RS Ayer":         score_ayer,
            "RS Semana ant.":  score_semana,
            "RS Mes ant.":     score_mes,
            "FR > SMA50":          sobre_sma,
            "FR Hoy":              fr_hoy,
            "FR Ayer":             fr_ayer,
            "FR Semana ant.":      fr_semana,
            "FR Mes ant.":         fr_mes,
            "VCP Score":           vcp['VCP Score'],
            "VCP Detected":        vcp['VCP Detected'],
            "VCP Contractions":    vcp['VCP Contractions'],
            "VCP Tightness":       vcp['VCP Tightness'],
            "VCP Dist Pivot %":    vcp['VCP Dist Pivot %'],
            "VCP Vol Decreasing":  vcp['VCP Vol Decreasing'],
            "Días + 10s":          dias_pos_10,
            "Días - 10s":          dias_neg_10,
            "Vol días + 10s":      vol_pos_10,
            "Vol días - 10s":      vol_neg_10,
            "Vol 5d/40d":          vol_5d_40d,
        }
    except Exception as e:
        print(f"  ⚠️ Error con {ticker_symbol}: {e}")
        return None

# ── DESCARGA SPY ──────────────────────────────────────────────
print("⏳ Descargando SPY como referencia...")
hist_spy = yf.Ticker("SPY").history(period="2y")

# ── LOOP PRINCIPAL ────────────────────────────────────────────
print("⏳ Calculando KPIs + Market Cap + Sector + Volumen...")
todos_los_datos = []
tickers_procesados = set()

for grupo, tickers in TICKERS.items():
    print(f"\n📂 {grupo}")
    for ticker in list(dict.fromkeys(tickers)):
        if ticker in tickers_procesados:
            continue
        tickers_procesados.add(ticker)
        print(f"  → {ticker}")

        datos = calcular_kpis(ticker, hist_spy)
        if not datos:
            continue

        datos["Grupo"] = grupo

        info = obtener_info_ticker(ticker)
        datos.update(info)

        sector_etf = ETF_SECTOR.get(ticker, None)
        if sector_etf:
            try:
                t  = yf.Ticker(ticker).history(period="3mo")["Close"]
                s  = yf.Ticker(sector_etf).history(period="3mo")["Close"]
                vs = round(((t.iloc[-1]/t.iloc[0]) / (s.iloc[-1]/s.iloc[0]) - 1) * 100, 2)
                datos["Vs Sector %"] = vs
                datos["ETF Sector"]  = sector_etf
            except:
                datos["Vs Sector %"] = None
                datos["ETF Sector"]  = None
        else:
            datos["Vs Sector %"] = None
            datos["ETF Sector"]  = None

        todos_los_datos.append(datos)

df = pd.DataFrame(todos_los_datos)
print(f"\n✅ Datos listos: {len(df)} tickers")
print(df[["Ticker", "Dist Mín52W %", "Vol Relativa", "RS Score", "Sector", "Market Cap Cat"]].head(10).to_string(index=False))

# ── EXPORTAR A GITHUB ──────────────────────────────────────────
import json, base64, requests, os
from datetime import datetime

GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"

datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str       = json.dumps(datos_export, ensure_ascii=False)

# Guardar copia local
with open("datos.json", "w", encoding="utf-8") as _f:
    _f.write(json_str)

contenido_b64  = base64.b64encode(json_str.encode()).decode()
headers        = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url            = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

resp = requests.get(url, headers=headers)
sha  = resp.json().get("sha") if resp.status_code == 200 else None

payload = {"message": f"Auto-update {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": contenido_b64}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"\n✅ datos.json actualizado con {len(datos_export)} tickers")
else:
    print(f"\n❌ Error subiendo JSON: {resp.status_code} — {resp.json().get('message')}")
    exit(1)

# ── FIN — el resto de las celdas son solo para Colab ──────────
import sys; sys.exit(0)

import gspread
from google.colab import auth
from google.auth import default

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

sh = gc.open_by_key(SHEET_ID)

try:
    ws = sh.worksheet("Dashboard")
    ws.clear()
except:
    ws = sh.add_worksheet(title="Dashboard", rows=500, cols=25)

columnas = [
    "Grupo", "Ticker", "Precio", "Var Día %",
    "EMA200", "EMA200 Slope", "Dist EMA200 %",
    "SMA50",  "Dist SMA50 %",
    "Máx 52W", "Dist Máx52W %",
    "Mín 52W", "Dist Mín52W %",
    "RSI 14", "Vol Relativa", "Vol Inusual %",
    "RS Score", "RS Ayer", "RS Semana ant.", "RS Mes ant.", "FR > SMA50",
    "FR Hoy", "FR Ayer", "FR Semana ant.", "FR Mes ant.",
    "Market Cap USD", "Market Cap Cat", "Sector", "Tipo",
    "ETF Sector", "Vs Sector %"
]

df_export = df[columnas]

ws.update(values=[df_export.columns.tolist()] + df_export.fillna("—").values.tolist(), range_name="A1")
ws.update(values=[[f"Actualizado: {datetime.now().strftime('%d/%m/%Y %H:%M')}"]], range_name="A1")

print(f"✅ Sheet actualizado con {len(df)} tickers y {len(columnas)} columnas")
print(f"🔗 https://docs.google.com/spreadsheets/d/{SHEET_ID}")

# ============================================
# CELDA 5 — FORMATO VISUAL DEL DASHBOARD
# ============================================
import gspread
from gspread_formatting import (
    CellFormat, Color, TextFormat, BooleanRule, BooleanCondition,
    ConditionalFormatRule, GridRange, format_cell_range,
    get_conditional_format_rules, set_column_width
)

ws = sh.worksheet("Dashboard")

# --- Congelar primera fila ---
ws.freeze(rows=1)

# --- Color de encabezado (azul oscuro) ---
header_format = CellFormat(
    backgroundColor=Color(0.13, 0.27, 0.49),
    textFormat=TextFormat(bold=True, foregroundColor=Color(1, 1, 1), fontSize=10),
    horizontalAlignment="CENTER"
)
format_cell_range(ws, "A1:N1", header_format)

# --- Formato condicional semáforo ---
rules = get_conditional_format_rules(ws)
rules.clear()

for col in ["D", "F", "H", "J", "K", "M"]:
    # Verde para positivos
    rules.append(ConditionalFormatRule(
        ranges=[GridRange.from_a1_range(f"{col}2:{col}500", ws)],
        booleanRule=BooleanRule(
            condition=BooleanCondition("NUMBER_GREATER", ["0"]),
            format=CellFormat(backgroundColor=Color(0.71, 0.92, 0.71))
        )
    ))
    # Rojo para negativos
    rules.append(ConditionalFormatRule(
        ranges=[GridRange.from_a1_range(f"{col}2:{col}500", ws)],
        booleanRule=BooleanRule(
            condition=BooleanCondition("NUMBER_LESS", ["0"]),
            format=CellFormat(backgroundColor=Color(0.96, 0.71, 0.71))
        )
    ))

rules.save()

# --- Anchos de columna ---
set_column_width(ws, "A", 120)
set_column_width(ws, "B", 70)
set_column_width(ws, "C", 80)
set_column_width(ws, "D", 80)
set_column_width(ws, "E", 80)
set_column_width(ws, "F", 110)
set_column_width(ws, "G", 70)
set_column_width(ws, "H", 105)
set_column_width(ws, "I", 80)
set_column_width(ws, "J", 110)
set_column_width(ws, "K", 105)
set_column_width(ws, "L", 90)
set_column_width(ws, "M", 100)

print("✅ Formato aplicado correctamente")

# ============================================
# CELDA 6 — EXPORTAR DATOS COMO JSON PARA DASHBOARD
# ============================================
import json

# Convertimos el dataframe a JSON limpio
datos_json = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_json.append(item)

# Guardamos en el Sheet en una hoja separada llamada "JSON"
try:
    ws_json = sh.worksheet("JSON")
    ws_json.clear()
except:
    ws_json = sh.add_worksheet(title="JSON", rows=len(datos_json)+5, cols=2)

# Una fila por ticker (evita el límite de 50k caracteres por celda)
filas = [[json.dumps(item)] for item in datos_json]
ws_json.update(values=filas, range_name="A1")

print(f"✅ JSON exportado: {len(datos_json)} tickers en {len(filas)} filas")
print(f"📋 Campos disponibles: {list(datos_json[0].keys())}")

# ============================================
# CELDA 7 — GENERAR ARCHIVO HTML CON DATOS EMBEBIDOS
# ============================================
import json
from google.colab import files

# Convertimos los datos a JSON
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)

# Leemos el template HTML y reemplazamos la URL por los datos embebidos
html_template = '''<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<script>
const DATOS_EMBEBIDOS = ''' + json_str + ''';
</script>
</head>
<body>
<script>
// Redirect a la version completa
window.location.href = "dashboard_cedears.html";
</script>
</body>
</html>'''

# Guardamos el JSON como archivo separado que el HTML puede leer
with open('datos_cedears.json', 'w', encoding='utf-8') as f:
    json.dump(datos_export, f, ensure_ascii=False)

files.download('datos_cedears.json')
print(f"✅ JSON descargado con {len(datos_export)} tickers")
print("Guardá el archivo datos_cedears.json en la misma carpeta que el dashboard_cedears.html")

# ============================================
# CELDA 8 — DESCARGA HTML COMPLETO CON DATOS EMBEBIDOS
# ============================================
import json, urllib.request
from google.colab import files

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)

print(f"✅ {len(datos_export)} tickers preparados")
print(f"📦 Tamaño del JSON: {len(json_str)//1024} KB")
print("Pegá este resultado en Claude para que genere el HTML final")
print("\n--- PRIMERAS 3 FILAS (para verificar) ---")
for d in datos_export[:3]:
    print(d.get('Ticker'), '|', d.get('RS Score'), '|', d.get('Volatilidad 20d'))

# ============================================
# CELDA 9 — SUBIR JSON A GITHUB
# ============================================
import json, base64, requests
from datetime import datetime

GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)
contenido_b64 = base64.b64encode(json_str.encode()).decode()

headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

resp = requests.get(url, headers=headers)
sha = resp.json().get("sha") if resp.status_code == 200 else None

payload = {
    "message": f"Actualización datos {datetime.now().strftime('%d/%m/%Y %H:%M')}",
    "content": contenido_b64
}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"✅ datos.json subido a GitHub con {len(datos_export)} tickers")
    print(f"📋 Campos: {list(datos_export[0].keys())}")
else:
    print(f"❌ Error: {resp.status_code} — {resp.json().get('message')}")

import os
archivos = os.listdir('/content')
print([f for f in archivos if 'dashboard' in f.lower()])

with open('dashboard_v2_template.html', 'r', encoding='utf-8') as f:
    contenido = f.read()

print("Tamaño template:", len(contenido), "chars")
print("Tiene placeholder:", '##JSON_PLACEHOLDER##' in contenido)
print("Primeras 200 chars del script:", contenido[contenido.find('<script>'): contenido.find('<script>')+200])

# ============================================
# CELDA 10 — SUBE LOS DATOS DIRECTO A GITHUB
# ============================================
import json, base64, requests

# ── CONFIGURACIÓN ──
GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)
contenido_b64 = base64.b64encode(json_str.encode()).decode()

# Subimos a GitHub via API
headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

# Verificamos si el archivo ya existe (para actualizarlo)
resp = requests.get(url, headers=headers)
sha = resp.json().get("sha") if resp.status_code == 200 else None

payload = {
    "message": f"Actualización datos {datetime.now().strftime('%d/%m/%Y %H:%M')}",
    "content": contenido_b64
}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"✅ datos.json subido a GitHub con {len(datos_export)} tickers")
    print(f"🔗 https://{GITHUB_USER}.github.io/{GITHUB_REPO}/datos.json")
else:
    print(f"❌ Error: {resp.status_code} — {resp.json().get('message')}")

# ============================================
# CELDA 12 — BOT TELEGRAM TOP 5 RS DIARIO
# ============================================
import requests
from datetime import datetime

TELEGRAM_TOKEN   = "8608163960:AAEZpmmU0So3hwG-aNb6Slyjbz5DBOHDzvU"
TELEGRAM_CHAT_ID = "1673990665"

def enviar_mensaje(texto):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    requests.post(url, json={
        "chat_id": TELEGRAM_CHAT_ID,
        "text": texto,
        "parse_mode": "HTML"
    })

# Calculamos variación diaria de RS (RS Score - RS Ayer)
df_bot = df.copy()
df_bot['Delta RS Dia'] = df_bot['RS Score'] - df_bot['RS Ayer']

# Filtramos solo acciones (no ETFs) con RS Score válido
df_bot = df_bot[
    (df_bot['RS Score'].notna()) &
    (df_bot['RS Ayer'].notna()) &
    (df_bot['Tipo'] == 'Acción')
].copy()

# TOP 5 mayor aumento de RS en el día
top5 = df_bot.nlargest(5, 'Delta RS Dia')

# Armamos el mensaje
fecha = datetime.now().strftime('%d/%m/%Y')
hora  = datetime.now().strftime('%H:%M')

msg = f"📊 <b>TOP 5 — Mayor aumento de RS Score</b>\n"
msg += f"📅 {fecha} | ⏰ {hora}\n"
msg += f"━━━━━━━━━━━━━━━━━━━━\n\n"

medallas = ['🥇','🥈','🥉','4️⃣','5️⃣']

for i, (_, row) in enumerate(top5.iterrows()):
    delta = row['Delta RS Dia']
    rs    = row['RS Score']
    ayer  = row['RS Ayer']
    sector = row['Sector'] or '—'

    msg += f"{medallas[i]} <b>{row['Ticker']}</b>\n"
    msg += f"   RS: <b>{rs}</b>  (ayer: {ayer})  <b>▲+{delta:.1f}</b>\n"
    msg += f"   Sector: {sector}\n\n"

msg += f"━━━━━━━━━━━━━━━━━━━━\n"
msg += f"<i>Warren Bife Indicator</i>"

enviar_mensaje(msg)
print(f"✅ Mensaje enviado a Telegram")
print(f"\n🏆 TOP 5 mayor aumento RS Score:")
print(top5[['Ticker','RS Score','RS Ayer','Delta RS Dia','Sector']].to_string(index=False))