# -*- coding: utf-8 -*-
"""Datos Claudio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvZ9kDjxOSMoyYs3bxAiQNVjO5crOjRD
"""

# Dependencias instaladas via workflow (requirements)

# ============================================
# CONFIGURACIÓN — EDITÁ SOLO ESTA SECCIÓN
# ============================================

# Tu Google Sheet ID
SHEET_ID = "1Tuy0X7VMylI0-4PA1dSWPUK4_-iqPmczPqfjTUtDldY"

# Benchmark para fuerza relativa
BENCHMARK = "SPY"

# Tickers organizados por categoría
TICKERS = {
    "ADRs Argentina": [
        "YPF", "GGAL", "BMA", "LOMA", "MELI", "GLOB", "SUPV", "BBAR",
        "CEPU", "PAM", "TGS", "IRS", "BIOX", "VIST", "CAAP", "ADGO"
    ],
    "CEDEARs Tecnología": [
        "AAPL", "MSFT", "GOOGL", "META", "AMZN", "NVDA", "TSLA", "NFLX",
        "AMD", "INTC", "QCOM", "AVGO", "MU", "AMAT", "LRCX", "MRVL",
        "TXN", "TSM", "ARM", "ASML", "ADBE", "CRM", "NOW", "TEAM",
        "SNOW", "DOCU", "TWLO", "SHOP", "UBER", "ABNB", "BKNG",
        "PYPL", "XYZ", "COIN", "MSTR", "PLTR", "PANW", "CSCO", "IBM",
        "ORCL", "SAP", "INFY", "ACN", "ADP", "MSI", "GRMN",
        "EBAY", "ETSY", "PINS", "SNAP", "SPOT", "ZM", "RBLX",
        "ROKU", "SONY", "NTCO", "SE", "JD", "BIDU", "BABA",
        "NTES", "PDD", "TCOM", "AI", "PATH", "UPST", "HOOD",
        "RKLB", "ASTS", "ALAB", "RGTI", "OKLO", "IREN",
        "IBIT", "ETHA", "ARKK", "CRWV", "TEM", "SATL",
        "ANET", "SNDK", "NBIS", "ONDS"
    ],
    "CEDEARs Finanzas": [
        "JPM", "BAC", "GS", "C", "WFC", "USB", "BK", "AXP",
        "V", "MA", "PYPL", "SCHW", "BX", "MS", "AIG",
        "BBD", "ITUB", "BSBR", "SAN", "BBV", "ING",
        "HSBC", "HDB", "IBN", "KB", "MFG", "MUFG", "NMR",
        "XP", "PAGS", "STNE", "NU", "HOOD", "FISV", "O"
    ],
    "CEDEARs Salud": [
        "JNJ", "PFE", "ABBV", "MRK", "AMGN", "GILD", "BIIB",
        "MRNA", "BMY", "AZN", "NVS", "GSK", "LLY", "MDT",
        "ISRG", "DHR", "TMO", "UNH", "CVS", "VRTX", "MDLZ"
    ],
    "CEDEARs Consumo & Retail": [
        "KO", "PEP", "MCD", "WMT", "COST", "TGT", "HD", "NKE",
        "SBUX", "DIS", "MO", "PM", "PG", "CL", "KMB", "UL",
        "DEO", "HSY", "MDLZ", "SYY", "TJX", "ROST", "URBN",
        "ANF", "WBA", "DECK", "HMC", "TM", "CAJ", "TTM"
    ],
    "CEDEARs Energía & Materiales": [
        "XOM", "CVX", "BP", "SHEL", "TTE", "OXY", "HAL", "SLB",
        "BKR", "PSX", "EQNR", "FCX", "RIO", "BHP", "VALE",
        "GOLD", "NEM", "AEM", "GFI", "HMY", "KGC", "PAAS",
        "MUX", "HL", "CDE", "NG", "AUY", "GGB", "SID",
        "NUE", "SCCO", "MOS", "DOW", "LND", "BNG",
        "SUZ", "BAK", "UGP", "PBR", "PTR", "SNP",
        "COP", "GLNG", "MP", "CCJ", "NEE"
    ],
    "CEDEARs Industria & Aero": [
        "BA", "CAT", "MMM", "GE", "HON", "RTX", "LMT", "HWM",
        "DE", "PCAR", "UNP", "FDX", "DAL", "AAL", "UAL",
        "GM", "F", "STLA", "HOG", "ERJ", "TSLA",
        "RACE", "HPQ", "IP", "AVY", "IFF", "GLW",
        "ECL", "EMR", "JCI", "PKS", "CX", "ARCO"
    ],
    "CEDEARs ETFs Renta Variable": [
        "SPY", "QQQ", "DIA", "IWM", "VIG", "VEA",
        "EWZ", "EEM", "IEMG", "EFA", "EWJ", "FXI",
        "ILF", "ACWI", "IEUR", "IJH",
        "XLK", "XLF", "XLE", "XLV", "XLI", "XLB",
        "XLC", "XLY", "XLP", "XLRE", "XLU",
        "SMH", "IBB", "ITA", "COPX", "URA",
        "ARKK", "TQQQ", "SH", "PSQ",
        "ESGU", "IVE", "SPGI",
        "CIBR", "CLOU", "BOTZ", "KRE", "XOP", "ICLN"
    ],
    "CEDEARs ETFs Commodities & Bonos": [
        "GLD", "SLV", "IAU", "GDX", "USO",
        "TLT", "HYG", "VXX"
    ],
    "CEDEARs Brasil": [
        "VALE", "PBR", "ITUB", "BBD", "BSBR", "SUZ", "GGB",
        "BAK", "BRFS", "EBR", "ELP", "SBS", "UGP",
        "ABEV", "PAGS", "STNE", "XP", "CAAP"
    ],
    "CEDEARs Europa & Asia": [
        "ASML", "SAP", "ADBE", "AZN", "NVS", "GSK", "BAYER",
        "BAYN", "BAS", "EOAN", "NEC1", "MBG", "BSN",
        "VOD", "T", "TMUS", "VZ", "NGG", "ORAN",
        "SIEGY", "PHG", "ING", "BBV", "SAN",
        "TTE", "ENI", "SHEL", "BP", "EQNR",
        "RIO", "BHP", "LFC", "SNP", "PTR",
        "HMC", "TM", "SONY", "MUFG", "MFG", "NMR",
        "TSM", "SMSN", "INFY", "HDB", "IBN",
        "BABA", "JD", "BIDU", "NTES", "PDD", "SE"
    ]
}

# ETF de sector por ticker (para comparar vs su sector)
ETF_SECTOR = {
    # Tecnología
    "AAPL": "XLK", "MSFT": "XLK", "GOOGL": "XLK", "META": "XLK",
    "UBER": "XLK", "SNAP": "XLK", "SHOP": "XLK", "XYZ": "XLK",
    "ADBE": "XLK", "CRM": "XLK", "NOW": "XLK", "TEAM": "XLK",
    "SNOW": "XLK", "DOCU": "XLK", "TWLO": "XLK", "IBM": "XLK",
    "ORCL": "XLK", "SAP": "XLK", "ACN": "XLK", "ADP": "XLK",
    "CSCO": "XLK", "MSI": "XLK", "INFY": "XLK", "PLTR": "XLK",
    "PANW": "XLK", "PATH": "XLK", "AI": "XLK", "TEM": "XLK",
    "COIN": "XLK", "MSTR": "XLK", "HOOD": "XLK",
    "ANET": "XLK", "SNDK": "SMH", "NBIS": "XLK", "ONDS": "XLK",
    # Semis
    "NVDA": "SMH", "AMD": "SMH", "INTC": "SMH", "QCOM": "SMH",
    "AVGO": "SMH", "MU": "SMH", "AMAT": "SMH", "LRCX": "SMH",
    "MRVL": "SMH", "TXN": "SMH", "TSM": "SMH", "ARM": "SMH",
    "ASML": "SMH", "SWKS": "SMH", "ADI": "SMH",
    # Finanzas
    "JPM": "XLF", "BAC": "XLF", "GS": "XLF", "C": "XLF",
    "WFC": "XLF", "AXP": "XLF", "V": "XLF", "MA": "XLF",
    "SCHW": "XLF", "BX": "XLF", "BK": "XLF", "USB": "XLF",
    "PYPL": "XLF", "FISV": "XLF", "O": "XLRE",
    # Salud
    "JNJ": "XLV", "PFE": "XLV", "ABBV": "XLV", "MRK": "XLV",
    "AMGN": "XLV", "GILD": "XLV", "BIIB": "XLV", "MRNA": "XLV",
    "BMY": "XLV", "LLY": "XLV", "MDT": "XLV", "ISRG": "XLV",
    "DHR": "XLV", "TMO": "XLV", "UNH": "XLV", "CVS": "XLV",
    "VRTX": "XLV", "AZN": "XLV", "NVS": "XLV", "GSK": "XLV",
    # Energía
    "XOM": "XLE", "CVX": "XLE", "BP": "XLE", "SHEL": "XLE",
    "TTE": "XLE", "OXY": "XLE", "HAL": "XLE", "SLB": "XLE",
    "BKR": "XLE", "PSX": "XLE", "EQNR": "XLE", "COP": "XLE", "GLNG": "XLE",
    # Materiales / Minería
    "GOLD": "GDX", "NEM": "GDX", "AEM": "GDX", "KGC": "GDX",
    "GFI": "GDX", "HMY": "GDX", "PAAS": "GDX", "MUX": "GDX",
    "HL": "GDX", "CDE": "GDX", "NG": "GDX", "AUY": "GDX",
    "FCX": "COPX", "SCCO": "COPX", "MP": "XLB", "CCJ": "URA", "NEE": "XLU",
    "RIO": "XLB", "BHP": "XLB", "VALE": "XLB", "GGB": "XLB",
    # Industria
    "BA": "XLI", "CAT": "XLI", "MMM": "XLI", "GE": "XLI",
    "HON": "XLI", "RTX": "XLI", "LMT": "XLI", "DE": "XLI",
    "UNP": "XLI", "FDX": "XLI", "HWM": "XLI",
    # Consumo discrecional
    "AMZN": "XLY", "TSLA": "XLY", "MCD": "XLY", "NKE": "XLY",
    "SBUX": "XLY", "HD": "XLY", "TGT": "XLY", "BKNG": "XLY",
    "ABNB": "XLY", "GM": "XLY", "F": "XLY", "HOG": "XLY",
    "RACE": "XLY", "TJX": "XLY", "ROST": "XLY",
    # Consumo básico
    "KO": "XLP", "PEP": "XLP", "WMT": "XLP", "COST": "XLP",
    "PG": "XLP", "CL": "XLP", "KMB": "XLP", "UL": "XLP",
    "PM": "XLP", "MO": "XLP", "HSY": "XLP", "MDLZ": "XLP",
    # Comunicaciones
    "GOOGL": "XLC", "META": "XLC", "NFLX": "XLC", "DIS": "XLC",
    "T": "XLC", "TMUS": "XLC", "VZ": "XLC", "SPOT": "XLC",
    # Latam
    "MELI": "EWZ", "GLOB": "EWZ", "VALE": "EWZ", "PBR": "EWZ",
    "ITUB": "EWZ", "BBD": "EWZ", "ABEV": "EWZ", "XP": "EWZ",
    "PAGS": "EWZ", "STNE": "EWZ",
}

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime

def calcular_rsi(close, periodo=14):
    # Wilder's Smoothing (RMA) — igual a TradingView
    delta = close.diff()
    ganancia = delta.clip(lower=0)
    perdida = (-delta.clip(upper=0))
    alpha = 1 / periodo
    avg_gan = ganancia.ewm(alpha=alpha, min_periods=periodo, adjust=False).mean()
    avg_per = perdida.ewm(alpha=alpha, min_periods=periodo, adjust=False).mean()
    rs = avg_gan / avg_per
    return round((100 - (100 / (1 + rs))).iloc[-1], 2)

def calcular_volatilidad_relativa(close, high, low, ruedas_corto=5, ruedas_largo=252):
    """
    Promedio del rango diario H-L/Close de los últimos 5 días vs histórico 1 año.
    Captura velas amplias individuales (ej: +20% en un día) y semanas extendidas.
    < 1 = velas más estrechas que de costumbre (comprimido)
    > 1 = velas más anchas que de costumbre (extendido/volátil)
    """
    if len(close) < ruedas_largo + ruedas_corto:
        return None
    rango_pct = ((high - low) / close).dropna()
    if len(rango_pct) < ruedas_largo:
        return None
    avg_5d   = rango_pct.tail(ruedas_corto).mean()
    avg_hist = rango_pct.tail(ruedas_largo).mean()
    if avg_hist == 0:
        return None
    return round(avg_5d / avg_hist, 2)

def calcular_volumen_inusual(volume, ruedas=20):
    if len(volume) < ruedas + 1:
        return None
    vol_hoy      = volume.iloc[-1]
    vol_promedio = volume.iloc[-ruedas-1:-1].mean()
    if vol_promedio == 0:
        return None
    return round((vol_hoy / vol_promedio - 1) * 100, 2)

def calcular_rs_score(close_ticker, close_spy, periodo_sma=50, lookback=252):
    df = pd.DataFrame({"ticker": close_ticker, "spy": close_spy}).dropna()
    if len(df) < lookback + 1:
        return None, None, None, None, None

    df["fr"]     = df["ticker"] / df["spy"]
    df["sma_fr"] = df["fr"].rolling(window=periodo_sma).mean()

    def percentrank_tv(series, length):
        """
        Replica exacta de ta.percentrank de TradingView:
        cuenta cuántos de los últimos 'length' valores anteriores
        son MENORES al valor actual (excluye el valor actual)
        """
        scores = []
        arr = series.values
        for i in range(len(arr)):
            if i < length:
                scores.append(np.nan)
            else:
                ventana = arr[i-length:i]
                actual  = arr[i]
                rank    = (ventana < actual).sum() / length * 100
                scores.append(round(rank, 2))
        return pd.Series(scores, index=series.index)

    df["rs_score"] = percentrank_tv(df["fr"], lookback)

    ultimo = df.iloc[-1]
    ayer   = df.iloc[-2]
    semana = df.iloc[-6]  if len(df) >= 6  else df.iloc[0]
    mes    = df.iloc[-22] if len(df) >= 22 else df.iloc[0]

    sobre_sma = "✅ Sí" if ultimo["fr"] > ultimo["sma_fr"] else "❌ No"

    return (
        round(ultimo["rs_score"], 1),
        round(ayer["rs_score"],   1),
        round(semana["rs_score"], 1),
        round(mes["rs_score"],    1),
        sobre_sma,
        round(float(ultimo["fr"]), 6),
        round(float(ayer["fr"]),   6),
        round(float(semana["fr"]), 6),
        round(float(mes["fr"]),    6),
    )

def atr14_pct(df):
    """ATR de 14 ruedas expresado como % del precio actual."""
    if df is None or len(df) < 15:
        return None
    try:
        high  = df['High']
        low   = df['Low']
        close = df['Close']
        prev  = close.shift(1)
        tr = pd.concat([
            high - low,
            (high - prev).abs(),
            (low  - prev).abs()
        ], axis=1).max(axis=1)
        atr14  = tr.tail(14).mean()
        precio = close.iloc[-1]
        if precio <= 0:
            return None
        return round(float(atr14 / precio * 100), 4)
    except:
        return None

def vol_anual_pct(df):
    """Volatilidad histórica anualizada (252 ruedas) expresada como %."""
    if df is None or len(df) < 20:
        return None
    try:
        rets = df['Close'].pct_change().dropna()
        if len(rets) < 20:
            return None
        return round(float(rets.std() * (252 ** 0.5) * 100), 4)
    except:
        return None


def _atr14_series(df):
    """Serie completa de ATR14 (True Range promedio de 14 ruedas), no solo el ultimo valor."""
    try:
        high, low, close = df['High'], df['Low'], df['Close']
        prev = close.shift(1)
        tr = pd.concat([
            high - low,
            (high - prev).abs(),
            (low  - prev).abs()
        ], axis=1).max(axis=1)
        return tr.rolling(14).mean()
    except Exception:
        return None


def avance_pico_15r(df):
    """Avance Pico 15r % — estiramiento reciente medido contra el PICO de la
    ventana, no contra el cierre de hoy. Motivo (caso CVX): si el papel subió
    y corrigió parte en las últimas ruedas, medir cierre-a-cierre esconde el
    estiramiento real; contra el pico queda capturado. cierre_base usa el menor
    entre el cierre de hace 15 ruedas y el mínimo de cierre de la ventana, para
    anclar bien la base de recuperaciones en V. Reemplaza a la vieja
    'Var 10 Ruedas %' (Warren Score v2.3)."""
    if df is None or len(df) < 16:
        return None
    try:
        close, high = df['Close'], df['High']
        pico_15r          = high.tail(15).max()
        cierre_hace_15    = close.iloc[-16]
        min_close_ventana = close.tail(15).min()
        cierre_base       = min(cierre_hace_15, min_close_ventana)
        if cierre_base <= 0:
            return None
        return round(float((pico_15r / cierre_base - 1) * 100), 2)
    except Exception:
        return None


def choppiness_eficiencia(df):
    """Choppiness (ATR14% actual vs hace 20 ruedas) y Eficiencia (Kaufman ER, 10 ruedas).
    Detecta 'volatilidad sin dirección' — velas grandes sin avance neto, firma de
    posible distribución (Warren Score v2.3, caso VOD)."""
    if df is None or len(df) < 35:
        return {'Choppiness': None, 'Eficiencia 10d': None}
    try:
        close = df['Close']
        atr14_abs = _atr14_series(df)
        if atr14_abs is None:
            return {'Choppiness': None, 'Eficiencia 10d': None}
        atr14_pct_ser = atr14_abs / close * 100
        atr_hoy = atr14_pct_ser.iloc[-1]
        atr_20r = atr14_pct_ser.iloc[-21]
        choppiness = (round(float(atr_hoy / atr_20r), 4)
                      if pd.notna(atr_hoy) and pd.notna(atr_20r) and atr_20r > 0 else None)

        cambio_neto = abs(close.iloc[-1] - close.iloc[-11])
        recorrido   = close.tail(11).diff().abs().sum()
        eficiencia  = round(float(cambio_neto / recorrido), 4) if recorrido > 0 else None

        return {'Choppiness': choppiness, 'Eficiencia 10d': eficiencia}
    except Exception:
        return {'Choppiness': None, 'Eficiencia 10d': None}


# ── Panel "Regreso a la EMA200" — visitas raras a la media de largo plazo ──
EMA200_CERCA_ATR = 2.0   # "cerca de la EMA200" = |precio - EMA200| <= CERCA_ATR x ATR14
EMA200_RACHA_MIN = 80    # ruedas minimas de alejamiento previo para que la visita sea "rara" (~4 meses)
EMA200_VENTANA   = 15    # la visita es "actual" si ocurrio dentro de las ultimas 15 ruedas

def visita_ema200(close, ema200, atr14, cerca_atr=EMA200_CERCA_ATR, racha_min=EMA200_RACHA_MIN, ventana=EMA200_VENTANA):
    """
    Detecta visitas raras a la EMA200: un acercamiento actual precedido por
    una racha larga de alejamiento (no la frecuencia anual, que solo informa).
    close/ema200/atr14: arrays o series alineados, mismo largo (>= 260 ruedas).
    """
    try:
        c = np.asarray(close, dtype=float)
        e = np.asarray(ema200, dtype=float)
        a = np.asarray(atr14, dtype=float)
        n = len(c)
        if n < 260:
            return None
        if np.isnan(a[-1]) or a[-1] <= 0:
            return None  # ATR no computable -> el umbral "cerca" tampoco lo es

        valid = ~np.isnan(a) & (a > 0)
        cerca = np.zeros(n, dtype=bool)
        cerca[valid] = np.abs(c[valid] - e[valid]) <= cerca_atr * a[valid]

        freq = round(float(cerca[-252:].mean() * 100), 1) if n >= 252 else round(float(cerca.mean() * 100), 1)
        dist_atrs = round(float((c[-1] - e[-1]) / a[-1]), 2)

        idx_visitas = [i for i in range(max(0, n - ventana), n) if cerca[i]]
        if not idx_visitas:
            return {'visita': False, 'racha': None, 'freq': freq, 'dist_atrs': dist_atrs}

        # inicio del acercamiento actual: retroceder mientras siga "cerca"
        inicio = idx_visitas[0]
        while inicio - 1 >= 0 and cerca[inicio - 1]:
            inicio -= 1

        # racha de alejamiento previa al acercamiento actual
        racha = 0
        j = inicio - 1
        while j >= 0 and not cerca[j]:
            racha += 1
            j -= 1
        # si la racha llega hasta el principio de la serie disponible, se toma tal cual (no None)

        return {'visita': racha >= racha_min, 'racha': racha, 'freq': freq, 'dist_atrs': dist_atrs}
    except Exception:
        return None

def detectar_base(df):
    """
    Detecta la base estructural de un papel (para Warren Score v2 Pilar D).
    Retorna dict con semanas, prof, pos, voltrend — o None en cada campo si no computable.
    """
    NULL = {'semanas': None, 'prof': None, 'pos': None, 'voltrend': None}
    try:
        if df is None or len(df) < 30:
            return NULL
        # Renombrar columnas a minúsculas para uniformidad
        df = df.copy()
        df.columns = [c.lower() for c in df.columns]
        if 'close' not in df.columns or 'high' not in df.columns:
            return NULL

        VENTANA = 130  # ~26 semanas
        reciente = df.tail(VENTANA)
        pivote_alto = reciente['high'].max()
        fecha_pivote = reciente['high'].idxmax()

        # Si el máximo está en las últimas 5 ruedas, retroceder al máximo previo
        if fecha_pivote >= df.index[-5]:
            reciente2 = df.iloc[:-5].tail(VENTANA)
            if len(reciente2) < 10:
                return NULL
            pivote_alto = reciente2['high'].max()
            fecha_pivote = reciente2['high'].idxmax()

        tramo = df.loc[fecha_pivote:]
        if len(tramo) < 10:
            return NULL

        min_base = tramo['low'].min()
        profundidad = (pivote_alto - min_base) / pivote_alto * 100

        # Sin corrección ≥6% = papel vertical sin base (caso CVS)
        if profundidad < 6:
            return NULL

        cierre = float(df['close'].iloc[-1])

        # ¿Rompió hace más de ~3 semanas?
        ruedas_sobre_pivote = int((tramo['close'] > pivote_alto).sum())
        if ruedas_sobre_pivote > 15:
            idx_bo = tramo[tramo['close'] > pivote_alto].index[0]
            tramo = df.loc[fecha_pivote:idx_bo]

        semanas = len(tramo) / 5.0
        posicion = (cierre - min_base) / (pivote_alto - min_base) * 100
        posicion = min(posicion, 130.0)  # clamp

        # Volumen decreciente: último tercio vs primer tercio del tramo
        tercio = max(5, len(tramo) // 3)
        if 'volume' in df.columns:
            vol_ini = float(tramo['volume'].iloc[:tercio].mean())
            vol_fin = float(tramo['volume'].iloc[-tercio:].mean())
            voltrend = round(vol_fin / vol_ini, 2) if vol_ini > 0 else None
        else:
            voltrend = None

        return {
            'semanas':  round(semanas, 1),
            'prof':     round(profundidad, 1),
            'pos':      round(posicion, 1),
            'voltrend': voltrend,
        }
    except Exception as e:
        return NULL


def div_rsi(hist):
    """Divergencia bajista de RSI: precio hace máximos nuevos pero RSI no los confirma."""
    try:
        if hist is None or len(hist) < 20:
            return False
        close = hist['Close']
        delta = close.diff()
        gain  = delta.clip(lower=0).rolling(14, min_periods=14).mean()
        loss  = (-delta.clip(upper=0)).rolling(14, min_periods=14).mean()
        rsi   = (100 - 100 / (1 + gain / loss.replace(0, np.nan))).values
        c     = close.values
        n     = min(40, len(c))
        cw, rw = c[-n:], rsi[-n:]
        # Pivotes confirmados: máximo local con ≥4 ruedas de margen a cada lado
        pivots = [i for i in range(4, n - 4)
                  if all(cw[i] >= cw[i-j] for j in range(1, 5))
                  and all(cw[i] >= cw[i+j] for j in range(1, 5))]
        if len(pivots) < 2:
            return False
        p1, p2 = pivots[-2], pivots[-1]
        if np.isnan(rw[p1]) or np.isnan(rw[p2]):
            return False
        if not bool(cw[p2] > cw[p1] and rw[p2] < rw[p1] - 3):
            return False

        # Anulación: si en las últimas 5 ruedas el precio ya superó el último
        # pivote confirmado y el RSI lo acompañó (no cayó ≥3 pts), el avance
        # reciente objeta la divergencia vieja aunque todavía no sea un
        # pivote "confirmado" (le faltan ruedas futuras para serlo)
        recientes     = cw[-5:]
        rsi_recientes = rw[-5:]
        idx_max       = int(np.argmax(recientes))
        max_reciente  = recientes[idx_max]
        rsi_en_max    = rsi_recientes[idx_max]
        if not np.isnan(rsi_en_max) and max_reciente > cw[p2] and rsi_en_max >= rw[p2] - 3:
            return False

        return True
    except:
        return False


def div_obv(hist, R=3, L=20):
    """'Suba sin combustible' (reemplaza la vieja divergencia de OBV de dos ventanas):
    el precio sigue haciendo maximos pegado al pico de las ultimas L ruedas, pero con
    velas mas chicas y volumen mas seco que el impulso que marco ese pico. Distingue
    agotamiento (sigue subiendo sin fuerza) de compresion sana (lateraliza/corrige)."""
    try:
        if hist is None or len(hist) < L + R + 2:
            return False
        c = hist['Close'].values
        h = hist['High'].values
        l = hist['Low'].values
        v = hist['Volume'].values
        n = len(hist)

        # pico = indice del dia de mayor volumen en las ultimas L ruedas (el impulso real,
        # no el maximo de High — asi no se corre dia a dia mientras el precio hace
        # maximos marginales con volumen decreciente)
        ini  = n - L
        pico = ini + int(np.argmax(v[ini:]))

        # si el pico es demasiado reciente, no hay "despues" que evaluar
        if pico > n - 1 - R:
            return False

        # 1) sigue arriba pero avanza poco (y no se derrumba)
        avance_reciente = (c[-1] - c[-1 - R]) / c[-1 - R] * 100
        cond1 = (c[-1] >= h[pico] * 0.97) and (-3.0 < avance_reciente < 3.5)

        # 2) velas mas chicas que en el impulso
        rango = h - l
        rango_reciente = rango[-R:].mean()
        rango_impulso  = rango[pico - R + 1: pico + 1].mean()
        cond2 = rango_impulso > 0 and (rango_reciente / rango_impulso) < 0.65

        # 3) volumen secandose respecto del impulso
        vol_reciente = v[-R:].mean()
        vol_impulso  = v[pico - R + 1: pico + 1].mean()
        cond3 = vol_impulso > 0 and (vol_reciente / vol_impulso) < 0.70

        return bool(cond1 and cond2 and cond3)
    except:
        return False


def churn_maximos(hist):
    """Churning en máximos: ≥3 días en las últimas 10 ruedas con cierre en mitad inferior y volumen ≥50% sobre el promedio de esas 10 ruedas."""
    try:
        if hist is None or len(hist) < 25:
            return False
        hi  = hist['High'].values
        lo  = hist['Low'].values
        c   = hist['Close'].values
        v   = hist['Volume'].values
        max_20 = hi[-20:].max()
        if max_20 <= 0 or (max_20 - c[-1]) / max_20 * 100 > 4:
            return False
        vol_avg = v[-10:].mean()
        if vol_avg <= 0:
            return False
        count = sum(
            1 for i in range(-10, 0)
            if (hi[i] - lo[i]) > 0
            and (c[i] - lo[i]) / (hi[i] - lo[i]) < 0.5
            and v[i] >= vol_avg * 1.5
        )
        return count >= 3
    except:
        return False


def detectar_vcp(hist, pivot_order=3):
    try:
        h = hist['High'].values
        l = hist['Low'].values
        c = hist['Close'].values
        v = hist['Volume'].values
        # Últimas 90 ruedas
        if len(c) > 90:
            h = h[-90:]; l = l[-90:]; c = c[-90:]; v = v[-90:]
        if len(c) < 30:
            return {'VCP Score': None, 'VCP Detected': False, 'VCP Contractions': 0,
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False}

        def find_pivots(arr, order, mode):
            pivots = []
            for i in range(order, len(arr) - order):
                w = arr[i-order:i+order+1]
                if mode == 'H' and arr[i] >= max(w):
                    pivots.append((i, float(arr[i])))
                elif mode == 'L' and arr[i] <= min(w):
                    pivots.append((i, float(arr[i])))
            return pivots

        ph = find_pivots(h, pivot_order, 'H')
        pl = find_pivots(l, pivot_order, 'L')

        if not ph or not pl:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': 0,
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False}

        all_piv = [(i, 'H', val) for i, val in ph] + [(i, 'L', val) for i, val in pl]
        all_piv.sort()

        contractions = []
        i = 0
        while i < len(all_piv):
            if all_piv[i][1] == 'H':
                hi, _, hval = all_piv[i]
                for j in range(i + 1, len(all_piv)):
                    if all_piv[j][1] == 'L' and all_piv[j][0] > hi:
                        li, _, lval = all_piv[j]
                        if hval > lval:
                            pct     = (hval - lval) / hval * 100
                            seg_vol = float(np.mean(v[hi:li+1])) if li > hi else float(v[hi])
                            contractions.append({'high': hval, 'low': lval, 'pct': pct, 'avg_vol': seg_vol})
                        i = j
                        break
                else:
                    i += 1
            else:
                i += 1

        if len(contractions) < 2:
            return {'VCP Score': 0, 'VCP Detected': False, 'VCP Contractions': len(contractions),
                    'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False}

        pcts = [ct['pct'] for ct in contractions]
        vols = [ct['avg_vol'] for ct in contractions]
        n_c  = len(contractions)
        pairs = n_c - 1

        pct_dec = sum(1 for k in range(pairs) if pcts[k] > pcts[k+1]) / pairs
        vol_dec = sum(1 for k in range(pairs) if vols[k] > vols[k+1]) / pairs

        last_pct       = pcts[-1]
        last_piv_high  = contractions[-1]['high']
        dist_pivot     = (float(c[-1]) - last_piv_high) / last_piv_high * 100

        score = 0
        score += round(pct_dec * 35)
        score += round(vol_dec * 20)
        if last_pct <= 5:    score += 20
        elif last_pct <= 10: score += 15
        elif last_pct <= 15: score += 10
        elif last_pct <= 20: score += 5
        if   -3  <= dist_pivot <= 1:   score += 15
        elif -5  <= dist_pivot < -3:   score += 12
        elif -8  <= dist_pivot < -5:   score += 8
        elif -15 <= dist_pivot < -8:   score += 4
        if n_c >= 4:   score += 10
        elif n_c == 3: score += 7
        elif n_c == 2: score += 4
        score = min(100, score)

        return {
            'VCP Score':          score,
            'VCP Detected':       score >= 60,
            'VCP Contractions':   n_c,
            'VCP Tightness':      round(last_pct, 2),
            'VCP Dist Pivot %':   round(dist_pivot, 2),
            'VCP Vol Decreasing': vol_dec >= 0.5,
        }
    except:
        return {'VCP Score': None, 'VCP Detected': False, 'VCP Contractions': 0,
                'VCP Tightness': None, 'VCP Dist Pivot %': None, 'VCP Vol Decreasing': False}

def calcular_sesiones_10(close, volume):
    """
    Últimas 10 sesiones: días positivos/negativos y volumen acumulado por tipo.
    Un día es positivo si cierre > cierre anterior.
    """
    if len(close) < 11 or len(volume) < 10:
        return None, None, None, None
    precios = close.tail(11).values
    vols    = volume.tail(10).values
    dias_pos, dias_neg = 0, 0
    vol_pos,  vol_neg  = 0.0, 0.0
    for i in range(10):
        cambio = precios[i + 1] - precios[i]
        v      = float(vols[i])
        if cambio > 0:
            dias_pos += 1
            vol_pos  += v
        elif cambio < 0:
            dias_neg += 1
            vol_neg  += v
    return dias_pos, dias_neg, round(vol_pos), round(vol_neg)

def clasificar_market_cap(mc):
    if mc is None:     return "—"
    if mc >= 200e9:    return "Mega Cap"
    if mc >= 10e9:     return "Large Cap"
    if mc >= 2e9:      return "Mid Cap"
    if mc >= 300e6:    return "Small Cap"
    return "Micro Cap"

def obtener_info_ticker(ticker_symbol):
    try:
        info   = yf.Ticker(ticker_symbol).info
        mc     = info.get('marketCap', None)
        sector = info.get('sector', None)
        es_etf = info.get('quoteType', '') in ['ETF', 'MUTUALFUND']
        if es_etf and not sector:
            sector = "ETF"
        if not sector:
            sector = info.get('category', '—') or '—'
        return {
            "Market Cap USD": mc,
            "Market Cap Cat": clasificar_market_cap(mc),
            "Sector":         sector or "—",
            "Tipo":           "ETF" if es_etf else "Acción"
        }
    except:
        return {"Market Cap USD": None, "Market Cap Cat": "—", "Sector": "—", "Tipo": "—"}

def detectar_breakout(hist, lookback=20, vol_factor=1.5, frescura=3):
    """
    3 capas de confirmación del breakout (Minervini):
    1. Precio cruzó el máximo de las últimas `lookback` velas hace ≤ `frescura` días
    2. El volumen ese día fue ≥ `vol_factor` veces el promedio de 50 ruedas
    3. (extensión: Dist SMA50 % — se calcula aparte y se evalúa en el frontend)
    """
    try:
        c = hist['Close'].values
        v = hist['Volume'].values
        if len(c) < lookback + 2:
            return {'Breakout Fresh': False, 'Breakout Days Ago': None,
                    'Breakout Vol OK': False, 'Breakout Vol Ratio': None, 'Pivot': None}

        vol50 = float(np.mean(v[-51:-1])) if len(v) >= 51 else float(np.mean(v[:-1]))

        breakout_day = None
        vol_ratio    = None
        pivot_val    = None

        for ago in range(frescura + 1):
            idx = len(c) - 1 - ago
            if idx < lookback + 1:
                break
            pivot = float(np.max(c[idx - lookback:idx]))
            if float(c[idx]) > pivot and float(c[idx - 1]) <= pivot:
                vr = float(v[idx]) / vol50 if vol50 > 0 else None
                breakout_day = ago
                vol_ratio    = round(vr, 2) if vr is not None else None
                pivot_val    = round(pivot, 2)
                break

        vol_ok = vol_ratio is not None and vol_ratio >= vol_factor
        return {
            'Breakout Fresh':     breakout_day is not None,
            'Breakout Days Ago':  breakout_day,
            'Breakout Vol OK':    vol_ok,
            'Breakout Vol Ratio': vol_ratio,
            'Pivot':              pivot_val,
        }
    except:
        return {'Breakout Fresh': False, 'Breakout Days Ago': None,
                'Breakout Vol OK': False, 'Breakout Vol Ratio': None, 'Pivot': None}


# ── Feedback de breakouts (Capa 3 del Regimen de Mercado) ────────────
# Reemplaza el viejo track record client-side (localStorage, sesgado a
# quien haya abierto el dashboard) por un calculo objetivo sobre todo el
# universo, persistido entre corridas en breakouts_log.json.
FEEDBACK_VENTANA    = 5     # ruedas de gracia tras el breakout
FEEDBACK_COLCHON    = 0.025 # 2.5% bajo el pivote = fallo
FEEDBACK_MIN_MUESTRA = 5    # evaluables minimos para que la capa puntue
FEEDBACK_POBLACION_DIAS = 28  # ventana (calendario) ~20 ruedas para la tasa
FEEDBACK_PRUNE_DIAS  = 35   # se descartan entradas mas viejas que esto

def _procesar_breakout_log(breakouts_log, ticker, hist, brk, hoy_str):
    """Resuelve (si ya maduraron 5 ruedas) las entradas pendientes de este
    ticker, y agrega una entrada nueva si hoy detecto un Breakout Fresh."""
    try:
        fechas_str = [d.strftime('%Y-%m-%d') for d in hist.index]
        closes     = hist['Close'].values

        for entry in breakouts_log:
            if entry['ticker'] != ticker or entry.get('resultado'):
                continue
            try:
                pos = fechas_str.index(entry['fecha_ruptura'])
            except ValueError:
                continue
            ventana = closes[pos + 1: pos + 1 + FEEDBACK_VENTANA]
            if len(ventana) < FEEDBACK_VENTANA:
                continue  # todavia no tiene sus 5 ruedas de gracia completas
            nivel_falla = entry['pivote'] * (1 - FEEDBACK_COLCHON)
            entry['resultado'] = 'fallo' if any(float(cl) < nivel_falla for cl in ventana) else 'sobrevivio'

        if brk.get('Breakout Fresh') and brk.get('Breakout Days Ago') == 0 and brk.get('Pivot'):
            ya_logueado = any(e['ticker'] == ticker and e['fecha_ruptura'] == hoy_str for e in breakouts_log)
            if not ya_logueado:
                breakouts_log.append({
                    'ticker':        ticker,
                    'fecha_ruptura': hoy_str,
                    'pivote':        brk['Pivot'],
                    'resultado':     None,
                })
    except Exception as e:
        print(f"    ⚠️ Error procesando breakout log de {ticker}: {e}")


def calcular_feedback_breakouts(breakouts_log):
    """tasa de supervivencia (0-1) y tamaño de muestra sobre la poblacion
    evaluable reciente. Devuelve (None, n) si la muestra es insuficiente."""
    from datetime import datetime as _dt
    hoy_dt = _dt.now()
    poblacion = [
        e for e in breakouts_log
        if e.get('resultado') and (hoy_dt - _dt.strptime(e['fecha_ruptura'], '%Y-%m-%d')).days <= FEEDBACK_POBLACION_DIAS
    ]
    n = len(poblacion)
    if n < FEEDBACK_MIN_MUESTRA:
        return None, n
    sobrevivieron = sum(1 for e in poblacion if e['resultado'] == 'sobrevivio')
    return round(sobrevivieron / n, 3), n


def calcular_kpis(ticker_symbol, hist_spy, breakouts_log, hoy_str):
    try:
        tk   = yf.Ticker(ticker_symbol)
        hist = tk.history(period="2y")
        if hist.empty or len(hist) < 60:
            return None

        close  = hist["Close"]
        high   = hist["High"]
        low    = hist["Low"]
        volume = hist["Volume"]
        precio_actual = round(close.iloc[-1], 2)

        # Medias móviles
        ema200_series = close.ewm(span=200, adjust=False).mean()
        ema200        = round(ema200_series.iloc[-1], 2)
        ema200_ref    = ema200_series.iloc[-10] if len(ema200_series) >= 10 else ema200_series.iloc[0]
        ema200_slope  = round(ema200 - float(ema200_ref), 4)
        sma50_series  = close.rolling(window=50).mean()
        sma50         = round(sma50_series.iloc[-1], 2)
        sma50_ref     = sma50_series.iloc[-10] if len(sma50_series.dropna()) >= 10 else sma50_series.dropna().iloc[0]
        sma50_slope   = round(sma50 - float(sma50_ref), 4)
        dist_ema200   = round((precio_actual - ema200) / ema200 * 100, 2)
        dist_sma50    = round((precio_actual - sma50)  / sma50  * 100, 2)

        # Máximo y mínimo 52 semanas
        max_52w    = round(close.tail(252).max(), 2)
        dist_max52 = round((precio_actual - max_52w) / max_52w * 100, 2)
        min_52w    = round(close.tail(252).min(), 2)
        dist_min52 = round((precio_actual - min_52w) / min_52w * 100, 2)

        # Variación del día
        var_dia = round((close.iloc[-1] - close.iloc[-2]) / close.iloc[-2] * 100, 2)

        # Avance Pico 15r % — verticalidad reciente, medida contra el pico (Warren Score v2.3)
        avance_pico15r = avance_pico_15r(hist)

        # RSI, Vol Relativa, Volumen inusual
        rsi     = calcular_rsi(close)
        vol_rel = calcular_volatilidad_relativa(close, high, low)
        vol_inu = calcular_volumen_inusual(volume, 20)

        # Sesiones 10 ruedas
        dias_pos_10, dias_neg_10, vol_pos_10, vol_neg_10 = calcular_sesiones_10(close, volume)

        # Vol 5d/40d: ratio volumen promedio últimas 5 ruedas vs últimas 40
        vol_5d_40d = None
        if len(volume) >= 40:
            v5  = volume.tail(5).mean()
            v40 = volume.tail(40).mean()
            if v40 > 0:
                vol_5d_40d = round(v5 / v40, 2)

        # RS Score
        score_actual, score_ayer, score_semana, score_mes, sobre_sma, \
        fr_hoy, fr_ayer, fr_semana, fr_mes = calcular_rs_score(
            close, hist_spy["Close"]
        )

        # VCP
        vcp = detectar_vcp(hist)

        # Base estructural (Warren Score v2 Pilar D)
        base = detectar_base(hist)

        # ATR14 % y Volatilidad Anual % (Warren Score v2.1)
        atr14_p    = atr14_pct(hist)
        vol_anual  = vol_anual_pct(hist)

        # Choppiness + Eficiencia — volatilidad sin dirección (Warren Score v2.3)
        chop = choppiness_eficiencia(hist)

        # Regreso a la EMA200: visita rara a la media de largo plazo
        atr14_ser = _atr14_series(hist)
        visita = visita_ema200(close.values, ema200_series.values, atr14_ser.values) if atr14_ser is not None else None

        # Señales de agotamiento del avance (Warren Score v2.2)
        div_rsi_v  = div_rsi(hist)
        div_obv_v  = div_obv(hist)
        churn_v    = churn_maximos(hist)

        # Breakout fresco
        brk = detectar_breakout(hist)
        _procesar_breakout_log(breakouts_log, ticker_symbol, hist, brk, hoy_str)

        return {
            "Ticker":          ticker_symbol,
            "Precio":          precio_actual,
            "Var Día %":       var_dia,
            "Avance Pico 15r %": avance_pico15r,
            "EMA200":          ema200,
            "EMA200 Slope":    ema200_slope,
            "Dist EMA200 %":   dist_ema200,
            "SMA50":           sma50,
            "SMA50 Slope":     sma50_slope,
            "Dist SMA50 %":    dist_sma50,
            "Máx 52W":         max_52w,
            "Dist Máx52W %":   dist_max52,
            "Mín 52W":         min_52w,
            "Dist Mín52W %":   dist_min52,
            "RSI 14":          rsi,
            "Vol Relativa":    vol_rel,
            "Vol Inusual %":   vol_inu,
            "RS Score":        score_actual,
            "RS Ayer":         score_ayer,
            "RS Semana ant.":  score_semana,
            "RS Mes ant.":     score_mes,
            "FR > SMA50":          sobre_sma,
            "FR Hoy":              fr_hoy,
            "FR Ayer":             fr_ayer,
            "FR Semana ant.":      fr_semana,
            "FR Mes ant.":         fr_mes,
            "VCP Score":           vcp['VCP Score'],
            "VCP Detected":        vcp['VCP Detected'],
            "VCP Contractions":    vcp['VCP Contractions'],
            "VCP Tightness":       vcp['VCP Tightness'],
            "VCP Dist Pivot %":    vcp['VCP Dist Pivot %'],
            "VCP Vol Decreasing":  vcp['VCP Vol Decreasing'],
            "Días + 10s":          dias_pos_10,
            "Días - 10s":          dias_neg_10,
            "Vol días + 10s":      vol_pos_10,
            "Vol días - 10s":      vol_neg_10,
            "Vol 5d/40d":              vol_5d_40d,
            "Breakout Fresh":          brk['Breakout Fresh'],
            "Breakout Days Ago":       brk['Breakout Days Ago'],
            "Breakout Vol OK":         brk['Breakout Vol OK'],
            "Breakout Vol Ratio":      brk['Breakout Vol Ratio'],
            "Breakout Pivot":          brk['Pivot'],
            "Base Semanas":            base['semanas'],
            "Base Profundidad %":      base['prof'],
            "Base Posición %":         base['pos'],
            "Base Vol Trend":          base['voltrend'],
            "ATR14 %":                 atr14_p,
            "Volatilidad Anual %":     vol_anual,
            "Choppiness":              chop['Choppiness'],
            "Eficiencia 10d":          chop['Eficiencia 10d'],
            "Div RSI":                 div_rsi_v,
            "Div OBV":                 div_obv_v,
            "Churn Máximos":           churn_v,
            "EMA200 Visita":           visita['visita']    if visita else False,
            "EMA200 Racha Previa":     visita['racha']     if visita else None,
            "EMA200 Freq %":           visita['freq']      if visita else None,
            "EMA200 Dist ATRs":        visita['dist_atrs'] if visita else None,
        }
    except Exception as e:
        print(f"  ⚠️ Error con {ticker_symbol}: {e}")
        return None

def calcular_regimen(hist_spy, hist_qqq):
    """
    Calcula los scores de régimen de mercado para SPY y QQQ.
    Devuelve un dict compatible con el contrato del frontend (V3 REGIMEN_DATA).
    """
    def analizar_indice(hist):
        c = hist['Close'].squeeze()
        v = hist['Volume'].squeeze()
        h = hist['High'].squeeze()
        l = hist['Low'].squeeze()
        ema50  = c.ewm(span=50,  adjust=False).mean()
        ema200 = c.ewm(span=200, adjust=False).mean()

        # Tendencia (10 pts)
        tend = 0
        if float(c.iloc[-1]) > float(ema50.iloc[-1]):  tend += 4
        if float(c.iloc[-1]) > float(ema200.iloc[-1]): tend += 4
        if len(ema200) >= 21 and float(ema200.iloc[-1]) > float(ema200.iloc[-21]): tend += 2

        # Días de distribución en las últimas 25 ruedas (con expiración +5%)
        ret  = c.pct_change()
        dist = 0
        for i in range(-25, 0):
            try:
                ci = float(c.iloc[i]); ci_prev = float(c.iloc[i-1])
                vi = float(v.iloc[i]); vi_prev = float(v.iloc[i-1])
                hi = float(h.iloc[i]); li = float(l.iloc[i])
                ri = float(ret.iloc[i]) if not pd.isna(ret.iloc[i]) else 0
                cae   = ri <= -0.002
                stall = (0 <= ri < 0.001) and (ci < (hi + li) / 2)
                mas_vol   = vi > vi_prev
                expirado  = float(c.iloc[-1]) >= ci * 1.05
                if (cae or stall) and mas_vol and not expirado:
                    dist += 1
            except:
                pass
        dist_score = max(0, 10 - max(0, dist - 1) * 2)

        # Follow-through / estado del rally (5 pts)
        if float(c.iloc[-1]) > float(ema50.iloc[-1]):
            ftd = 5
        else:
            max_60    = float(c.rolling(60).max().iloc[-1])
            correccion = float(c.iloc[-1]) < max_60 * 0.94
            ret_vals   = ret.values; v_vals = v.values
            hubo_ftd   = any(
                (not pd.isna(ret_vals[i]) and float(ret_vals[i]) >= 0.015
                 and float(v_vals[i]) > float(v_vals[i-1]))
                for i in range(max(-15, -len(ret_vals)), 0)
            )
            ftd = 4 if (correccion and hubo_ftd) else (2 if correccion else 0)

        return int(tend), int(dist), int(dist_score), int(ftd)

    try:
        spy_tend, spy_dist_days, spy_dist_score, spy_ftd = analizar_indice(hist_spy)
        qqq_tend, qqq_dist_days, qqq_dist_score, qqq_ftd = analizar_indice(hist_qqq)
    except Exception as e:
        print(f"  ⚠️  Error analizando índices: {e}")
        return None

    vix = None
    try:
        vix_hist = yf.Ticker('^VIX').history(period='1mo')
        if not vix_hist.empty:
            closes = vix_hist['Close'].dropna()
            if not closes.empty:
                vix = round(float(closes.iloc[-1]), 2)
                print(f"    VIX obtenido: {vix}")
            else:
                print("    ⚠️ VIX: columna Close vacía")
        else:
            print("    ⚠️ VIX: historia vacía")
    except Exception as e:
        print(f"  ⚠️  VIX no disponible: {e}")

    putcall_5d = None
    for pc_ticker in ['^CPCE', '^CPC']:
        try:
            pc_hist = yf.Ticker(pc_ticker).history(period='1mo')
            if not pc_hist.empty:
                closes = pc_hist['Close'].dropna()
                if not closes.empty:
                    putcall_5d = round(float(closes.tail(5).mean() if len(closes) >= 5 else closes.iloc[-1]), 3)
                    print(f"    P/C ratio obtenido de {pc_ticker}: {putcall_5d}")
                    break
                else:
                    print(f"    ⚠️ {pc_ticker}: columna Close vacía")
            else:
                print(f"    ⚠️ {pc_ticker}: historia vacía")
        except Exception as e:
            print(f"  ⚠️  P/C ({pc_ticker}) no disponible: {e}")

    return {
        "fecha":          datetime.now().strftime('%Y-%m-%d'),
        "spy_tendencia":  spy_tend,
        "spy_dist_days":  spy_dist_days,
        "spy_dist_score": spy_dist_score,
        "spy_ftd_score":  spy_ftd,
        "qqq_tendencia":  qqq_tend,
        "qqq_dist_days":  qqq_dist_days,
        "qqq_dist_score": qqq_dist_score,
        "qqq_ftd_score":  qqq_ftd,
        "vix":            vix,
        "putcall_5d":     putcall_5d,
    }


# ── DESCARGA SPY ──────────────────────────────────────────────
print("⏳ Descargando SPY como referencia...")
hist_spy = yf.Ticker("SPY").history(period="2y")

print("⏳ Descargando QQQ para régimen de mercado...")
hist_qqq = yf.Ticker("QQQ").history(period="2y")

print("⏳ Calculando régimen de mercado (SPY/QQQ + VIX + P/C)...")
regimen_data = calcular_regimen(hist_spy, hist_qqq)
if regimen_data:
    spy_pts = regimen_data['spy_tendencia'] + regimen_data['spy_dist_score'] + regimen_data['spy_ftd_score']
    qqq_pts = regimen_data['qqq_tendencia'] + regimen_data['qqq_dist_score'] + regimen_data['qqq_ftd_score']
    print(f"  ✅ SPY {spy_pts}/25 pts | QQQ {qqq_pts}/25 pts | VIX {regimen_data['vix']} | P/C {regimen_data['putcall_5d']}")
else:
    print("  ⚠️  Régimen no disponible, las capas 1 y 4 quedarán inactivas")

# ── CREDENCIALES GITHUB (se necesitan antes del loop para leer breakouts_log.json) ──
import json, base64, requests, os
from datetime import datetime

GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"
gh_headers   = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}

# ── CARGAR BREAKOUTS_LOG.JSON (feedback de breakouts, Capa 3 del regimen) ──
BREAKOUTS_LOG_FILE = "breakouts_log.json"
breakouts_log = []
try:
    resp_bl = requests.get(
        f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{BREAKOUTS_LOG_FILE}",
        headers=gh_headers,
    )
    if resp_bl.status_code == 200:
        breakouts_log = json.loads(base64.b64decode(resp_bl.json()["content"]).decode("utf-8"))
        print(f"  ✅ breakouts_log.json cargado: {len(breakouts_log)} entradas")
    else:
        print("  ℹ️  breakouts_log.json no existe todavía, arranca vacío")
except Exception as e:
    print(f"  ⚠️  Error cargando breakouts_log.json: {e}")

hoy_str = datetime.now().strftime('%Y-%m-%d')

# ── LOOP PRINCIPAL ────────────────────────────────────────────
print("⏳ Calculando KPIs + Market Cap + Sector + Volumen...")
todos_los_datos = []
tickers_procesados = set()

for grupo, tickers in TICKERS.items():
    print(f"\n📂 {grupo}")
    for ticker in list(dict.fromkeys(tickers)):
        if ticker in tickers_procesados:
            continue
        tickers_procesados.add(ticker)
        print(f"  → {ticker}")

        datos = calcular_kpis(ticker, hist_spy, breakouts_log, hoy_str)
        if not datos:
            continue

        datos["Grupo"] = grupo

        info = obtener_info_ticker(ticker)
        datos.update(info)

        sector_etf = ETF_SECTOR.get(ticker, None)
        if sector_etf:
            try:
                t  = yf.Ticker(ticker).history(period="3mo")["Close"]
                s  = yf.Ticker(sector_etf).history(period="3mo")["Close"]
                vs = round(((t.iloc[-1]/t.iloc[0]) / (s.iloc[-1]/s.iloc[0]) - 1) * 100, 2)
                datos["Vs Sector %"] = vs
                datos["ETF Sector"]  = sector_etf
            except:
                datos["Vs Sector %"] = None
                datos["ETF Sector"]  = None
        else:
            datos["Vs Sector %"] = None
            datos["ETF Sector"]  = None

        todos_los_datos.append(datos)

df = pd.DataFrame(todos_los_datos)
print(f"\n✅ Datos listos: {len(df)} tickers")
print(df[["Ticker", "Dist Mín52W %", "Vol Relativa", "RS Score", "Sector", "Market Cap Cat"]].head(10).to_string(index=False))

# ── PRUNE + FEEDBACK DE BREAKOUTS (Capa 3 del regimen) ────────
breakouts_log = [
    e for e in breakouts_log
    if (datetime.now() - datetime.strptime(e['fecha_ruptura'], '%Y-%m-%d')).days <= FEEDBACK_PRUNE_DIAS
]
feedback_tasa, feedback_n = calcular_feedback_breakouts(breakouts_log)
if regimen_data:
    regimen_data['feedback_tasa'] = feedback_tasa
    regimen_data['feedback_n']    = feedback_n
if feedback_tasa is not None:
    print(f"  ✅ Feedback breakouts: {feedback_tasa*100:.0f}% supervivencia sobre {feedback_n} evaluables")
else:
    print(f"  ℹ️  Feedback breakouts: muestra insuficiente ({feedback_n} evaluables)")

# ── EXPORTAR A GITHUB ──────────────────────────────────────────
headers = gh_headers

datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str       = json.dumps(datos_export, ensure_ascii=False)

# Guardar copia local
with open("datos.json", "w", encoding="utf-8") as _f:
    _f.write(json_str)

contenido_b64  = base64.b64encode(json_str.encode()).decode()
headers        = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url            = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

resp = requests.get(url, headers=headers)
sha  = resp.json().get("sha") if resp.status_code == 200 else None

payload = {"message": f"Auto-update {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": contenido_b64}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"\n✅ datos.json actualizado con {len(datos_export)} tickers")
else:
    print(f"\n❌ Error subiendo JSON: {resp.status_code} — {resp.json().get('message')}")
    exit(1)

# ── EXPORTAR DATOS_VIERNES_CIERRE.JSON (snapshot fijo del Top10 semanal) ──
# Solo se pisa en la corrida de cierre (17:00 ARG) de un viernes, para que quede
# fija toda la semana hasta el próximo cierre. RUN_SCHEDULE viene del workflow
# (github.event.schedule) y viene vacío en corridas manuales (workflow_dispatch),
# que por eso no la disparan.
CIERRE_VIERNES_ARCHIVO = "datos_viernes_cierre.json"
es_corrida_cierre = os.environ.get("RUN_SCHEDULE") == "0 20 * * 1-5"
es_viernes = datetime.utcnow().weekday() == 4
if es_corrida_cierre and es_viernes:
    snapshot = {"fecha": datetime.utcnow().strftime('%Y-%m-%d'), "datos": datos_export}
    snapshot_str = json.dumps(snapshot, ensure_ascii=False)
    snapshot_b64 = base64.b64encode(snapshot_str.encode()).decode()
    url_snap = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{CIERRE_VIERNES_ARCHIVO}"
    resp_snap = requests.get(url_snap, headers=headers)
    sha_snap  = resp_snap.json().get("sha") if resp_snap.status_code == 200 else None
    payload_snap = {"message": f"Snapshot cierre viernes {datetime.utcnow().strftime('%d/%m/%Y')}", "content": snapshot_b64}
    if sha_snap:
        payload_snap["sha"] = sha_snap
    resp_snap = requests.put(url_snap, headers=headers, json=payload_snap)
    if resp_snap.status_code in [200, 201]:
        print(f"✅ {CIERRE_VIERNES_ARCHIVO} actualizado (cierre de viernes)")
    else:
        print(f"⚠️  Error subiendo {CIERRE_VIERNES_ARCHIVO}: {resp_snap.status_code} — {resp_snap.json().get('message')}")
else:
    print(f"ℹ️  {CIERRE_VIERNES_ARCHIVO} no se toca en esta corrida (no es cierre de viernes)")

# ── EXPORTAR REGIMEN.JSON A GITHUB ────────────────────────────
if regimen_data:
    regimen_str = json.dumps(regimen_data, ensure_ascii=False)
    regimen_b64 = base64.b64encode(regimen_str.encode()).decode()
    url_reg = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/regimen.json"
    resp_reg = requests.get(url_reg, headers=headers)
    sha_reg  = resp_reg.json().get("sha") if resp_reg.status_code == 200 else None
    payload_reg = {"message": f"Auto-update régimen {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": regimen_b64}
    if sha_reg:
        payload_reg["sha"] = sha_reg
    resp_reg = requests.put(url_reg, headers=headers, json=payload_reg)
    if resp_reg.status_code in [200, 201]:
        print(f"✅ regimen.json actualizado en GitHub")
    else:
        print(f"⚠️  Error subiendo regimen.json: {resp_reg.status_code} — {resp_reg.json().get('message')}")
else:
    print("⚠️  regimen.json no exportado (datos insuficientes)")

# ── EXPORTAR BREAKOUTS_LOG.JSON A GITHUB (feedback Capa 3) ────
breakouts_str = json.dumps(breakouts_log, ensure_ascii=False)
breakouts_b64 = base64.b64encode(breakouts_str.encode()).decode()
url_bl = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{BREAKOUTS_LOG_FILE}"
resp_bl = requests.get(url_bl, headers=headers)
sha_bl  = resp_bl.json().get("sha") if resp_bl.status_code == 200 else None
payload_bl = {"message": f"Auto-update breakouts_log {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": breakouts_b64}
if sha_bl:
    payload_bl["sha"] = sha_bl
resp_bl = requests.put(url_bl, headers=headers, json=payload_bl)
if resp_bl.status_code in [200, 201]:
    print(f"✅ breakouts_log.json actualizado ({len(breakouts_log)} entradas)")
else:
    print(f"⚠️  Error subiendo breakouts_log.json: {resp_bl.status_code} — {resp_bl.json().get('message')}")

# ── EXPORTAR RS_HISTORIA.JSON A GITHUB (V7 RRG ETFs) ─────────
SECTOR_ETFS_RRG = ['XLK','XLE','XLF','XLV','XLI','XLY','XLP','XLU','XLB','XLRE','XLC',
                   'SMH','CIBR','CLOU','BOTZ','IBB','ITA','KRE','XOP','ICLN','URA',
                   'QQQ','GLD','GDX','SLV','EWZ','FXI','ARGT','TLT','IWM','DIA']
RS_HISTORIA_SEMANAS = 16
RS_LOOKBACK = 12

def calcular_rs_historia():
    try:
        import yfinance as yf
        import numpy as np
        raw = yf.download(SECTOR_ETFS_RRG + ['SPY'], period='2y', interval='1d',
                          auto_adjust=True, progress=False)
        datos_yf = raw['Close'] if isinstance(raw.columns, pd.MultiIndex) else raw
        weekly = datos_yf.resample('W-FRI').last().dropna(how='all')
        spy = weekly['SPY'].dropna()
        filas = []
        for t in SECTOR_ETFS_RRG:
            if t not in weekly.columns:
                continue
            serie = weekly[t].dropna()
            idx = serie.index.intersection(spy.index)
            if len(idx) < RS_LOOKBACK + 4:
                continue
            ratio = 100 * serie[idx] / spy[idx]
            media = ratio.rolling(RS_LOOKBACK).mean()
            std   = ratio.rolling(RS_LOOKBACK).std().replace(0, np.nan)
            z     = ((ratio - media) / std).clip(-4, 4)
            rs_ratio = (100 + z).round(2)
            rs_mom   = (100 + (rs_ratio - rs_ratio.rolling(4).mean()) * 2).clip(96, 104).round(2)
            df_t = pd.DataFrame({'rs_ratio': rs_ratio, 'rs_mom': rs_mom}).dropna()
            for fecha, row_rs in df_t.tail(RS_HISTORIA_SEMANAS).iterrows():
                filas.append({
                    'fecha':    fecha.strftime('%Y-%m-%d'),
                    'ticker':   t,
                    'rs_ratio': float(row_rs['rs_ratio']),
                    'rs_mom':   float(row_rs['rs_mom'])
                })
        return filas
    except Exception as e:
        print(f'[RS_HISTORIA] Error: {e}')
        return []

try:
    rs_historia = calcular_rs_historia()
    if rs_historia:
        rs_str = json.dumps(rs_historia, ensure_ascii=False)
        rs_b64 = base64.b64encode(rs_str.encode()).decode()
        url_rs = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/rs_historia.json"
        resp_rs = requests.get(url_rs, headers=headers)
        sha_rs  = resp_rs.json().get("sha") if resp_rs.status_code == 200 else None
        payload_rs = {"message": f"Auto-update RS historia {datetime.now().strftime('%d/%m/%Y %H:%M')}", "content": rs_b64}
        if sha_rs:
            payload_rs["sha"] = sha_rs
        resp_rs = requests.put(url_rs, headers=headers, json=payload_rs)
        if resp_rs.status_code in [200, 201]:
            print(f"✅ rs_historia.json actualizado: {len(rs_historia)} filas")
        else:
            print(f"⚠️  Error subiendo rs_historia.json: {resp_rs.status_code} — {resp_rs.json().get('message')}")
    else:
        print("⚠️  rs_historia.json vacío, no exportado")
except Exception as e:
    print(f"⚠️  rs_historia.json: {e}")

# ── FIN — el resto de las celdas son solo para Colab ──────────
import sys; sys.exit(0)

import gspread
from google.colab import auth
from google.auth import default

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

sh = gc.open_by_key(SHEET_ID)

try:
    ws = sh.worksheet("Dashboard")
    ws.clear()
except:
    ws = sh.add_worksheet(title="Dashboard", rows=500, cols=25)

columnas = [
    "Grupo", "Ticker", "Precio", "Var Día %",
    "EMA200", "EMA200 Slope", "Dist EMA200 %",
    "SMA50",  "Dist SMA50 %",
    "Máx 52W", "Dist Máx52W %",
    "Mín 52W", "Dist Mín52W %",
    "RSI 14", "Vol Relativa", "Vol Inusual %",
    "RS Score", "RS Ayer", "RS Semana ant.", "RS Mes ant.", "FR > SMA50",
    "FR Hoy", "FR Ayer", "FR Semana ant.", "FR Mes ant.",
    "Market Cap USD", "Market Cap Cat", "Sector", "Tipo",
    "ETF Sector", "Vs Sector %"
]

df_export = df[columnas]

ws.update(values=[df_export.columns.tolist()] + df_export.fillna("—").values.tolist(), range_name="A1")
ws.update(values=[[f"Actualizado: {datetime.now().strftime('%d/%m/%Y %H:%M')}"]], range_name="A1")

print(f"✅ Sheet actualizado con {len(df)} tickers y {len(columnas)} columnas")
print(f"🔗 https://docs.google.com/spreadsheets/d/{SHEET_ID}")

# ============================================
# CELDA 5 — FORMATO VISUAL DEL DASHBOARD
# ============================================
import gspread
from gspread_formatting import (
    CellFormat, Color, TextFormat, BooleanRule, BooleanCondition,
    ConditionalFormatRule, GridRange, format_cell_range,
    get_conditional_format_rules, set_column_width
)

ws = sh.worksheet("Dashboard")

# --- Congelar primera fila ---
ws.freeze(rows=1)

# --- Color de encabezado (azul oscuro) ---
header_format = CellFormat(
    backgroundColor=Color(0.13, 0.27, 0.49),
    textFormat=TextFormat(bold=True, foregroundColor=Color(1, 1, 1), fontSize=10),
    horizontalAlignment="CENTER"
)
format_cell_range(ws, "A1:N1", header_format)

# --- Formato condicional semáforo ---
rules = get_conditional_format_rules(ws)
rules.clear()

for col in ["D", "F", "H", "J", "K", "M"]:
    # Verde para positivos
    rules.append(ConditionalFormatRule(
        ranges=[GridRange.from_a1_range(f"{col}2:{col}500", ws)],
        booleanRule=BooleanRule(
            condition=BooleanCondition("NUMBER_GREATER", ["0"]),
            format=CellFormat(backgroundColor=Color(0.71, 0.92, 0.71))
        )
    ))
    # Rojo para negativos
    rules.append(ConditionalFormatRule(
        ranges=[GridRange.from_a1_range(f"{col}2:{col}500", ws)],
        booleanRule=BooleanRule(
            condition=BooleanCondition("NUMBER_LESS", ["0"]),
            format=CellFormat(backgroundColor=Color(0.96, 0.71, 0.71))
        )
    ))

rules.save()

# --- Anchos de columna ---
set_column_width(ws, "A", 120)
set_column_width(ws, "B", 70)
set_column_width(ws, "C", 80)
set_column_width(ws, "D", 80)
set_column_width(ws, "E", 80)
set_column_width(ws, "F", 110)
set_column_width(ws, "G", 70)
set_column_width(ws, "H", 105)
set_column_width(ws, "I", 80)
set_column_width(ws, "J", 110)
set_column_width(ws, "K", 105)
set_column_width(ws, "L", 90)
set_column_width(ws, "M", 100)

print("✅ Formato aplicado correctamente")

# ============================================
# CELDA 6 — EXPORTAR DATOS COMO JSON PARA DASHBOARD
# ============================================
import json

# Convertimos el dataframe a JSON limpio
datos_json = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_json.append(item)

# Guardamos en el Sheet en una hoja separada llamada "JSON"
try:
    ws_json = sh.worksheet("JSON")
    ws_json.clear()
except:
    ws_json = sh.add_worksheet(title="JSON", rows=len(datos_json)+5, cols=2)

# Una fila por ticker (evita el límite de 50k caracteres por celda)
filas = [[json.dumps(item)] for item in datos_json]
ws_json.update(values=filas, range_name="A1")

print(f"✅ JSON exportado: {len(datos_json)} tickers en {len(filas)} filas")
print(f"📋 Campos disponibles: {list(datos_json[0].keys())}")

# ============================================
# CELDA 7 — GENERAR ARCHIVO HTML CON DATOS EMBEBIDOS
# ============================================
import json
from google.colab import files

# Convertimos los datos a JSON
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)

# Leemos el template HTML y reemplazamos la URL por los datos embebidos
html_template = '''<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<script>
const DATOS_EMBEBIDOS = ''' + json_str + ''';
</script>
</head>
<body>
<script>
// Redirect a la version completa
window.location.href = "dashboard_cedears.html";
</script>
</body>
</html>'''

# Guardamos el JSON como archivo separado que el HTML puede leer
with open('datos_cedears.json', 'w', encoding='utf-8') as f:
    json.dump(datos_export, f, ensure_ascii=False)

files.download('datos_cedears.json')
print(f"✅ JSON descargado con {len(datos_export)} tickers")
print("Guardá el archivo datos_cedears.json en la misma carpeta que el dashboard_cedears.html")

# ============================================
# CELDA 8 — DESCARGA HTML COMPLETO CON DATOS EMBEBIDOS
# ============================================
import json, urllib.request
from google.colab import files

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)

print(f"✅ {len(datos_export)} tickers preparados")
print(f"📦 Tamaño del JSON: {len(json_str)//1024} KB")
print("Pegá este resultado en Claude para que genere el HTML final")
print("\n--- PRIMERAS 3 FILAS (para verificar) ---")
for d in datos_export[:3]:
    print(d.get('Ticker'), '|', d.get('RS Score'), '|', d.get('Volatilidad 20d'))

# ============================================
# CELDA 9 — SUBIR JSON A GITHUB
# ============================================
import json, base64, requests
from datetime import datetime

GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)
contenido_b64 = base64.b64encode(json_str.encode()).decode()

headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

resp = requests.get(url, headers=headers)
sha = resp.json().get("sha") if resp.status_code == 200 else None

payload = {
    "message": f"Actualización datos {datetime.now().strftime('%d/%m/%Y %H:%M')}",
    "content": contenido_b64
}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"✅ datos.json subido a GitHub con {len(datos_export)} tickers")
    print(f"📋 Campos: {list(datos_export[0].keys())}")
else:
    print(f"❌ Error: {resp.status_code} — {resp.json().get('message')}")

import os
archivos = os.listdir('/content')
print([f for f in archivos if 'dashboard' in f.lower()])

with open('dashboard_v2_template.html', 'r', encoding='utf-8') as f:
    contenido = f.read()

print("Tamaño template:", len(contenido), "chars")
print("Tiene placeholder:", '##JSON_PLACEHOLDER##' in contenido)
print("Primeras 200 chars del script:", contenido[contenido.find('<script>'): contenido.find('<script>')+200])

# ============================================
# CELDA 10 — SUBE LOS DATOS DIRECTO A GITHUB
# ============================================
import json, base64, requests

# ── CONFIGURACIÓN ──
GITHUB_TOKEN = os.environ.get("PAT_TOKEN")
GITHUB_USER  = "WarrenBife"
GITHUB_REPO  = "cedears-dashboard"
ARCHIVO      = "datos.json"

# Convertimos datos
datos_export = []
for _, row in df.iterrows():
    item = {}
    for col in df.columns:
        val = row[col]
        if pd.isna(val) if not isinstance(val, bool) else False:
            item[col] = None
        elif val == "—":
            item[col] = None
        elif isinstance(val, bool):
            item[col] = val
        elif isinstance(val, (int, float)):
            item[col] = round(float(val), 2)
        else:
            item[col] = str(val)
    datos_export.append(item)

json_str = json.dumps(datos_export, ensure_ascii=False)
contenido_b64 = base64.b64encode(json_str.encode()).decode()

# Subimos a GitHub via API
headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
url = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{ARCHIVO}"

# Verificamos si el archivo ya existe (para actualizarlo)
resp = requests.get(url, headers=headers)
sha = resp.json().get("sha") if resp.status_code == 200 else None

payload = {
    "message": f"Actualización datos {datetime.now().strftime('%d/%m/%Y %H:%M')}",
    "content": contenido_b64
}
if sha:
    payload["sha"] = sha

resp = requests.put(url, headers=headers, json=payload)
if resp.status_code in [200, 201]:
    print(f"✅ datos.json subido a GitHub con {len(datos_export)} tickers")
    print(f"🔗 https://{GITHUB_USER}.github.io/{GITHUB_REPO}/datos.json")
else:
    print(f"❌ Error: {resp.status_code} — {resp.json().get('message')}")

# ============================================
# CELDA 12 — BOT TELEGRAM TOP 5 RS DIARIO
# ============================================
import requests
from datetime import datetime

TELEGRAM_TOKEN   = "8608163960:AAEZpmmU0So3hwG-aNb6Slyjbz5DBOHDzvU"
TELEGRAM_CHAT_ID = "1673990665"

def enviar_mensaje(texto):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    requests.post(url, json={
        "chat_id": TELEGRAM_CHAT_ID,
        "text": texto,
        "parse_mode": "HTML"
    })

# Calculamos variación diaria de RS (RS Score - RS Ayer)
df_bot = df.copy()
df_bot['Delta RS Dia'] = df_bot['RS Score'] - df_bot['RS Ayer']

# Filtramos solo acciones (no ETFs) con RS Score válido
df_bot = df_bot[
    (df_bot['RS Score'].notna()) &
    (df_bot['RS Ayer'].notna()) &
    (df_bot['Tipo'] == 'Acción')
].copy()

# TOP 5 mayor aumento de RS en el día
top5 = df_bot.nlargest(5, 'Delta RS Dia')

# Armamos el mensaje
fecha = datetime.now().strftime('%d/%m/%Y')
hora  = datetime.now().strftime('%H:%M')

msg = f"📊 <b>TOP 5 — Mayor aumento de RS Score</b>\n"
msg += f"📅 {fecha} | ⏰ {hora}\n"
msg += f"━━━━━━━━━━━━━━━━━━━━\n\n"

medallas = ['🥇','🥈','🥉','4️⃣','5️⃣']

for i, (_, row) in enumerate(top5.iterrows()):
    delta = row['Delta RS Dia']
    rs    = row['RS Score']
    ayer  = row['RS Ayer']
    sector = row['Sector'] or '—'

    msg += f"{medallas[i]} <b>{row['Ticker']}</b>\n"
    msg += f"   RS: <b>{rs}</b>  (ayer: {ayer})  <b>▲+{delta:.1f}</b>\n"
    msg += f"   Sector: {sector}\n\n"

msg += f"━━━━━━━━━━━━━━━━━━━━\n"
msg += f"<i>Warren Bife Indicator</i>"

enviar_mensaje(msg)
print(f"✅ Mensaje enviado a Telegram")
print(f"\n🏆 TOP 5 mayor aumento RS Score:")
print(top5[['Ticker','RS Score','RS Ayer','Delta RS Dia','Sector']].to_string(index=False))